#!/usr/bin/env python3
"""Emit the curated RagasBench dataset as JSON.

Synthetic, authored for the model-loader RAG-quality benchmark: 20 scenarios.
Each scenario gives the model a small set of documents and a question whose
answer is fully contained in exactly one document. A grader later scores
faithfulness (no claims beyond the docs), answer relevancy, and context
precision against groundTruth / expectedContext.

Reproduce:  python3 tools/ragas-curate/main.py > \
    internal/service/benchmark/data/ragas_curated.json
"""
import json
import sys

# (id, [documents], question, ground_truth, expected_context)
SCENARIOS = [
    ("rag-01",
     ["The Aldebaran rover landed in the Vallis Marineris region on March 3, 2031.",
      "The mission was funded jointly by three national space agencies.",
      "Its primary instrument is a deep-drilling spectrometer."],
     "On what date did the Aldebaran rover land?",
     "March 3, 2031.",
     "The Aldebaran rover landed in the Vallis Marineris region on March 3, 2031."),
    ("rag-02",
     ["Quartzine is a fictional alloy with a melting point of 2,140 degrees Celsius.",
      "It is prized for corrosion resistance in marine turbines."],
     "What is the melting point of quartzine?",
     "2,140 degrees Celsius.",
     "Quartzine is a fictional alloy with a melting point of 2,140 degrees Celsius."),
    ("rag-03",
     ["The Béker Prize in linguistics was first awarded in 1962.",
      "It carries a cash award and a two-year research fellowship."],
     "In what year was the Béker Prize first awarded?",
     "1962.",
     "The Béker Prize in linguistics was first awarded in 1962."),
    ("rag-04",
     ["The novel 'Tideglass' was written by Marin Holloway over seven years.",
      "It is set in a drowned coastal city named Sarn."],
     "Who wrote the novel 'Tideglass'?",
     "Marin Holloway.",
     "The novel 'Tideglass' was written by Marin Holloway over seven years."),
    ("rag-05",
     ["Project Halberd reduced packet loss by 38% in field trials.",
      "The trials ran across twelve metropolitan test sites."],
     "By how much did Project Halberd reduce packet loss?",
     "38%.",
     "Project Halberd reduced packet loss by 38% in field trials."),
    ("rag-06",
     ["The Sundara Festival is held every third year in the city of Pell.",
      "It centers on traditional kite-making competitions."],
     "How often is the Sundara Festival held?",
     "Every third year.",
     "The Sundara Festival is held every third year in the city of Pell."),
    ("rag-07",
     ["Enzyme XR-9 catalyzes the breakdown of microplastics at room temperature.",
      "It was isolated from a deep-sea bacterium in 2029."],
     "What does enzyme XR-9 break down?",
     "Microplastics.",
     "Enzyme XR-9 catalyzes the breakdown of microplastics at room temperature."),
    ("rag-08",
     ["The Korrin Bridge spans 1,480 meters across the Vasser Strait.",
      "It opened to traffic after nine years of construction."],
     "How long is the Korrin Bridge?",
     "1,480 meters.",
     "The Korrin Bridge spans 1,480 meters across the Vasser Strait."),
    ("rag-09",
     ["Dr. Imani Sefu chairs the Coastal Resilience Council.",
      "The council advises on flood-defense policy for twelve provinces."],
     "Who chairs the Coastal Resilience Council?",
     "Dr. Imani Sefu.",
     "Dr. Imani Sefu chairs the Coastal Resilience Council."),
    ("rag-10",
     ["The game 'Latticefall' sold 4.2 million copies in its first month.",
      "It was developed by a studio of just nine people."],
     "How many copies did 'Latticefall' sell in its first month?",
     "4.2 million.",
     "The game 'Latticefall' sold 4.2 million copies in its first month."),
    ("rag-11",
     ["Vantium decays with a half-life of 19 days.",
      "It is used as a tracer in hydrology studies."],
     "What is the half-life of vantium?",
     "19 days.",
     "Vantium decays with a half-life of 19 days."),
    ("rag-12",
     ["The treaty of Oren Bay was signed by five coastal nations in 1998.",
      "It established shared fishing quotas."],
     "How many nations signed the treaty of Oren Bay?",
     "Five.",
     "The treaty of Oren Bay was signed by five coastal nations in 1998."),
    ("rag-13",
     ["The Marrow Line subway carries 600,000 riders daily.",
      "It connects the harbor district to the northern suburbs."],
     "How many riders does the Marrow Line carry daily?",
     "600,000.",
     "The Marrow Line subway carries 600,000 riders daily."),
    ("rag-14",
     ["Solenne coffee is grown only on the slopes of Mount Yaru.",
      "Its beans are harvested entirely by hand."],
     "Where is Solenne coffee grown?",
     "On the slopes of Mount Yaru.",
     "Solenne coffee is grown only on the slopes of Mount Yaru."),
    ("rag-15",
     ["The Pareli telescope has a primary mirror 11 meters in diameter.",
      "It observes primarily in the mid-infrared band."],
     "How large is the Pareli telescope's primary mirror?",
     "11 meters in diameter.",
     "The Pareli telescope has a primary mirror 11 meters in diameter."),
    ("rag-16",
     ["The Wexler protocol requires three independent confirmations before release.",
      "It was adopted by the consortium in 2025."],
     "How many independent confirmations does the Wexler protocol require?",
     "Three.",
     "The Wexler protocol requires three independent confirmations before release."),
    ("rag-17",
     ["The Talin reservoir holds 320 million cubic meters of water.",
      "It supplies drinking water to two cities."],
     "How much water does the Talin reservoir hold?",
     "320 million cubic meters.",
     "The Talin reservoir holds 320 million cubic meters of water."),
    ("rag-18",
     ["Composer Nadia Brevik wrote the symphony 'Ashlight' in 2014.",
      "It premiered with a choir of two hundred voices."],
     "Who composed 'Ashlight'?",
     "Nadia Brevik.",
     "Composer Nadia Brevik wrote the symphony 'Ashlight' in 2014."),
    ("rag-19",
     ["The Verda standard mandates a maximum latency of 50 milliseconds.",
      "It applies to all real-time control systems in the network."],
     "What maximum latency does the Verda standard mandate?",
     "50 milliseconds.",
     "The Verda standard mandates a maximum latency of 50 milliseconds."),
    ("rag-20",
     ["The Hollow Pines trail is 27 kilometers long and rated difficult.",
      "It gains 1,900 meters of elevation."],
     "How long is the Hollow Pines trail?",
     "27 kilometers.",
     "The Hollow Pines trail is 27 kilometers long and rated difficult."),
]


def main():
    items = [{
        "id": pid,
        "documents": docs,
        "question": q,
        "groundTruth": gt,
        "expectedContext": ctx,
    } for pid, docs, q, gt, ctx in SCENARIOS]
    json.dump(items, sys.stdout, indent=2, ensure_ascii=False)
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
