package backendschema

import "github.com/quantmind-br/model-loader/internal/domain"

const (
	sglangGroupEssentials                       = "Essentials"
	sglangGroupServidorEGeral                   = "1. Server and General"
	sglangGroupModeloETokenizer                 = "2. Model and Tokenizer"
	sglangGroupCarregamentoDePesos              = "3. Weight Loading"
	sglangGroupDtypeEQuantizacao                = "4. Dtype and Quantization"
	sglangGroupMemoriaEKvCache                  = "5. Memory and KV Cache"
	sglangGroupCacheDePrefixoRadixEHierarquico  = "6. Prefix Cache: Radix and Hierarchical"
	sglangGroupPrefillChunkingEScheduler        = "7. Prefill, Chunking, and Scheduler"
	sglangGroupStreamingSamplingEGramatica      = "8. Streaming, Sampling, and Grammar"
	sglangGroupParalelismoEExecucaoDistribuida  = "9. Parallelism and Distributed Execution"
	sglangGroupMoeEExpertParallelism            = "10. MoE and Expert Parallelism"
	sglangGroupBackendsDeAtencaoEGemm           = "11. Attention and GEMM Backends"
	sglangGroupAtencaoEsparsaNsaEDoubleSparsity = "12. Sparse Attention (NSA and Double Sparsity)"
	sglangGroupMambaSsm                         = "13. Mamba (SSM)"
	sglangGroupLora                             = "14. LoRA"
	sglangGroupSpeculativeDecoding              = "15. Speculative Decoding"
	sglangGroupCudaGraphETorchCompile           = "16. CUDA Graph and torch.compile"
	sglangGroupComunicacaoEAllReduce            = "17. Communication and All-Reduce"
	sglangGroupOffloadDePesosEMemorySaver       = "18. Weight Offload and Memory Saver"
	sglangGroupMultimodalEEncoder               = "19. Multimodal and Encoder"
	sglangGroupApiOpenaiEParsers                = "20. OpenAI API and Parsers"
	sglangGroupLoggingMetricasETracing          = "21. Logging, Metrics, and Tracing"
	sglangGroupPdDisaggregation                 = "22. PD disaggregation"
	sglangGroupDebugDeterminismoEDiversos       = "23. Debug, Determinism, and Miscellaneous"
	sglangGroupServidorDeModelosDeDifusao       = "24. Diffusion Model Server"
)

// CuratedSGLangSchema returns the hand-curated sglang serve schema based on sglang.md.
// The model path flags are intentionally omitted because model-loader handles model selection separately.
func CuratedSGLangSchema() domain.BackendValidationSchema {
	flags := map[string]domain.FlagSpec{}
	add := func(spec domain.FlagSpec) { flags[spec.Long] = spec }
	for _, spec := range []domain.FlagSpec{
		strFlag("host", "", nil, nil, "HTTP server address.", sglangGroupServidorEGeral, false),
		portFlag("port", "", 30000, "HTTP server port.", sglangGroupServidorEGeral),
		strFlag("fastapi-root-path", "", nil, nil, "FastAPI `root_path` behind a path-routing proxy.", sglangGroupServidorEGeral, false),
		boolFlag("grpc-mode", "", nil, false, "Uses gRPC server instead of HTTP.", sglangGroupServidorEGeral),
		strFlag("config", "", nil, nil, "Reads CLI options from a YAML file.", sglangGroupServidorEGeral, false),
		boolFlag("skip-server-warmup", "", nil, false, "Skips server warmup.", sglangGroupServidorEGeral),
		strFlag("warmups", "", nil, nil, "Custom warmup functions (from `warmup.py`).", sglangGroupServidorEGeral, false),
		intFlag("nccl-port", "", nil, nil, "Port for distributed NCCL setup (random default).", sglangGroupServidorEGeral, nil, nil),
		boolFlag("checkpoint-engine-wait-weights-before-ready", "", nil, false, "Waits for initial weights before serving.", sglangGroupServidorEGeral),
		intFlag("watchdog-timeout", "", nil, nil, "Crashes if a forward batch exceeds the timeout (prevents hangs).", sglangGroupServidorEGeral, nil, nil),
		intFlag("soft-watchdog-timeout", "", nil, nil, "Dumps debug info if a forward batch exceeds the timeout (no crash).", sglangGroupServidorEGeral, nil, nil),
		intFlag("dist-timeout", "", nil, nil, "`torch.distributed` timeout.", sglangGroupServidorEGeral, nil, nil),
		strFlag("custom-sigquit-handler", "", nil, nil, "Custom SIGQUIT handler (Engine only).", sglangGroupServidorEGeral, false),
		boolFlag("sleep-on-idle", "", nil, false, "Reduces CPU usage while idle.", sglangGroupServidorEGeral),
		intFlag("base-gpu-id", "", nil, 0, "Initial GPU for allocation.", sglangGroupServidorEGeral, nil, nil),
		intFlag("gpu-id-step", "", nil, 1, "Step between GPU IDs (e.g. `2` uses GPU 0,2,4...).", sglangGroupServidorEGeral, nil, nil),
		strFlag("numa-node", "", nil, nil, "NUMA node for each subprocess.", sglangGroupServidorEGeral, false),
		intFlag("scheduler-recv-interval", "", nil, nil, "Request polling interval in the scheduler.", sglangGroupServidorEGeral, nil, nil),
		strFlag("tokenizer-path", "", nil, "= model-path", "Tokenizer path.", sglangGroupModeloETokenizer, false),
		enumFlag("tokenizer-mode", "", nil, []string{"auto", "slow"}, "auto", "Tokenizer mode (`auto` uses fast when available).", sglangGroupModeloETokenizer),
		intFlag("tokenizer-worker-num", "", nil, nil, "Tokenizer manager workers.", sglangGroupModeloETokenizer, nil, nil),
		boolFlag("skip-tokenizer-init", "", nil, false, "Skips tokenizer init; expects `input_ids`.", sglangGroupModeloETokenizer),
		boolFlag("trust-remote-code", "", nil, false, "Allows custom Hub code.", sglangGroupModeloETokenizer),
		intFlag("context-length", "", nil, nil, "Maximum context; `None` uses the value from `config.json`.", sglangGroupModeloETokenizer, nil, nil),
		boolFlag("is-embedding", "", nil, false, "Uses a CausalLM as an embedding model.", sglangGroupModeloETokenizer),
		boolFlag("enable-multimodal", "", nil, false, "Enables multimodality (see [[#2. Model and Tokenizer]]).", sglangGroupModeloETokenizer),
		strFlag("revision", "", nil, nil, "Specific model version on HF.", sglangGroupModeloETokenizer, false),
		enumFlag("model-impl", "", nil, []string{"auto", "sglang", "transformers", "mindspore"}, "auto", "Model implementation.", sglangGroupModeloETokenizer),
		strFlag("served-model-name", "", nil, "= model-path", "Name returned by `/v1/models`.", sglangGroupModeloETokenizer, false),
		strFlag("weight-version", "", nil, "default", "Weight version identifier (default `default`).", sglangGroupModeloETokenizer, false),
		strFlag("json-model-override-args", "", nil, nil, "Overrides model configs.", sglangGroupModeloETokenizer, false),
		strFlag("model-checksum", "", nil, nil, "Integrity check for model files.", sglangGroupModeloETokenizer, false),
		enumFlag("load-format", "", nil, []string{"auto", "pt", "safetensors", "npcache", "dummy", "sharded_state", "gguf", "bitsandbytes", "layered", "flash_rl", "remote", "remote_instance", "fastsafetensors", "private"}, "auto", "Weight format.", sglangGroupCarregamentoDePesos),
		strFlag("model-loader-extra-config", "", nil, nil, "Extra loader config.", sglangGroupCarregamentoDePesos, false),
		strFlag("download-dir", "", nil, nil, "HF download directory.", sglangGroupCarregamentoDePesos, false),
		strFlag("custom-weight-loader", "", nil, nil, "Custom weight loader.", sglangGroupCarregamentoDePesos, false),
		boolFlag("weight-loader-disable-mmap", "", nil, false, "Disables mmap when loading safetensors.", sglangGroupCarregamentoDePesos),
		boolFlag("delete-ckpt-after-loading", "", nil, false, "Deletes the checkpoint after loading.", sglangGroupCarregamentoDePesos),
		strFlag("decrypted-config-file", "", nil, nil, "Decrypted config file.", sglangGroupCarregamentoDePesos, false),
		strFlag("decrypted-draft-config-file", "", nil, nil, "Decrypted draft model config.", sglangGroupCarregamentoDePesos, false),
		strFlag("remote-instance-weight-loader-seed-instance-ip", "", nil, nil, "Seed instance IP (remote load).", sglangGroupCarregamentoDePesos, false),
		intFlag("remote-instance-weight-loader-seed-instance-service-port", "", nil, nil, "Seed service port.", sglangGroupCarregamentoDePesos, nil, nil),
		intFlag("remote-instance-weight-loader-send-weights-group-ports", "", nil, nil, "Communication group ports.", sglangGroupCarregamentoDePesos, nil, nil),
		enumFlag("remote-instance-weight-loader-backend", "", nil, []string{"transfer_engine", "nccl"}, nil, "Remote load backend (default `nccl`).", sglangGroupCarregamentoDePesos),
		boolFlag("remote-instance-weight-loader-start-seed-via-transfer-engine", "", nil, false, "Starts the seed via transfer engine.", sglangGroupCarregamentoDePesos),
		enumFlag("dtype", "", nil, []string{"auto", "half", "float16", "bfloat16", "float", "float32"}, "auto", "Weights/activations dtype.", sglangGroupDtypeEQuantizacao),
		enumFlag("quantization", "", nil, []string{"awq", "fp8", "mxfp8", "gptq", "marlin", "gptq_marlin", "awq_marlin", "bitsandbytes", "gguf", "mxfp4", "compressed-tensors"}, "None", "Quantization method.", sglangGroupDtypeEQuantizacao),
		strFlag("quantization-param-path", "", nil, nil, "KV cache scales (for KV fp8).", sglangGroupDtypeEQuantizacao, false),
		enumFlag("kv-cache-dtype", "", nil, []string{"auto", "fp8_e5m2", "fp8_e4m3", "bf16", "bfloat16", "fp4_e2m1"}, "auto", "KV cache dtype.", sglangGroupDtypeEQuantizacao),
		boolFlag("enable-fp32-lm-head", "", nil, false, "LM head (logits) em FP32.", sglangGroupDtypeEQuantizacao),
		enumFlag("modelopt-quant", "", nil, []string{"fp8", "int4_awq", "w4a8_awq", "nvfp4", "nvfp4_awq"}, nil, "ModelOpt quantization config.", sglangGroupDtypeEQuantizacao),
		strFlag("modelopt-checkpoint-restore-path", "", nil, nil, "Restores quantized ModelOpt checkpoint.", sglangGroupDtypeEQuantizacao, false),
		strFlag("modelopt-checkpoint-save-path", "", nil, nil, "Saves quantized ModelOpt checkpoint.", sglangGroupDtypeEQuantizacao, false),
		intFlag("modelopt-export-path", "", nil, nil, "Exports the quantized model in HF format.", sglangGroupDtypeEQuantizacao, nil, nil),
		boolFlag("quantize-and-serve", "", nil, false, "Quantizes with ModelOpt and serves directly (dev/proto).", sglangGroupDtypeEQuantizacao),
		strFlag("rl-quant-profile", "", nil, nil, "Profile FlashRL (exigido por `--load-format flash_rl`).", sglangGroupDtypeEQuantizacao, false),
		strFlag("torchao-config", "", nil, nil, "Optimization via torchao (`int8dq`, `int4wo-<g>`, `fp8wo`, ...).", sglangGroupDtypeEQuantizacao, false),
		floatFlag("mem-fraction-static", "", nil, nil, "Memory fraction for static allocation (weights + KV pool).", sglangGroupMemoriaEKvCache, nil, nil),
		intFlag("max-running-requests", "", nil, nil, "Max running requests.", sglangGroupMemoriaEKvCache, nil, nil),
		intFlag("max-queued-requests", "", nil, nil, "Max queued requests (ignored in disaggregation).", sglangGroupMemoriaEKvCache, nil, nil),
		intFlag("max-total-tokens", "", nil, nil, "Max tokens in memory pool (usually for debug).", sglangGroupMemoriaEKvCache, nil, nil),
		intFlag("page-size", "", nil, nil, "Number of tokens per page.", sglangGroupMemoriaEKvCache, nil, nil),
		intFlag("max-mamba-cache-size", "", nil, nil, "Maximum Mamba cache size (see [[#13. Mamba (SSM)]]).", sglangGroupMemoriaEKvCache, nil, nil),
		floatFlag("swa-full-tokens-ratio", "", nil, nil, "Ratio of SWA-layer KV tokens to full tokens.", sglangGroupMemoriaEKvCache, nil, nil),
		boolFlag("disable-hybrid-swa-memory", "", nil, false, "Disables hybrid memory pool for SWA.", sglangGroupMemoriaEKvCache),
		floatFlag("hybrid-kvcache-ratio", "", nil, nil, "Replaced by `--swa-full-tokens-ratio`.", sglangGroupMemoriaEKvCache, nil, nil),
		boolFlag("disable-radix-cache", "", nil, false, "Disables RadixAttention (prefix caching).", sglangGroupCacheDePrefixoRadixEHierarquico),
		enumFlag("radix-eviction-policy", "", nil, []string{"lru", "lfu"}, "lru", "Radix tree eviction policy.", sglangGroupCacheDePrefixoRadixEHierarquico),
		boolFlag("enable-hierarchical-cache", "", nil, false, "Enables hierarchical cache (HiCache).", sglangGroupCacheDePrefixoRadixEHierarquico),
		floatFlag("hicache-ratio", "", nil, nil, "Host / device pool size.", sglangGroupCacheDePrefixoRadixEHierarquico, nil, nil),
		floatFlag("hicache-size", "", nil, nil, "Host pool size in GB (overrides the ratio).", sglangGroupCacheDePrefixoRadixEHierarquico, nil, nil),
		enumFlag("hicache-write-policy", "", nil, []string{"write_back", "write_through", "write_through_selective"}, nil, "HiCache write policy.", sglangGroupCacheDePrefixoRadixEHierarquico),
		enumFlag("hicache-io-backend", "", nil, []string{"direct", "kernel", "kernel_ascend"}, nil, "Backend de I/O CPU↔GPU.", sglangGroupCacheDePrefixoRadixEHierarquico),
		enumFlag("hicache-mem-layout", "", nil, []string{"layer_first", "page_first"}, nil, "Host memory pool layout.", sglangGroupCacheDePrefixoRadixEHierarquico),
		boolFlag("disable-hicache-numa-detect", "", nil, false, "Does not pin the process to the NUMA node nearest the GPU.", sglangGroupCacheDePrefixoRadixEHierarquico),
		enumFlag("hicache-storage-backend", "", nil, []string{"file", "mooncake", "hf3fs", "nixl", "aibrix", "dynamic", "eic"}, nil, "Hierarchical KV storage backend.", sglangGroupCacheDePrefixoRadixEHierarquico),
		enumFlag("hicache-storage-prefetch-policy", "", nil, []string{"best_effort", "wait_complete", "timeout"}, nil, "When to stop storage prefetch.", sglangGroupCacheDePrefixoRadixEHierarquico),
		strFlag("hicache-storage-backend-extra-config", "", nil, nil, "Extra storage backend config.", sglangGroupCacheDePrefixoRadixEHierarquico, false),
		boolFlag("enable-lmcache", "", nil, false, "Uses LMCache as an alternative hierarchical cache.", sglangGroupCacheDePrefixoRadixEHierarquico),
		intFlag("chunked-prefill-size", "", nil, nil, "Tokens per chunk in chunked prefill; `-1` disables.", sglangGroupPrefillChunkingEScheduler, nil, nil),
		intFlag("prefill-max-requests", "", nil, nil, "Max requests in a prefill batch.", sglangGroupPrefillChunkingEScheduler, nil, nil),
		boolFlag("enable-dynamic-chunking", "", nil, false, "Dynamic chunk size adjustment (pipeline parallel).", sglangGroupPrefillChunkingEScheduler),
		intFlag("max-prefill-tokens", "", nil, nil, "Max tokens in a prefill batch.", sglangGroupPrefillChunkingEScheduler, nil, nil),
		boolFlag("enable-mixed-chunk", "", nil, false, "Mixes prefill and decode in a batch (with chunked prefill).", sglangGroupPrefillChunkingEScheduler),
		boolFlag("disable-chunked-prefix-cache", "", nil, false, "Disables chunked prefix cache (DeepSeek).", sglangGroupPrefillChunkingEScheduler),
		enumFlag("schedule-policy", "", nil, []string{"lpm", "random", "fcfs", "dfs-weight", "lof", "priority", "routing-key"}, nil, "Scheduling policy.", sglangGroupPrefillChunkingEScheduler),
		boolFlag("enable-priority-scheduling", "", nil, false, "Enables priority scheduling.", sglangGroupPrefillChunkingEScheduler),
		boolFlag("abort-on-priority-when-disabled", "", nil, false, "Aborts priority requests when mode is off.", sglangGroupPrefillChunkingEScheduler),
		boolFlag("schedule-low-priority-values-first", "", nil, false, "Prioridade menor = agendada primeiro.", sglangGroupPrefillChunkingEScheduler),
		floatFlag("priority-scheduling-preemption-threshold", "", nil, nil, "Minimum priority difference for preemption.", sglangGroupPrefillChunkingEScheduler, nil, nil),
		strFlag("schedule-conservativeness", "", nil, nil, "How conservative the scheduler is (higher = more).", sglangGroupPrefillChunkingEScheduler, false),
		intFlag("num-continuous-decode-steps", "", nil, 1, "Continuous decode steps per schedule (default `1`).", sglangGroupPrefillChunkingEScheduler, nil, nil),
		boolFlag("disable-overlap-schedule", "", nil, false, "Disables the overlap scheduler (CPU x GPU worker).", sglangGroupPrefillChunkingEScheduler),
		boolFlag("enable-prefill-delayer", "", nil, false, "Delays prefill in DP attention to reduce idleness.", sglangGroupPrefillChunkingEScheduler),
		intFlag("prefill-delayer-max-delay-passes", "", nil, nil, "Max forward passes to delay prefill.", sglangGroupPrefillChunkingEScheduler, nil, nil),
		strFlag("prefill-delayer-token-usage-low-watermark", "", nil, nil, "Delayer token usage watermark.", sglangGroupPrefillChunkingEScheduler, false),
		intFlag("stream-interval", "", nil, nil, "Intervalo/buffer de streaming (em tokens).", sglangGroupStreamingSamplingEGramatica, nil, nil),
		boolFlag("stream-output", "", nil, false, "Output in disjoint segments.", sglangGroupStreamingSamplingEGramatica),
		intFlag("random-seed", "", nil, nil, "RNG seed.", sglangGroupStreamingSamplingEGramatica, nil, nil),
		enumFlag("sampling-defaults", "", nil, []string{"openai", "model"}, "model", "Sampling defaults source (default `model`).", sglangGroupStreamingSamplingEGramatica),
		strFlag("preferred-sampling-params", "", nil, nil, "Sampling retornado em `/get_model_info`.", sglangGroupStreamingSamplingEGramatica, false),
		enumFlag("grammar-backend", "", nil, []string{"xgrammar", "outlines", "llguidance", "none"}, nil, "Grammar-guided decoding backend.", sglangGroupStreamingSamplingEGramatica),
		strFlag("constrained-json-whitespace-pattern", "", nil, nil, "Allowed whitespaces in constrained JSON (outlines/llguidance).", sglangGroupStreamingSamplingEGramatica, false),
		boolFlag("constrained-json-disable-any-whitespace", "", nil, false, "Compact representation in constrained JSON (xgrammar/llguidance).", sglangGroupStreamingSamplingEGramatica),
		enumFlag("device", "", nil, []string{"cuda", "xpu", "hpu", "npu", "cpu"}, nil, "Device (auto-detection by default).", sglangGroupParalelismoEExecucaoDistribuida),
		intFlag("tensor-parallel-size", "", nil, 1, "Tensor parallelism size.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		intFlag("tp-size", "", nil, 1, "Tensor parallelism (default `1`).", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		intFlag("pipeline-parallel-size", "", nil, 1, "Pipeline parallelism size.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		intFlag("pp-size", "", nil, 1, "Pipeline parallelism size.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		intFlag("data-parallel-size", "", nil, 1, "Data parallelism size.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		intFlag("dp-size", "", nil, 1, "Data parallelism size.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		intFlag("attention-context-parallel-size", "", nil, 1, "Context parallelism in attention.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		intFlag("attn-cp-size", "", nil, 1, "Context parallelism in attention.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		intFlag("moe-data-parallel-size", "", nil, nil, "DP in MoE layers.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		intFlag("moe-dp-size", "", nil, nil, "DP in MoE layers.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		intFlag("pp-max-micro-batch-size", "", nil, nil, "Max micro-batch in the pipeline.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		intFlag("pp-async-batch-depth", "", nil, nil, "PP asynchronous batch depth.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		enumFlag("load-balance-method", "", nil, []string{"auto", "round_robin", "follow_bootstrap_room", "total_requests", "total_tokens"}, nil, "DP LB strategy.", sglangGroupParalelismoEExecucaoDistribuida),
		intFlag("dist-init-addr", "", nil, nil, "Distributed backend init address.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		intFlag("nccl-init-addr", "", nil, nil, "Distributed backend init address.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		intFlag("nnodes", "", nil, 1, "Number of nodes.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		intFlag("node-rank", "", nil, 0, "Node rank.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		boolFlag("enable-dp-attention", "", nil, false, "DP in attention + TP in FFN (dp size = tp size).", sglangGroupParalelismoEExecucaoDistribuida),
		boolFlag("enable-dp-lm-head", "", nil, false, "Vocab parallel in attention TP group (under DP attention).", sglangGroupParalelismoEExecucaoDistribuida),
		boolFlag("enable-attn-tp-input-scattered", "", nil, false, "Sharded attention input (TP only), reduces qkv latent load.", sglangGroupParalelismoEExecucaoDistribuida),
		intFlag("moe-dense-tp-size", "", nil, nil, "TP for dense MoE MLP layers.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		intFlag("expert-parallel-size", "", nil, 1, "Expert parallelism size.", sglangGroupMoeEExpertParallelism, nil, nil),
		intFlag("ep-size", "", nil, 1, "Expert parallelism size.", sglangGroupMoeEExpertParallelism, nil, nil),
		intFlag("ep", "", nil, 1, "Expert parallelism size.", sglangGroupMoeEExpertParallelism, nil, nil),
		enumFlag("moe-a2a-backend", "", nil, []string{"none", "deepep", "mooncake", "mori", "ascend_fuseep", "flashinfer"}, "none", "MoE A2A communication backend.", sglangGroupMoeEExpertParallelism),
		enumFlag("moe-runner-backend", "", nil, []string{"auto", "deep_gemm", "triton", "triton_kernel", "cutlass"}, "auto", "Expert computation backend.", sglangGroupMoeEExpertParallelism),
		enumFlag("flashinfer-mxfp4-moe-precision", "", nil, []string{"default", "bf16"}, nil, "FlashInfer MoE mxfp4 precision.", sglangGroupMoeEExpertParallelism),
		boolFlag("enable-flashinfer-allreduce-fusion", "", nil, false, "AllReduce + Residual RMSNorm fusion (FlashInfer).", sglangGroupMoeEExpertParallelism),
		enumFlag("deepep-mode", "", nil, []string{"normal", "low_latency", "auto"}, "auto", "DeepEP MoE mode (default `auto`).", sglangGroupMoeEExpertParallelism),
		intFlag("ep-num-redundant-experts", "", nil, nil, "Redundant experts in EP.", sglangGroupMoeEExpertParallelism, nil, nil),
		strFlag("ep-dispatch-algorithm", "", nil, nil, "Algoritmo de escolha de ranks p/ experts redundantes.", sglangGroupMoeEExpertParallelism, false),
		strFlag("init-expert-location", "", nil, nil, "Initial EP expert location.", sglangGroupMoeEExpertParallelism, false),
		boolFlag("enable-eplb", "", nil, false, "Enables the EPLB algorithm (expert load balancing).", sglangGroupMoeEExpertParallelism),
		strFlag("eplb-algorithm", "", nil, nil, "Algoritmo EPLB.", sglangGroupMoeEExpertParallelism, false),
		intFlag("eplb-rebalance-num-iterations", "", nil, nil, "Iterations before triggering automatic rebalancing.", sglangGroupMoeEExpertParallelism, nil, nil),
		intFlag("eplb-rebalance-layers-per-chunk", "", nil, nil, "Layers rebalanced per forward pass.", sglangGroupMoeEExpertParallelism, nil, nil),
		floatFlag("eplb-min-rebalancing-utilization-threshold", "", nil, nil, "Minimum GPU utilization for rebalancing.", sglangGroupMoeEExpertParallelism, nil, nil),
		strFlag("expert-distribution-recorder-mode", "", nil, nil, "Expert distribution recorder mode.", sglangGroupMoeEExpertParallelism, false),
		intFlag("expert-distribution-recorder-buffer-size", "", nil, nil, "Recorder ring buffer (`-1` = infinite).", sglangGroupMoeEExpertParallelism, nil, nil),
		boolFlag("enable-expert-distribution-metrics", "", nil, false, "Expert balancing metrics.", sglangGroupMoeEExpertParallelism),
		strFlag("deepep-config", "", nil, nil, "DeepEP config tuned for the cluster.", sglangGroupMoeEExpertParallelism, false),
		enumFlag("elastic-ep-backend", "", nil, []string{"none", "mooncake"}, nil, "Communication backend for elastic EP.", sglangGroupMoeEExpertParallelism),
		strFlag("mooncake-ib-device", "", nil, nil, "Mooncake InfiniBand devices.", sglangGroupMoeEExpertParallelism, false),
		boolFlag("disable-shared-experts-fusion", "", nil, false, "Disables shared experts fusion (DeepSeek v3/r1).", sglangGroupMoeEExpertParallelism),
		enumFlag("attention-backend", "", nil, []string{"triton", "torch_native", "flex_attention", "nsa", "cutlass_mla", "fa3", "fa4", "flashinfer", "flashmla", "trtllm_mla", "trtllm_mha", "dual_chunk_flash_attn", "aiter", "wave", "intel_amx", "ascend", "intel_xpu"}, nil, "Attention backend (`fa`, `torch_sdpa`, `sage_attn`, ...).", sglangGroupBackendsDeAtencaoEGemm),
		strFlag("prefill-attention-backend", "", nil, "= attention-backend", "Prefill-only kernels (take priority over the general setting).", sglangGroupBackendsDeAtencaoEGemm, false),
		strFlag("decode-attention-backend", "", nil, "= attention-backend", "Decode-only kernels (take priority over the general setting).", sglangGroupBackendsDeAtencaoEGemm, false),
		enumFlag("sampling-backend", "", nil, []string{"pytorch", "flashinfer", "ascend"}, nil, "Sampling kernels.", sglangGroupBackendsDeAtencaoEGemm),
		enumFlag("mm-attention-backend", "", nil, []string{"sdpa", "fa3", "fa4", "triton_attn", "ascend_attn", "aiter_attn"}, nil, "Multimodal attention backend.", sglangGroupBackendsDeAtencaoEGemm),
		enumFlag("fp8-gemm-backend", "", nil, []string{"auto", "deep_gemm", "flashinfer_trtllm", "flashinfer_deepgemm", "cutlass", "triton", "aiter"}, "auto", "Runner de GEMM FP8 blockwise.", sglangGroupBackendsDeAtencaoEGemm),
		enumFlag("fp4-gemm-backend", "", nil, []string{"auto", "flashinfer_cudnn", "flashinfer_cutlass", "flashinfer_trtllm"}, "flashinfer_cutlass", "Runner de GEMM NVFP4 (default `flashinfer_cutlass`).", sglangGroupBackendsDeAtencaoEGemm),
		boolFlag("disable-flashinfer-autotune", "", nil, false, "Disables FlashInfer autotuning.", sglangGroupBackendsDeAtencaoEGemm),
		boolFlag("flashinfer-mla-disable-ragged", "", nil, false, "Does not use ragged prefill wrapper in FlashInfer MLA.", sglangGroupBackendsDeAtencaoEGemm),
		boolFlag("enable-fused-qk-norm-rope", "", nil, false, "Fuses QK normalization + RoPE.", sglangGroupBackendsDeAtencaoEGemm),
		boolFlag("triton-attention-reduce-in-fp32", "", nil, false, "Reduces attention intermediate results in FP32 (Triton).", sglangGroupBackendsDeAtencaoEGemm),
		intFlag("triton-attention-num-kv-splits", "", nil, 8, "Number of KV splits in flash decoding Triton (default `8`).", sglangGroupBackendsDeAtencaoEGemm, nil, nil),
		intFlag("triton-attention-split-tile-size", "", nil, nil, "KV split tile size (Triton).", sglangGroupBackendsDeAtencaoEGemm, nil, nil),
		enumFlag("nsa-prefill-backend", "", nil, []string{"flashmla_sparse", "flashmla_kv", "flashmla_auto", "fa3", "tilelang", "aiter", "trtllm"}, nil, "Backend NSA de prefill.", sglangGroupAtencaoEsparsaNsaEDoubleSparsity),
		strFlag("nsa-decode-backend", "", nil, nil, "Backend NSA de decode.", sglangGroupAtencaoEsparsaNsaEDoubleSparsity, false),
		boolFlag("enable-nsa-prefill-context-parallel", "", nil, false, "Context parallel in long prefill (DeepSeek v3.2).", sglangGroupAtencaoEsparsaNsaEDoubleSparsity),
		enumFlag("nsa-prefill-cp-mode", "", nil, []string{"in-seq-split", "round-robin-split"}, nil, "Token split mode in NSA prefill.", sglangGroupAtencaoEsparsaNsaEDoubleSparsity),
		boolFlag("enable-double-sparsity", "", nil, false, "Enables double sparsity attention.", sglangGroupAtencaoEsparsaNsaEDoubleSparsity),
		strFlag("ds-channel-config-path", "", nil, nil, "Double sparsity channel config.", sglangGroupAtencaoEsparsaNsaEDoubleSparsity, false),
		intFlag("ds-heavy-channel-num", "", nil, nil, "Nº de \"heavy channels\".", sglangGroupAtencaoEsparsaNsaEDoubleSparsity, nil, nil),
		intFlag("ds-heavy-token-num", "", nil, nil, "Nº de \"heavy tokens\".", sglangGroupAtencaoEsparsaNsaEDoubleSparsity, nil, nil),
		strFlag("ds-heavy-channel-type", "", nil, nil, "Heavy channel type.", sglangGroupAtencaoEsparsaNsaEDoubleSparsity, false),
		floatFlag("ds-sparse-decode-threshold", "", nil, nil, "Minimum decode length to activate the sparse kernel.", sglangGroupAtencaoEsparsaNsaEDoubleSparsity, nil, nil),
		strFlag("hierarchical-sparse-attention-extra-config", "", nil, nil, "Hierarchical sparse attention config (e.g. `quest`).", sglangGroupAtencaoEsparsaNsaEDoubleSparsity, false),
		enumFlag("mamba-ssm-dtype", "", nil, []string{"float32", "bfloat16", "float16"}, nil, "SSM state dtype (default: from config).", sglangGroupMambaSsm),
		floatFlag("mamba-full-memory-ratio", "", nil, nil, "Mamba state memory / full KV cache.", sglangGroupMambaSsm, nil, nil),
		enumFlag("mamba-scheduler-strategy", "", nil, []string{"auto", "no_buffer", "extra_buffer"}, nil, "Radix cache strategy for Mamba.", sglangGroupMambaSsm),
		intFlag("mamba-track-interval", "", nil, nil, "Mamba state tracking interval during decode.", sglangGroupMambaSsm, nil, nil),
		enumFlag("mamba-backend", "", nil, []string{"triton", "flashinfer"}, "triton", "Kernel for Mamba SSM operations (default `triton`).", sglangGroupMambaSsm),
		boolFlag("enable-lora", "", nil, false, "Enables LoRA (auto-enabled if `--lora-paths` is used).", sglangGroupLora),
		strFlag("lora-paths", "", nil, nil, "Adapters a carregar (`<PATH>`, `<NOME>=<PATH>` ou JSON).", sglangGroupLora, false),
		intFlag("max-lora-rank", "", nil, nil, "Maximum rank (inferred from adapters if omitted).", sglangGroupLora, nil, nil),
		strFlag("lora-target-modules", "", nil, nil, "Modules where LoRA is applied.", sglangGroupLora, false),
		intFlag("max-loras-per-batch", "", nil, nil, "Max adapters in a running batch.", sglangGroupLora, nil, nil),
		intFlag("max-loaded-loras", "", nil, nil, "Max adapters in RAM (>= `--max-loras-per-batch`).", sglangGroupLora, nil, nil),
		enumFlag("lora-eviction-policy", "", nil, []string{"lru", "fifo"}, "lru", "LoRA eviction policy (default `lru`).", sglangGroupLora),
		enumFlag("lora-backend", "", nil, []string{"triton", "csgmv", "ascend", "torch_native"}, nil, "Backend de kernels multi-LoRA.", sglangGroupLora),
		strFlag("max-lora-chunk-size", "", nil, nil, "Maximum chunk for the `csgmv` backend.", sglangGroupLora, false),
		boolFlag("enable-lora-overlap-loading", "", nil, false, "Asynchronous LoRA loading (overlap H2D x compute).", sglangGroupLora),
		enumFlag("speculative-algorithm", "", nil, []string{"EAGLE", "EAGLE3", "NEXTN", "STANDALONE", "NGRAM"}, nil, "Algoritmo de speculative decoding.", sglangGroupSpeculativeDecoding),
		strFlag("speculative-draft-model-path", "", nil, nil, "Draft model.", sglangGroupSpeculativeDecoding, false),
		strFlag("speculative-draft-model", "", nil, nil, "Draft model.", sglangGroupSpeculativeDecoding, false),
		strFlag("speculative-draft-model-revision", "", nil, nil, "Draft version.", sglangGroupSpeculativeDecoding, false),
		strFlag("speculative-draft-load-format", "", nil, nil, "Draft weight format.", sglangGroupSpeculativeDecoding, false),
		strFlag("speculative-draft-model-quantization", "", nil, nil, "Draft quantization.", sglangGroupSpeculativeDecoding, false),
		intFlag("speculative-num-steps", "", nil, nil, "Sampled draft steps.", sglangGroupSpeculativeDecoding, nil, nil),
		intFlag("speculative-eagle-topk", "", nil, nil, "Draft tokens sampled per step (eagle2).", sglangGroupSpeculativeDecoding, nil, nil),
		intFlag("speculative-num-draft-tokens", "", nil, nil, "Draft tokens sampled.", sglangGroupSpeculativeDecoding, nil, nil),
		strFlag("speculative-accept-threshold-single", "", nil, nil, "Acceptance threshold for a draft token.", sglangGroupSpeculativeDecoding, false),
		strFlag("speculative-accept-threshold-acc", "", nil, nil, "Raises acceptance probability to `min(1, p/threshold)`.", sglangGroupSpeculativeDecoding, false),
		strFlag("speculative-token-map", "", nil, nil, "Reduced draft vocab.", sglangGroupSpeculativeDecoding, false),
		enumFlag("speculative-attention-mode", "", nil, []string{"prefill", "decode"}, "prefill", "Speculative attention backend (default `prefill`).", sglangGroupSpeculativeDecoding),
		strFlag("speculative-draft-attention-backend", "", nil, nil, "Attention backend for the draft step.", sglangGroupSpeculativeDecoding, false),
		strFlag("speculative-moe-runner-backend", "", nil, nil, "MoE runner in speculative.", sglangGroupSpeculativeDecoding, false),
		strFlag("speculative-moe-a2a-backend", "", nil, nil, "A2A MoE in speculative.", sglangGroupSpeculativeDecoding, false),
		boolFlag("enable-multi-layer-eagle", "", nil, false, "Multi-layer Eagle.", sglangGroupSpeculativeDecoding),
		enumFlag("speculative-ngram-match-type", "", nil, []string{"BFS", "PROB"}, nil, "Cache tree match type.", sglangGroupSpeculativeDecoding),
		intFlag("speculative-ngram-branch-length", "", nil, nil, "Branch length (n-gram).", sglangGroupSpeculativeDecoding, nil, nil),
		intFlag("speculative-ngram-capacity", "", nil, nil, "Cache capacity (n-gram).", sglangGroupSpeculativeDecoding, nil, nil),
		boolFlag("disable-cuda-graph", "", nil, false, "Disables CUDA graph.", sglangGroupCudaGraphETorchCompile),
		boolFlag("disable-cuda-graph-padding", "", nil, false, "Disables CUDA graph when padding is present.", sglangGroupCudaGraphETorchCompile),
		intFlag("cuda-graph-max-bs", "", nil, nil, "Maximum batch size captured in CUDA graph.", sglangGroupCudaGraphETorchCompile, nil, nil),
		strFlag("cuda-graph-bs", "", nil, nil, "Explicit list of batch sizes to capture.", sglangGroupCudaGraphETorchCompile, false),
		boolFlag("enable-profile-cuda-graph", "", nil, false, "CUDA graph capture profiling.", sglangGroupCudaGraphETorchCompile),
		boolFlag("enable-cudagraph-gc", "", nil, false, "GC during capture (default: frozen GC to speed up).", sglangGroupCudaGraphETorchCompile),
		boolFlag("enable-torch-compile", "", nil, false, "torch.compile on DiT (may cause precision drift).", sglangGroupCudaGraphETorchCompile),
		boolFlag("enable-torch-compile-debug-mode", "", nil, false, "torch.compile debug mode.", sglangGroupCudaGraphETorchCompile),
		intFlag("torch-compile-max-bs", "", nil, nil, "Maximum batch size with torch.compile.", sglangGroupCudaGraphETorchCompile, nil, nil),
		boolFlag("enable-piecewise-cuda-graph", "", nil, false, "Piecewise CUDA graph (extend/prefill only).", sglangGroupCudaGraphETorchCompile),
		strFlag("piecewise-cuda-graph-tokens", "", nil, nil, "Token lengths for piecewise capture.", sglangGroupCudaGraphETorchCompile, false),
		intFlag("piecewise-cuda-graph-max-tokens", "", nil, nil, "Max tokens in piecewise CUDA graph.", sglangGroupCudaGraphETorchCompile, nil, nil),
		enumFlag("piecewise-cuda-graph-compiler", "", nil, []string{"eager", "inductor"}, nil, "Piecewise CUDA graph compiler.", sglangGroupCudaGraphETorchCompile),
		boolFlag("disable-custom-all-reduce", "", nil, false, "Disables custom all-reduce (uses NCCL).", sglangGroupComunicacaoEAllReduce),
		boolFlag("enable-mscclpp", "", nil, false, "Uses mscclpp for small messages in all-reduce.", sglangGroupComunicacaoEAllReduce),
		boolFlag("enable-torch-symm-mem", "", nil, false, "Uses torch symm mem in all-reduce (SM90+).", sglangGroupComunicacaoEAllReduce),
		boolFlag("enable-symm-mem", "", nil, false, "NCCL symmetric memory for fast collectives.", sglangGroupComunicacaoEAllReduce),
		boolFlag("enable-nccl-nvls", "", nil, false, "NCCL NVLS for heavy prefills (when available).", sglangGroupComunicacaoEAllReduce),
		boolFlag("enable-p2p-check", "", nil, false, "Checks P2P access between GPUs.", sglangGroupComunicacaoEAllReduce),
		boolFlag("disable-flashinfer-cutlass-moe-fp4-allgather", "", nil, false, "Does not quantize before all-gather (flashinfer cutlass MoE).", sglangGroupComunicacaoEAllReduce),
		floatFlag("cpu-offload-gb", "", nil, 0, "RAM reserved for CPU weight offload.", sglangGroupOffloadDePesosEMemorySaver, nil, nil),
		intFlag("offload-group-size", "", nil, nil, "Layers per offload group.", sglangGroupOffloadDePesosEMemorySaver, nil, nil),
		intFlag("offload-num-in-group", "", nil, nil, "Layers offloaded per group.", sglangGroupOffloadDePesosEMemorySaver, nil, nil),
		intFlag("offload-prefetch-step", "", nil, nil, "Prefetch steps in offload.", sglangGroupOffloadDePesosEMemorySaver, nil, nil),
		strFlag("offload-mode", "", nil, nil, "Offload mode.", sglangGroupOffloadDePesosEMemorySaver, false),
		boolFlag("enable-memory-saver", "", nil, false, "Allows releasing/resuming memory occupation.", sglangGroupOffloadDePesosEMemorySaver),
		boolFlag("enable-weights-cpu-backup", "", nil, false, "Weight backup in RAM (release/resume).", sglangGroupOffloadDePesosEMemorySaver),
		boolFlag("enable-draft-weights-cpu-backup", "", nil, false, "Draft weight backup in RAM.", sglangGroupOffloadDePesosEMemorySaver),
		strFlag("kt-weight-path", "", nil, nil, "[ktransformers] Quantized expert weights (AMX).", sglangGroupOffloadDePesosEMemorySaver, false),
		strFlag("kt-method", "", nil, nil, "[ktransformers] Quantization format for CPU.", sglangGroupOffloadDePesosEMemorySaver, false),
		intFlag("kt-cpuinfer", "", nil, nil, "[ktransformers] CPUInfer threads.", sglangGroupOffloadDePesosEMemorySaver, nil, nil),
		intFlag("kt-threadpool-count", "", nil, nil, "[ktransformers] Thread pools (1 per NUMA).", sglangGroupOffloadDePesosEMemorySaver, nil, nil),
		intFlag("kt-num-gpu-experts", "", nil, nil, "[ktransformers] Number of experts on GPU.", sglangGroupOffloadDePesosEMemorySaver, nil, nil),
		intFlag("kt-max-deferred-experts-per-token", "", nil, nil, "[ktransformers] Experts deferred to CPU per token.", sglangGroupOffloadDePesosEMemorySaver, nil, nil),
		strFlag("limit-mm-data-per-request", "", nil, nil, "Limit of MM inputs per request (e.g. `{\"image\":1}`).", sglangGroupMultimodalEEncoder, false),
		intFlag("mm-max-concurrent-calls", "", nil, nil, "Concurrent calls in async MM processing.", sglangGroupMultimodalEEncoder, nil, nil),
		intFlag("mm-per-request-timeout", "", nil, nil, "Timeout per multimodal request.", sglangGroupMultimodalEEncoder, nil, nil),
		boolFlag("enable-broadcast-mm-inputs-process", "", nil, false, "Broadcast of the mm-inputs process in the scheduler.", sglangGroupMultimodalEEncoder),
		strFlag("mm-process-config", "", nil, nil, "MM preprocessing config (`image`/`video`/`audio`).", sglangGroupMultimodalEEncoder, false),
		boolFlag("mm-enable-dp-encoder", "", nil, false, "DP in MM encoder (dp size = tp size).", sglangGroupMultimodalEEncoder),
		boolFlag("disable-fast-image-processor", "", nil, false, "Uses the base image processor (not the fast one).", sglangGroupMultimodalEEncoder),
		boolFlag("keep-mm-feature-on-device", "", nil, false, "Keeps MM features on device (avoids D2H copy).", sglangGroupMultimodalEEncoder),
		boolFlag("enable-prefix-mm-cache", "", nil, false, "Multimodal prefix cache (mm-only).", sglangGroupMultimodalEEncoder),
		boolFlag("encoder-only", "", nil, false, "Starts an encoder-only server (MLLM).", sglangGroupMultimodalEEncoder),
		boolFlag("language-only", "", nil, false, "Loads only the LM (VLM).", sglangGroupMultimodalEEncoder),
		enumFlag("encoder-transfer-backend", "", nil, []string{"zmq_to_scheduler", "zmq_to_tokenizer", "mooncake"}, nil, "Encoder transfer backend.", sglangGroupMultimodalEEncoder),
		strFlag("encoder-urls", "", nil, nil, "URLs de servidores de encoder.", sglangGroupMultimodalEEncoder, false),
		strFlag("api-key", "", nil, nil, "Server API key (OpenAI-compatible).", sglangGroupApiOpenaiEParsers, false),
		strFlag("admin-api-key", "", nil, nil, "Key for sensitive admin endpoints.", sglangGroupApiOpenaiEParsers, false),
		strFlag("chat-template", "", nil, nil, "Chat template (OpenAI-compatible).", sglangGroupApiOpenaiEParsers, false),
		strFlag("hf-chat-template-name", "", nil, nil, "Which named HF template to use (`tool_use`, `rag`,…).", sglangGroupApiOpenaiEParsers, false),
		strFlag("completion-template", "", nil, nil, "Template de completion (code completion).", sglangGroupApiOpenaiEParsers, false),
		strFlag("file-storage-path", "", nil, nil, "Backend file storage path.", sglangGroupApiOpenaiEParsers, false),
		boolFlag("enable-cache-report", "", nil, false, "Reports cached tokens in `usage.prompt_tokens_details`.", sglangGroupApiOpenaiEParsers),
		enumFlag("reasoning-parser", "", nil, []string{"deepseek-r1", "deepseek-v3", "glm45", "gpt-oss", "kimi", "qwen3"}, nil, "Reasoning model parser.", sglangGroupApiOpenaiEParsers),
		enumFlag("tool-call-parser", "", nil, []string{"deepseekv3", "glm", "gpt-oss", "kimi_k2", "llama3", "mistral", "qwen", "hermes"}, nil, "Parser de tool calls.", sglangGroupApiOpenaiEParsers),
		strFlag("tool-server", "", nil, nil, "Tool server(s).", sglangGroupApiOpenaiEParsers, false),
		strFlag("multi-item-scoring-delimiter", "", nil, nil, "Delimiter for multi-item scoring.", sglangGroupApiOpenaiEParsers, false),
		boolFlag("allow-auto-truncate", "", nil, false, "Automatically truncates long requests (instead of error).", sglangGroupApiOpenaiEParsers),
		boolFlag("enable-custom-logit-processor", "", nil, false, "Allows custom logit processors (off for security).", sglangGroupApiOpenaiEParsers),
		boolFlag("enable-return-hidden-states", "", nil, false, "Returns hidden states in responses.", sglangGroupApiOpenaiEParsers),
		boolFlag("enable-return-routed-experts", "", nil, false, "Returns routed experts by layer.", sglangGroupApiOpenaiEParsers),
		strFlag("log-level", "", nil, nil, "Log level for all loggers.", sglangGroupLoggingMetricasETracing, false),
		strFlag("log-level-http", "", nil, nil, "HTTP server log level (inherits `--log-level`).", sglangGroupLoggingMetricasETracing, false),
		boolFlag("log-requests", "", nil, false, "Logs request metadata/inputs/outputs.", sglangGroupLoggingMetricasETracing),
		strFlag("log-requests-level", "", nil, "0", "Request log verbosity.", sglangGroupLoggingMetricasETracing, false),
		enumFlag("log-requests-format", "", nil, []string{"text", "json"}, nil, "Request log format.", sglangGroupLoggingMetricasETracing),
		strFlag("log-requests-target", "", nil, nil, "Request log destination(s).", sglangGroupLoggingMetricasETracing, false),
		strFlag("uvicorn-access-log-exclude-prefixes", "", nil, nil, "Excludes access logs by route prefix (e.g. `/metrics`).", sglangGroupLoggingMetricasETracing, false),
		strFlag("crash-dump-folder", "", nil, nil, "Dumps requests from the last 5 min before a crash.", sglangGroupLoggingMetricasETracing, false),
		boolFlag("show-time-cost", "", nil, false, "Mostra custo de tempo de marcas customizadas.", sglangGroupLoggingMetricasETracing),
		boolFlag("enable-metrics", "", nil, false, "Enables Prometheus metrics.", sglangGroupLoggingMetricasETracing),
		boolFlag("enable-metrics-for-all-schedulers", "", nil, false, "Metrics for all TP ranks (not only TP 0).", sglangGroupLoggingMetricasETracing),
		strFlag("tokenizer-metrics-custom-labels-header", "", nil, nil, "HTTP header for custom tokenizer metric labels.", sglangGroupLoggingMetricasETracing, false),
		strFlag("tokenizer-metrics-allowed-custom-labels", "", nil, nil, "Labels custom permitidos.", sglangGroupLoggingMetricasETracing, false),
		strFlag("extra-metric-labels", "", nil, nil, "Custom labels for metrics.", sglangGroupLoggingMetricasETracing, false),
		strFlag("bucket-time-to-first-token", "", nil, nil, "Buckets de TTFT.", sglangGroupLoggingMetricasETracing, false),
		strFlag("bucket-inter-token-latency", "", nil, nil, "Buckets de inter-token latency.", sglangGroupLoggingMetricasETracing, false),
		strFlag("bucket-e2e-request-latency", "", nil, nil, "E2E latency buckets.", sglangGroupLoggingMetricasETracing, false),
		boolFlag("collect-tokens-histogram", "", nil, false, "Prompt/generation token histogram.", sglangGroupLoggingMetricasETracing),
		strFlag("prompt-tokens-buckets", "", nil, nil, "Buckets (`default`/`tse`/`custom`).", sglangGroupLoggingMetricasETracing, false),
		strFlag("generation-tokens-buckets", "", nil, nil, "Buckets (`default`/`tse`/`custom`).", sglangGroupLoggingMetricasETracing, false),
		intFlag("gc-warning-threshold-secs", "", nil, nil, "Long GC warning (`0` disables).", sglangGroupLoggingMetricasETracing, nil, nil),
		intFlag("decode-log-interval", "", nil, nil, "Decode batch log interval.", sglangGroupLoggingMetricasETracing, nil, nil),
		boolFlag("enable-request-time-stats-logging", "", nil, false, "Timing stats per request.", sglangGroupLoggingMetricasETracing),
		strFlag("kv-events-config", "", nil, nil, "KV event publishing (NVIDIA Dynamo).", sglangGroupLoggingMetricasETracing, false),
		boolFlag("enable-trace", "", nil, false, "Enables OpenTelemetry tracing.", sglangGroupLoggingMetricasETracing),
		intFlag("otlp-traces-endpoint", "", nil, nil, "OpenTelemetry collector endpoint.", sglangGroupLoggingMetricasETracing, nil, nil),
		boolFlag("export-metrics-to-file", "", nil, false, "Exports per-request metrics to a file.", sglangGroupLoggingMetricasETracing),
		strFlag("export-metrics-to-file-dir", "", nil, nil, "Metrics files directory.", sglangGroupLoggingMetricasETracing, false),
		enumFlag("disaggregation-mode", "", nil, []string{"null", "prefill", "decode"}, "null", "Server role (PD disaggregation).", sglangGroupPdDisaggregation),
		enumFlag("disaggregation-transfer-backend", "", nil, []string{"mooncake", "nixl", "ascend", "fake", "mori"}, "mooncake", "Transfer backend (default `mooncake`).", sglangGroupPdDisaggregation),
		intFlag("disaggregation-bootstrap-port", "", nil, 8998, "Bootstrap port on prefill (default `8998`).", sglangGroupPdDisaggregation, nil, nil),
		intFlag("disaggregation-decode-tp", "", nil, nil, "Decode TP (set in prefill).", sglangGroupPdDisaggregation, nil, nil),
		intFlag("disaggregation-decode-dp", "", nil, nil, "Decode DP (set in prefill).", sglangGroupPdDisaggregation, nil, nil),
		intFlag("disaggregation-prefill-pp", "", nil, 1, "Prefill PP (set in decode; default `1`).", sglangGroupPdDisaggregation, nil, nil),
		strFlag("disaggregation-ib-device", "", nil, nil, "InfiniBand devices for transfer.", sglangGroupPdDisaggregation, false),
		boolFlag("disaggregation-decode-enable-offload-kvcache", "", nil, false, "Async KV offload in decode.", sglangGroupPdDisaggregation),
		intFlag("num-reserved-decode-tokens", "", nil, nil, "Decode tokens with reserved memory per request.", sglangGroupPdDisaggregation, nil, nil),
		intFlag("disaggregation-decode-polling-interval", "", nil, nil, "Polling interval in decode server.", sglangGroupPdDisaggregation, nil, nil),
		boolFlag("enable-deterministic-inference", "", nil, false, "Deterministic inference (batch-invariant ops).", sglangGroupDebugDeterminismoEDiversos),
		boolFlag("enable-nan-detection", "", nil, false, "NaN detection (debug).", sglangGroupDebugDeterminismoEDiversos),
		strFlag("debug-tensor-dump-output-folder", "", nil, nil, "Folder for tensor dump.", sglangGroupDebugDeterminismoEDiversos, false),
		strFlag("debug-tensor-dump-layers", "", nil, nil, "Layers to dump (all if omitted).", sglangGroupDebugDeterminismoEDiversos, false),
		strFlag("debug-tensor-dump-input-file", "", nil, nil, "Input file for dump.", sglangGroupDebugDeterminismoEDiversos, false),
		strFlag("debug-tensor-dump-inject", "", nil, nil, "Injects outputs as input to each layer.", sglangGroupDebugDeterminismoEDiversos, false),
		boolFlag("enable-tokenizer-batch-encode", "", nil, false, "Batch tokenization (do not use with images/ids).", sglangGroupDebugDeterminismoEDiversos),
		boolFlag("disable-tokenizer-batch-decode", "", nil, false, "Disables batch decode.", sglangGroupDebugDeterminismoEDiversos),
		boolFlag("enable-dynamic-batch-tokenizer", "", nil, false, "Async dynamic tokenizer (multiple concurrent requests).", sglangGroupDebugDeterminismoEDiversos),
		intFlag("dynamic-batch-tokenizer-batch-size", "", nil, nil, "Maximum dynamic tokenizer batch.", sglangGroupDebugDeterminismoEDiversos, nil, nil),
		intFlag("dynamic-batch-tokenizer-batch-timeout", "", nil, nil, "Tokenization batching timeout.", sglangGroupDebugDeterminismoEDiversos, nil, nil),
		boolFlag("disable-outlines-disk-cache", "", nil, false, "Disables the outlines disk cache.", sglangGroupDebugDeterminismoEDiversos),
		boolFlag("enable-precise-embedding-interpolation", "", nil, false, "Embedding interpolation with corner alignment (slower).", sglangGroupDebugDeterminismoEDiversos),
		strFlag("rl-on-policy-target", "", nil, nil, "Training system to match for true on-policy.", sglangGroupDebugDeterminismoEDiversos, false),
		boolFlag("enable-pdmux", "", nil, false, "PD-Multiplexing (greenctx stream).", sglangGroupDebugDeterminismoEDiversos),
		strFlag("pdmux-config-path", "", nil, nil, "PD-Multiplexing config.", sglangGroupDebugDeterminismoEDiversos, false),
		intFlag("sm-group-num", "", nil, nil, "Number of SM partition groups.", sglangGroupDebugDeterminismoEDiversos, nil, nil),
		strFlag("dllm-algorithm", "", nil, nil, "Algoritmo de diffusion LLM (ex.: `LowConfidence`).", sglangGroupDebugDeterminismoEDiversos, false),
		strFlag("dllm-algorithm-config", "", nil, nil, "dLLM algorithm config.", sglangGroupDebugDeterminismoEDiversos, false),
		strFlag("forward-hooks", "", nil, nil, "Forward hooks a anexar ao modelo.", sglangGroupDebugDeterminismoEDiversos, false),
		strFlag("vae-path", "", nil, nil, "VAE customizado (ex.: autoencoder destilado).", sglangGroupServidorDeModelosDeDifusao, false),
		enumFlag("backend", "", nil, []string{"auto", "sglang", "diffusers"}, nil, "Backend (auto prefere sglang, cai p/ diffusers).", sglangGroupServidorDeModelosDeDifusao),
		strFlag("attention-backend-config", "", nil, nil, "Attention backend config.", sglangGroupServidorDeModelosDeDifusao, false),
		strFlag("cache-dit-config", "", nil, nil, "Enables Cache-DiT (diffusers backend).", sglangGroupServidorDeModelosDeDifusao, false),
		intFlag("num-gpus", "", nil, nil, "Nº de GPUs.", sglangGroupServidorDeModelosDeDifusao, nil, nil),
		intFlag("sp-degree", "", nil, nil, "Sequence parallelism (remaining GPUs after TP/DP).", sglangGroupServidorDeModelosDeDifusao, nil, nil),
		intFlag("ulysses-degree", "", nil, nil, "Ulysses / Ring SP degree (in attention).", sglangGroupServidorDeModelosDeDifusao, nil, nil),
		intFlag("ring-degree", "", nil, nil, "Ulysses / Ring SP degree (in attention).", sglangGroupServidorDeModelosDeDifusao, nil, nil),
		boolFlag("enable-cfg-parallel", "", nil, false, "Paralelismo de CFG.", sglangGroupServidorDeModelosDeDifusao),
		intFlag("dp", "", nil, nil, "Data parallelism.", sglangGroupServidorDeModelosDeDifusao, nil, nil),
		intFlag("hsdp-replicate-dim", "", nil, nil, "HSDP replica/shard dimensions.", sglangGroupServidorDeModelosDeDifusao, nil, nil),
		intFlag("hsdp-shard-dim", "", nil, nil, "HSDP replica/shard dimensions.", sglangGroupServidorDeModelosDeDifusao, nil, nil),
		strFlag("prompt-file-path", "", nil, nil, "Batch prompts (one per line).", sglangGroupServidorDeModelosDeDifusao, false),
		strFlag("mask-strategy-file-path", "", nil, nil, "Mask strategy (STA).", sglangGroupServidorDeModelosDeDifusao, false),
		strFlag("warmup", "", nil, nil, "Server warmup (resolutions, e.g. `256x256`).", sglangGroupServidorDeModelosDeDifusao, false),
		strFlag("warmup-resolutions", "", nil, nil, "Server warmup (resolutions, e.g. `256x256`).", sglangGroupServidorDeModelosDeDifusao, false),
		boolFlag("dit-cpu-offload", "", nil, false, "DiT CPU offload (if memory is insufficient with FSDP).", sglangGroupServidorDeModelosDeDifusao),
		boolFlag("dit-layerwise-offload", "", nil, false, "Layer-wise offload with async prefetch (Wan, MOVA).", sglangGroupServidorDeModelosDeDifusao),
		floatFlag("dit-offload-prefetch-size", "", nil, nil, "Layer-wise offload prefetch.", sglangGroupServidorDeModelosDeDifusao, nil, nil),
		boolFlag("use-fsdp-inference", "", nil, false, "FSDP for inference (weight sharding).", sglangGroupServidorDeModelosDeDifusao),
		boolFlag("text-encoder-cpu-offload", "", nil, false, "CPU offload of text/image encoder / VAE.", sglangGroupServidorDeModelosDeDifusao),
		boolFlag("image-encoder-cpu-offload", "", nil, false, "CPU offload of text/image encoder / VAE.", sglangGroupServidorDeModelosDeDifusao),
		boolFlag("vae-cpu-offload", "", nil, false, "CPU offload of text/image encoder / VAE.", sglangGroupServidorDeModelosDeDifusao),
		boolFlag("pin-cpu-memory", "", nil, false, "Pin memory for CPU offload.", sglangGroupServidorDeModelosDeDifusao),
		boolFlag("disable-autocast", "", nil, false, "Disables autocast in denoising/VAE.", sglangGroupServidorDeModelosDeDifusao),
		boolFlag("enable-svdquant", "", nil, false, "Nunchaku SVDQuant (estilo W4A4).", sglangGroupServidorDeModelosDeDifusao),
		strFlag("quantized-model-path", "", nil, nil, "Pre-quantized Nunchaku weights.", sglangGroupServidorDeModelosDeDifusao, false),
		enumFlag("quantization-precision", "", nil, []string{"int4", "nvfp4"}, nil, "Quantization precision.", sglangGroupServidorDeModelosDeDifusao),
		intFlag("quantization-rank", "", nil, nil, "SVD low-rank dimension (e.g. `32`).", sglangGroupServidorDeModelosDeDifusao, nil, nil),
		boolFlag("quantization-act-unsigned", "", nil, false, "Unsigned activation quantization.", sglangGroupServidorDeModelosDeDifusao),
		intFlag("master-port", "", nil, nil, "Distributed / scheduler ports.", sglangGroupServidorDeModelosDeDifusao, nil, nil),
		intFlag("scheduler-port", "", nil, nil, "Distributed / scheduler ports.", sglangGroupServidorDeModelosDeDifusao, nil, nil),
		boolFlag("webui", "", nil, false, "Interface web.", sglangGroupServidorDeModelosDeDifusao),
		boolFlag("webui-port", "", nil, false, "Interface web.", sglangGroupServidorDeModelosDeDifusao),
		strFlag("output-path", "", nil, nil, "Output directory (images/videos).", sglangGroupServidorDeModelosDeDifusao, false),
		strFlag("lora-path", "", nil, nil, "Adapter LoRA (ex.: `0.125` p/ Hyper-SD).", sglangGroupServidorDeModelosDeDifusao, false),
		strFlag("lora-nickname", "", nil, nil, "Adapter LoRA (ex.: `0.125` p/ Hyper-SD).", sglangGroupServidorDeModelosDeDifusao, false),
		strFlag("lora-scale", "", nil, nil, "Adapter LoRA (ex.: `0.125` p/ Hyper-SD).", sglangGroupServidorDeModelosDeDifusao, false),
		strFlag("pipeline-config-path", "", nil, nil, "Pipeline config.", sglangGroupServidorDeModelosDeDifusao, false),
		strFlag("embedded-cfg-scale", "", nil, nil, "Built-in CFG scale / flow shift.", sglangGroupServidorDeModelosDeDifusao, false),
		strFlag("flow-shift", "", nil, nil, "Built-in CFG scale / flow shift.", sglangGroupServidorDeModelosDeDifusao, false),
		enumFlag("dit-precision", "", nil, []string{"fp32", "fp16", "bf16"}, nil, "DiT / VAE / image encoder precision.", sglangGroupServidorDeModelosDeDifusao),
		enumFlag("vae-precision", "", nil, []string{"fp32", "fp16", "bf16"}, nil, "DiT / VAE / image encoder precision.", sglangGroupServidorDeModelosDeDifusao),
		enumFlag("image-encoder-precision", "", nil, []string{"fp32", "fp16", "bf16"}, nil, "DiT / VAE / image encoder precision.", sglangGroupServidorDeModelosDeDifusao),
		strFlag("text-encoder-precisions", "", nil, nil, "Precision of each text encoder.", sglangGroupServidorDeModelosDeDifusao, false),
		boolFlag("vae-tiling", "", nil, false, "VAE tiling / spatial parallelism.", sglangGroupServidorDeModelosDeDifusao),
		boolFlag("vae-sp", "", nil, false, "VAE tiling / spatial parallelism.", sglangGroupServidorDeModelosDeDifusao),
		strFlag("dmd-denoising-steps", "", nil, nil, "Denoising steps (e.g. `1000,757,522`).", sglangGroupServidorDeModelosDeDifusao, false),
		strFlag("dit-config.prefix", "", nil, nil, "DiT prefix / quantization.", sglangGroupServidorDeModelosDeDifusao, false),
		strFlag("dit-config.quant-config", "", nil, nil, "DiT prefix / quantization.", sglangGroupServidorDeModelosDeDifusao, false),
		boolFlag("t5-config.parallel-folding", "", nil, false, "T5 parallel folding.", sglangGroupServidorDeModelosDeDifusao),
		boolFlag("t5-config.parallel-folding-mode", "", nil, false, "T5 parallel folding.", sglangGroupServidorDeModelosDeDifusao),
	} {
		add(spec)
	}
	return domain.BackendValidationSchema{SchemaVersion: 1, Kind: domain.ValidationSchemaCLIFlagsV1, BackendKind: domain.BackendKindSGLang, BackendID: "sglang-default", Source: domain.SchemaSource{GeneratedFrom: "sglang.md curated reference", SourceVersion: "curated-sglang-serve", Editable: true}, Flags: flags, Presentation: sglangPresentation()}
}

func sglangPresentation() *domain.Presentation {
	return &domain.Presentation{Groups: []domain.PresentationGroup{
		{Name: sglangGroupEssentials, Highlighted: true, Flags: []string{"served-model-name", "host", "port", "api-key", "context-length", "dtype", "quantization", "kv-cache-dtype", "mem-fraction-static", "max-running-requests", "max-total-tokens", "tensor-parallel-size", "tp-size", "pipeline-parallel-size", "data-parallel-size", "device", "enable-multimodal", "chat-template"}},
		{Name: sglangGroupServidorEGeral, Flags: []string{"host", "port", "fastapi-root-path", "grpc-mode", "config", "skip-server-warmup", "warmups", "nccl-port", "checkpoint-engine-wait-weights-before-ready", "watchdog-timeout", "soft-watchdog-timeout", "dist-timeout", "custom-sigquit-handler", "sleep-on-idle", "base-gpu-id", "gpu-id-step", "numa-node", "scheduler-recv-interval"}},
		{Name: sglangGroupModeloETokenizer, Flags: []string{"tokenizer-path", "tokenizer-mode", "tokenizer-worker-num", "skip-tokenizer-init", "trust-remote-code", "context-length", "is-embedding", "enable-multimodal", "revision", "model-impl", "served-model-name", "weight-version", "json-model-override-args", "model-checksum"}},
		{Name: sglangGroupCarregamentoDePesos, Flags: []string{"load-format", "model-loader-extra-config", "download-dir", "custom-weight-loader", "weight-loader-disable-mmap", "delete-ckpt-after-loading", "decrypted-config-file", "decrypted-draft-config-file", "remote-instance-weight-loader-seed-instance-ip", "remote-instance-weight-loader-seed-instance-service-port", "remote-instance-weight-loader-send-weights-group-ports", "remote-instance-weight-loader-backend", "remote-instance-weight-loader-start-seed-via-transfer-engine"}},
		{Name: sglangGroupDtypeEQuantizacao, Flags: []string{"dtype", "quantization", "quantization-param-path", "kv-cache-dtype", "enable-fp32-lm-head", "modelopt-quant", "modelopt-checkpoint-restore-path", "modelopt-checkpoint-save-path", "modelopt-export-path", "quantize-and-serve", "rl-quant-profile", "torchao-config"}},
		{Name: sglangGroupMemoriaEKvCache, Flags: []string{"mem-fraction-static", "max-running-requests", "max-queued-requests", "max-total-tokens", "page-size", "max-mamba-cache-size", "swa-full-tokens-ratio", "disable-hybrid-swa-memory", "hybrid-kvcache-ratio"}},
		{Name: sglangGroupCacheDePrefixoRadixEHierarquico, Flags: []string{"disable-radix-cache", "radix-eviction-policy", "enable-hierarchical-cache", "hicache-ratio", "hicache-size", "hicache-write-policy", "hicache-io-backend", "hicache-mem-layout", "disable-hicache-numa-detect", "hicache-storage-backend", "hicache-storage-prefetch-policy", "hicache-storage-backend-extra-config", "enable-lmcache"}},
		{Name: sglangGroupPrefillChunkingEScheduler, Flags: []string{"chunked-prefill-size", "prefill-max-requests", "enable-dynamic-chunking", "max-prefill-tokens", "enable-mixed-chunk", "disable-chunked-prefix-cache", "schedule-policy", "enable-priority-scheduling", "abort-on-priority-when-disabled", "schedule-low-priority-values-first", "priority-scheduling-preemption-threshold", "schedule-conservativeness", "num-continuous-decode-steps", "disable-overlap-schedule", "enable-prefill-delayer", "prefill-delayer-max-delay-passes", "prefill-delayer-token-usage-low-watermark"}},
		{Name: sglangGroupStreamingSamplingEGramatica, Flags: []string{"stream-interval", "stream-output", "random-seed", "sampling-defaults", "preferred-sampling-params", "grammar-backend", "constrained-json-whitespace-pattern", "constrained-json-disable-any-whitespace"}},
		{Name: sglangGroupParalelismoEExecucaoDistribuida, Flags: []string{"device", "tensor-parallel-size", "tp-size", "pipeline-parallel-size", "pp-size", "data-parallel-size", "dp-size", "attention-context-parallel-size", "attn-cp-size", "moe-data-parallel-size", "moe-dp-size", "pp-max-micro-batch-size", "pp-async-batch-depth", "load-balance-method", "dist-init-addr", "nccl-init-addr", "nnodes", "node-rank", "enable-dp-attention", "enable-dp-lm-head", "enable-attn-tp-input-scattered", "moe-dense-tp-size"}},
		{Name: sglangGroupMoeEExpertParallelism, Flags: []string{"expert-parallel-size", "ep-size", "ep", "moe-a2a-backend", "moe-runner-backend", "flashinfer-mxfp4-moe-precision", "enable-flashinfer-allreduce-fusion", "deepep-mode", "ep-num-redundant-experts", "ep-dispatch-algorithm", "init-expert-location", "enable-eplb", "eplb-algorithm", "eplb-rebalance-num-iterations", "eplb-rebalance-layers-per-chunk", "eplb-min-rebalancing-utilization-threshold", "expert-distribution-recorder-mode", "expert-distribution-recorder-buffer-size", "enable-expert-distribution-metrics", "deepep-config", "elastic-ep-backend", "mooncake-ib-device", "disable-shared-experts-fusion"}},
		{Name: sglangGroupBackendsDeAtencaoEGemm, Flags: []string{"attention-backend", "prefill-attention-backend", "decode-attention-backend", "sampling-backend", "mm-attention-backend", "fp8-gemm-backend", "fp4-gemm-backend", "disable-flashinfer-autotune", "flashinfer-mla-disable-ragged", "enable-fused-qk-norm-rope", "triton-attention-reduce-in-fp32", "triton-attention-num-kv-splits", "triton-attention-split-tile-size"}},
		{Name: sglangGroupAtencaoEsparsaNsaEDoubleSparsity, Flags: []string{"nsa-prefill-backend", "nsa-decode-backend", "enable-nsa-prefill-context-parallel", "nsa-prefill-cp-mode", "enable-double-sparsity", "ds-channel-config-path", "ds-heavy-channel-num", "ds-heavy-token-num", "ds-heavy-channel-type", "ds-sparse-decode-threshold", "hierarchical-sparse-attention-extra-config"}},
		{Name: sglangGroupMambaSsm, Flags: []string{"mamba-ssm-dtype", "mamba-full-memory-ratio", "mamba-scheduler-strategy", "mamba-track-interval", "mamba-backend"}},
		{Name: sglangGroupLora, Flags: []string{"enable-lora", "lora-paths", "max-lora-rank", "lora-target-modules", "max-loras-per-batch", "max-loaded-loras", "lora-eviction-policy", "lora-backend", "max-lora-chunk-size", "enable-lora-overlap-loading"}},
		{Name: sglangGroupSpeculativeDecoding, Flags: []string{"speculative-algorithm", "speculative-draft-model-path", "speculative-draft-model", "speculative-draft-model-revision", "speculative-draft-load-format", "speculative-draft-model-quantization", "speculative-num-steps", "speculative-eagle-topk", "speculative-num-draft-tokens", "speculative-accept-threshold-single", "speculative-accept-threshold-acc", "speculative-token-map", "speculative-attention-mode", "speculative-draft-attention-backend", "speculative-moe-runner-backend", "speculative-moe-a2a-backend", "enable-multi-layer-eagle", "speculative-ngram-match-type", "speculative-ngram-branch-length", "speculative-ngram-capacity"}},
		{Name: sglangGroupCudaGraphETorchCompile, Flags: []string{"disable-cuda-graph", "disable-cuda-graph-padding", "cuda-graph-max-bs", "cuda-graph-bs", "enable-profile-cuda-graph", "enable-cudagraph-gc", "enable-torch-compile", "enable-torch-compile-debug-mode", "torch-compile-max-bs", "enable-piecewise-cuda-graph", "piecewise-cuda-graph-tokens", "piecewise-cuda-graph-max-tokens", "piecewise-cuda-graph-compiler"}},
		{Name: sglangGroupComunicacaoEAllReduce, Flags: []string{"disable-custom-all-reduce", "enable-mscclpp", "enable-torch-symm-mem", "enable-symm-mem", "enable-nccl-nvls", "enable-p2p-check", "disable-flashinfer-cutlass-moe-fp4-allgather"}},
		{Name: sglangGroupOffloadDePesosEMemorySaver, Flags: []string{"cpu-offload-gb", "offload-group-size", "offload-num-in-group", "offload-prefetch-step", "offload-mode", "enable-memory-saver", "enable-weights-cpu-backup", "enable-draft-weights-cpu-backup", "kt-weight-path", "kt-method", "kt-cpuinfer", "kt-threadpool-count", "kt-num-gpu-experts", "kt-max-deferred-experts-per-token"}},
		{Name: sglangGroupMultimodalEEncoder, Flags: []string{"limit-mm-data-per-request", "mm-max-concurrent-calls", "mm-per-request-timeout", "enable-broadcast-mm-inputs-process", "mm-process-config", "mm-enable-dp-encoder", "disable-fast-image-processor", "keep-mm-feature-on-device", "enable-prefix-mm-cache", "encoder-only", "language-only", "encoder-transfer-backend", "encoder-urls"}},
		{Name: sglangGroupApiOpenaiEParsers, Flags: []string{"api-key", "admin-api-key", "chat-template", "hf-chat-template-name", "completion-template", "file-storage-path", "enable-cache-report", "reasoning-parser", "tool-call-parser", "tool-server", "multi-item-scoring-delimiter", "allow-auto-truncate", "enable-custom-logit-processor", "enable-return-hidden-states", "enable-return-routed-experts"}},
		{Name: sglangGroupLoggingMetricasETracing, Flags: []string{"log-level", "log-level-http", "log-requests", "log-requests-level", "log-requests-format", "log-requests-target", "uvicorn-access-log-exclude-prefixes", "crash-dump-folder", "show-time-cost", "enable-metrics", "enable-metrics-for-all-schedulers", "tokenizer-metrics-custom-labels-header", "tokenizer-metrics-allowed-custom-labels", "extra-metric-labels", "bucket-time-to-first-token", "bucket-inter-token-latency", "bucket-e2e-request-latency", "collect-tokens-histogram", "prompt-tokens-buckets", "generation-tokens-buckets", "gc-warning-threshold-secs", "decode-log-interval", "enable-request-time-stats-logging", "kv-events-config", "enable-trace", "otlp-traces-endpoint", "export-metrics-to-file", "export-metrics-to-file-dir"}},
		{Name: sglangGroupPdDisaggregation, Flags: []string{"disaggregation-mode", "disaggregation-transfer-backend", "disaggregation-bootstrap-port", "disaggregation-decode-tp", "disaggregation-decode-dp", "disaggregation-prefill-pp", "disaggregation-ib-device", "disaggregation-decode-enable-offload-kvcache", "num-reserved-decode-tokens", "disaggregation-decode-polling-interval"}},
		{Name: sglangGroupDebugDeterminismoEDiversos, Flags: []string{"enable-deterministic-inference", "enable-nan-detection", "debug-tensor-dump-output-folder", "debug-tensor-dump-layers", "debug-tensor-dump-input-file", "debug-tensor-dump-inject", "enable-tokenizer-batch-encode", "disable-tokenizer-batch-decode", "enable-dynamic-batch-tokenizer", "dynamic-batch-tokenizer-batch-size", "dynamic-batch-tokenizer-batch-timeout", "disable-outlines-disk-cache", "enable-precise-embedding-interpolation", "rl-on-policy-target", "enable-pdmux", "pdmux-config-path", "sm-group-num", "dllm-algorithm", "dllm-algorithm-config", "forward-hooks"}},
		{Name: sglangGroupServidorDeModelosDeDifusao, Flags: []string{"vae-path", "backend", "attention-backend-config", "cache-dit-config", "num-gpus", "sp-degree", "ulysses-degree", "ring-degree", "enable-cfg-parallel", "dp", "hsdp-replicate-dim", "hsdp-shard-dim", "prompt-file-path", "mask-strategy-file-path", "warmup", "warmup-resolutions", "dit-cpu-offload", "dit-layerwise-offload", "dit-offload-prefetch-size", "use-fsdp-inference", "text-encoder-cpu-offload", "image-encoder-cpu-offload", "vae-cpu-offload", "pin-cpu-memory", "disable-autocast", "enable-svdquant", "quantized-model-path", "quantization-precision", "quantization-rank", "quantization-act-unsigned", "master-port", "scheduler-port", "webui", "webui-port", "output-path", "lora-path", "lora-nickname", "lora-scale", "pipeline-config-path", "embedded-cfg-scale", "flow-shift", "dit-precision", "vae-precision", "image-encoder-precision", "text-encoder-precisions", "vae-tiling", "vae-sp", "dmd-denoising-steps", "dit-config.prefix", "dit-config.quant-config", "t5-config.parallel-folding", "t5-config.parallel-folding-mode"}},
	}}
}
