package backendschema

import (
	"github.com/quantmind-br/model-loader/internal/domain"
	"github.com/quantmind-br/model-loader/internal/service/internal/ptrutil"
)

const (
	vllmGroupEssentials      = "Essentials"
	vllmGroupServer          = "1. Server and General"
	vllmGroupFrontend        = "2. Frontend (OpenAI API)"
	vllmGroupModel           = "3. Model (ModelConfig)"
	vllmGroupLoad            = "4. Weight Loading (LoadConfig)"
	vllmGroupAttention       = "5. Attention and Mamba"
	vllmGroupStructured      = "6. Structured Outputs and Reasoning"
	vllmGroupParallel        = "7. Parallelism and Distributed Execution"
	vllmGroupKV              = "8. KV Cache"
	vllmGroupWeightOffload   = "9. Weight Offloading"
	vllmGroupMultimodal      = "10. Multimodal"
	vllmGroupLora            = "11. LoRA"
	vllmGroupObservability   = "12. Observability and Metrics"
	vllmGroupScheduler       = "13. Scheduler"
	vllmGroupCompilation     = "14. Compilation and CUDA Graphs"
	vllmGroupKernels         = "15. Kernels and MoE"
	vllmGroupAdvancedConfigs = "16. Advanced Configs (VllmConfig)"
)

// CuratedVLLMSchema returns the hand-curated vLLM serve schema. It is a
// version-qualified compatibility union built from the vLLM engine CLI argument
// declarations (vllm/engine/arg_utils.py, vllm/entrypoints/openai/cli_args.py and
// the vllm/config dataclasses they pull in) of every installed "vllm" backend,
// spanning vLLM 0.20.2 through 0.28.1rc1.dev118+g87b9b5b8d. The profile model
// field is handled separately, so positional model_tag and --model are
// intentionally omitted. One schema serves every "vllm" catalog entry, so a flag
// that only some of those builds accept is kept here and its version requirement
// is called out in its description.
func CuratedVLLMSchema() domain.BackendValidationSchema {
	flags := map[string]domain.FlagSpec{}
	add := func(spec domain.FlagSpec) {
		flags[spec.Long] = spec
	}

	for _, spec := range []domain.FlagSpec{
		strFlag("config", "", nil, nil, "Reads CLI options from a YAML file.", vllmGroupServer, false),
		intFlag("api-server-count", "asc", nil, nil, "Number of API server processes to run; default follows data_parallel_size.", vllmGroupServer, ptrutil.Ptr(1), nil),
		boolFlag("headless", "", nil, false, "Runs without an HTTP frontend on secondary nodes in multi-node data parallel mode.", vllmGroupServer),
		boolFlag("grpc", "", nil, false, "Starts a gRPC server instead of OpenAI HTTP; requires vllm[grpc].", vllmGroupServer),
		boolFlag("disable-log-stats", "", nil, false, "Disables statistics logging.", vllmGroupServer),
		boolFlag("enable-log-requests", "", nil, false, "Logs request information; DEBUG may include prompts.", vllmGroupServer),
		boolFlag("no-enable-log-requests", "", nil, false, "Explicitly disables request logging.", vllmGroupServer),
		boolFlag("aggregate-engine-logging", "", nil, false, "Logs aggregated statistics in data parallelism.", vllmGroupServer),
		intFlag("shutdown-timeout", "", nil, 0, "Shutdown timeout in seconds; 0 aborts immediately.", vllmGroupServer, ptrutil.Ptr(0), nil),
		enumFlag("gdn-prefill-backend", "", nil, []string{"flashinfer", "triton", "cutedsl"}, nil, "Selects the GDN prefill backend; cutedsl requires vLLM 0.23 or later.", vllmGroupServer),
		enumFlag("kda-prefill-backend", "", nil, []string{"auto", "triton", "flashkda"}, nil, "Selects the KDA prefill backend. Requires vLLM 0.26.1 or later.", vllmGroupServer),
		boolFlag("fail-on-environ-validation", "", nil, false, "Fatal error if environment validation fails.", vllmGroupServer),
		boolFlag("no-fail-on-environ-validation", "", nil, false, "Ignores non-fatal environment validation failures.", vllmGroupServer),

		strFlag("host", "", nil, nil, "Listen address; None listens on all interfaces.", vllmGroupFrontend, false),
		portFlag("port", "", 8000, "HTTP server port.", vllmGroupFrontend),
		strFlag("uds", "", nil, nil, "Unix domain socket; ignores host/port when set.", vllmGroupFrontend, false),
		strFlag("api-key", "", nil, nil, "Requires one of the keys in the request header.", vllmGroupFrontend, false),
		strFlag("root-path", "", nil, nil, "FastAPI root_path behind a path-routing proxy.", vllmGroupFrontend, false),
		strFlag("allowed-origins", "", nil, "['*']", "Origins allowed by CORS.", vllmGroupFrontend, false),
		strFlag("allowed-methods", "", nil, "['*']", "Methods allowed by CORS.", vllmGroupFrontend, false),
		strFlag("allowed-headers", "", nil, "['*']", "Headers allowed by CORS.", vllmGroupFrontend, false),
		boolFlag("allow-credentials", "", nil, false, "Allows CORS credentials.", vllmGroupFrontend),
		boolFlag("no-allow-credentials", "", nil, false, "Disables CORS credentials.", vllmGroupFrontend),
		strFlag("ssl-certfile", "", nil, nil, "SSL certificate.", vllmGroupFrontend, false),
		strFlag("ssl-keyfile", "", nil, nil, "SSL key.", vllmGroupFrontend, false),
		strFlag("ssl-ca-certs", "", nil, nil, "CA file for SSL.", vllmGroupFrontend, false),
		intFlag("ssl-cert-reqs", "", nil, 0, "Requires client certificate according to stdlib ssl.", vllmGroupFrontend, ptrutil.Ptr(0), nil),
		strFlag("ssl-ciphers", "", nil, nil, "TLS 1.2 and below ciphers.", vllmGroupFrontend, false),
		boolFlag("enable-ssl-refresh", "", nil, false, "Reloads SSL context when files change.", vllmGroupFrontend),
		boolFlag("no-enable-ssl-refresh", "", nil, false, "Disables automatic SSL context reload.", vllmGroupFrontend),
		strFlag("chat-template", "", nil, nil, "Custom chat template or file.", vllmGroupFrontend, false),
		enumFlag("chat-template-content-format", "", nil, []string{"auto", "openai", "string"}, "auto", "Content format in the template.", vllmGroupFrontend),
		strFlag("default-chat-template-kwargs", "", nil, nil, "Default JSON arguments for the template.", vllmGroupFrontend, false),
		strFlag("response-role", "", nil, "assistant", "Role assigned to the response.", vllmGroupFrontend, false),
		boolFlag("cohere-is-reasoning-model", "", nil, true, "Cohere /cohere/v2/chat only; whether the served model is a reasoning Command-family model, surfacing chain-of-thought as a thinking block instead of the tool_plan field. Requires vLLM 0.26.1 or later.", vllmGroupFrontend),
		boolFlag("no-cohere-is-reasoning-model", "", nil, false, "Treats the served model as a non-reasoning Command model on the Cohere endpoint. Requires vLLM 0.26.1 or later.", vllmGroupFrontend),
		enumFlag("cohere-format", "", nil, []string{"cmd4", "cmd3"}, "cmd4", "Cohere --tokenizer-mode cohere prompt format: cmd4 for current Command A+ models or cmd3 for earlier Cmd-A models. Requires vLLM 0.26.1 or later.", vllmGroupFrontend),
		boolFlag("enable-auto-tool-choice", "", nil, false, "Enables automatic tool choice.", vllmGroupFrontend),
		boolFlag("no-enable-auto-tool-choice", "", nil, false, "Disables automatic tool choice.", vllmGroupFrontend),
		strFlag("tool-call-parser", "", nil, nil, "Tool-call parser for the model.", vllmGroupFrontend, false),
		strFlag("tool-parser-plugin", "", nil, "", "Tool parser plugin.", vllmGroupFrontend, false),
		strFlag("reasoning-parser", "", nil, "", "Reasoning-content parser in OpenAI format.", vllmGroupFrontend, false),
		strFlag("lora-modules", "", nil, nil, "Defines LoRA modules exposed in the API.", vllmGroupFrontend, false),
		intFlag("max-log-len", "", nil, nil, "Truncates prompt and output logs.", vllmGroupFrontend, ptrutil.Ptr(0), nil),
		boolFlag("enable-request-id-headers", "", nil, false, "Adds X-Request-Id to responses.", vllmGroupFrontend),
		boolFlag("no-enable-request-id-headers", "", nil, false, "Disables X-Request-Id in responses.", vllmGroupFrontend),
		boolFlag("disable-fastapi-docs", "", nil, false, "Disables Swagger, ReDoc, and OpenAPI.", vllmGroupFrontend),
		boolFlag("no-disable-fastapi-docs", "", nil, false, "Keeps Swagger, ReDoc, and OpenAPI enabled.", vllmGroupFrontend),
		boolFlag("enable-offline-docs", "", nil, false, "Uses offline FastAPI docs with embedded assets.", vllmGroupFrontend),
		boolFlag("no-enable-offline-docs", "", nil, false, "Disables offline FastAPI docs.", vllmGroupFrontend),
		boolFlag("disable-uvicorn-access-log", "", nil, false, "Disables uvicorn access log.", vllmGroupFrontend),
		boolFlag("no-disable-uvicorn-access-log", "", nil, false, "Keeps uvicorn access log enabled.", vllmGroupFrontend),
		strFlag("disable-access-log-for-endpoints", "", nil, nil, "Suppresses access logs for comma-separated endpoints.", vllmGroupFrontend, false),
		enumFlag("uvicorn-log-level", "", nil, []string{"critical", "error", "warning", "info", "debug", "trace"}, "info", "Uvicorn log level.", vllmGroupFrontend),
		strFlag("middleware", "", nil, "[]", "Extra ASGI middleware; repeatable.", vllmGroupFrontend, false),
		boolFlag("return-tokens-as-token-ids", "", nil, false, "Returns tokens as token IDs.", vllmGroupFrontend),
		boolFlag("no-return-tokens-as-token-ids", "", nil, false, "Returns tokens as text when possible.", vllmGroupFrontend),
		boolFlag("enable-prompt-tokens-details", "", nil, false, "Adds prompt token details to usage.", vllmGroupFrontend),
		boolFlag("no-enable-prompt-tokens-details", "", nil, false, "Disables prompt token details in usage.", vllmGroupFrontend),
		boolFlag("enable-force-include-usage", "", nil, false, "Forces usage inclusion in responses.", vllmGroupFrontend),
		boolFlag("no-enable-force-include-usage", "", nil, false, "Does not force usage inclusion in responses.", vllmGroupFrontend),
		intFlag("h11-max-header-count", "", nil, 256, "Maximum HTTP headers.", vllmGroupFrontend, ptrutil.Ptr(1), nil),
		intFlag("h11-max-incomplete-event-size", "", nil, 4194304, "Maximum incomplete HTTP event size in bytes.", vllmGroupFrontend, ptrutil.Ptr(1), nil),
		portFlag("data-parallel-supervisor-port", "", 9256, "HTTP port for aggregated health endpoints in multi-port external LB mode. Requires vLLM 0.23 or later.", vllmGroupFrontend),
		intFlag("dp-supervisor-probe-failure-threshold", "", nil, 3, "Consecutive connection-error retries before a child health probe is declared failed. Requires vLLM 0.23 or later.", vllmGroupFrontend, ptrutil.Ptr(1), nil),
		floatFlag("dp-supervisor-probe-interval-s", "", nil, 5.0, "Seconds between aggregated health probes in multi-port external LB mode. Requires vLLM 0.23 or later.", vllmGroupFrontend, ptrutil.Ptr(0.0), nil),
		floatFlag("dp-supervisor-probe-timeout-s", "", nil, 5.0, "Seconds to wait between retries when a child health probe fails with a connection error. Requires vLLM 0.23 or later.", vllmGroupFrontend, ptrutil.Ptr(0.0), nil),
		boolFlag("enable-flash-late-interaction", "", nil, true, "Runs pooling score MaxSim on GPU in the API server process.", vllmGroupFrontend),
		boolFlag("no-enable-flash-late-interaction", "", nil, false, "Disables GPU MaxSim scoring in the API server process.", vllmGroupFrontend),
		boolFlag("enable-log-deltas", "", nil, true, "Logs streaming response deltas.", vllmGroupFrontend),
		boolFlag("no-enable-log-deltas", "", nil, false, "Disables logging of streaming response deltas.", vllmGroupFrontend),
		boolFlag("enable-log-outputs", "", nil, false, "Logs model outputs in addition to inputs.", vllmGroupFrontend),
		boolFlag("no-enable-log-outputs", "", nil, false, "Disables logging of model outputs.", vllmGroupFrontend),
		boolFlag("enable-tokenizer-info-endpoint", "", nil, false, "Exposes the tokenizer info endpoint.", vllmGroupFrontend),
		boolFlag("no-enable-tokenizer-info-endpoint", "", nil, false, "Disables the tokenizer info endpoint.", vllmGroupFrontend),
		boolFlag("exclude-tools-when-tool-choice-none", "", nil, false, "Excludes tool definitions when tool_choice is none.", vllmGroupFrontend),
		boolFlag("no-exclude-tools-when-tool-choice-none", "", nil, false, "Keeps tool definitions when tool_choice is none.", vllmGroupFrontend),
		enumFlag("fingerprint-mode", "", nil, []string{"custom", "full", "hash", "none"}, "full", "How the system fingerprint is generated in API responses.", vllmGroupFrontend),
		strFlag("fingerprint-value", "", nil, nil, "Custom fingerprint value used with fingerprint-mode custom.", vllmGroupFrontend, false),
		strFlag("log-config-file", "", nil, nil, "Path to a logging config JSON file.", vllmGroupFrontend, false),
		boolFlag("log-error-stack", "", nil, false, "Logs stack traces on error responses.", vllmGroupFrontend),
		boolFlag("no-log-error-stack", "", nil, false, "Disables stack traces in error logs.", vllmGroupFrontend),
		boolFlag("tokens-only", "", nil, false, "Enables tokens-only mode in the frontend.", vllmGroupFrontend),
		boolFlag("no-tokens-only", "", nil, false, "Disables tokens-only mode.", vllmGroupFrontend),
		strFlag("tool-server", "", nil, nil, "Tool server addresses used for built-in tool calling.", vllmGroupFrontend, false),
		intFlag("sse-keep-alive-interval", "", nil, 0, "Seconds between SSE keep-alive comment lines while a streaming completion is idle, so read-timeout proxies do not close the connection; 0 disables. Requires vLLM 0.28.1 or later.", vllmGroupFrontend, ptrutil.Ptr(0), nil),
		boolFlag("trust-request-chat-template", "", nil, false, "Trusts chat templates provided in requests.", vllmGroupFrontend),
		boolFlag("no-trust-request-chat-template", "", nil, false, "Rejects chat templates provided in requests.", vllmGroupFrontend),

		strFlag("served-model-name", "", nil, nil, "Model name in the API and metrics; default uses the model.", vllmGroupModel, false),
		strFlag("tokenizer", "", nil, nil, "Alternative tokenizer; default uses the model.", vllmGroupModel, false),
		strFlag("tokenizer-mode", "", nil, "auto", "Tokenizer mode: auto, hf, slow, mistral, deepseek_v32, deepseek_v4, or a plugin-provided value; inkling requires vLLM 0.26 or later, cohere and kimi_k3 require vLLM 0.26.1 or later, and fastokens exists only on the vLLM 0.20.x DFlash fork.", vllmGroupModel, false),
		strFlag("revision", "", nil, nil, "Branch, tag or commit of the model on Hugging Face.", vllmGroupModel, false),
		strFlag("code-revision", "", nil, nil, "Branch, tag, or commit of remote code.", vllmGroupModel, false),
		strFlag("tokenizer-revision", "", nil, nil, "Branch, tag or commit of the tokenizer.", vllmGroupModel, false),
		enumFlag("dtype", "", nil, []string{"auto", "bfloat16", "float16", "float32", "half", "float"}, "auto", "Data type for weights and activations.", vllmGroupModel),
		strFlag("max-model-len", "", nil, nil, "Total context length; accepts integer, 1k, auto, or -1.", vllmGroupModel, false),
		strFlag("quantization", "q", nil, nil, "Weight quantization method.", vllmGroupModel, false),
		intFlag("seed", "", nil, 0, "Global reproducibility seed.", vllmGroupModel, nil, nil),
		boolFlag("trust-remote-code", "", nil, false, "Trusts remote Hugging Face code.", vllmGroupModel),
		boolFlag("no-trust-remote-code", "", nil, false, "Disables execution of remote Hugging Face code.", vllmGroupModel),
		strFlag("hf-token", "", nil, nil, "Bearer token for remote files; True uses local token.", vllmGroupModel, false),
		strFlag("hf-overrides", "", nil, "{}", "Overrides HF config with JSON.", vllmGroupModel, false),
		strFlag("hf-config-path", "", nil, nil, "Alternative HF config path.", vllmGroupModel, false),
		strFlag("config-format", "", nil, "auto", "Model config format: auto, hf, mistral, or a plugin-provided value.", vllmGroupModel, false),
		strFlag("model-impl", "", nil, "auto", "Model implementation: auto, vllm, transformers, terratorch, or a plugin-provided value.", vllmGroupModel, false),
		enumFlag("runner", "", nil, []string{"auto", "generate", "pooling", "draft"}, "auto", "Model runner type.", vllmGroupModel),
		enumFlag("convert", "", nil, []string{"auto", "classify", "embed", "none"}, "auto", "Adapts the model, for example from generation to pooling.", vllmGroupModel),
		boolFlag("enforce-eager", "", nil, false, "Forces eager mode, without CUDA graph.", vllmGroupModel),
		boolFlag("no-enforce-eager", "", nil, false, "Allows CUDA graphs and compilation when applicable.", vllmGroupModel),
		boolFlag("enable-sleep-mode", "", nil, false, "Enables engine sleep mode on CUDA/HIP.", vllmGroupModel),
		boolFlag("no-enable-sleep-mode", "", nil, false, "Disables engine sleep mode.", vllmGroupModel),
		boolFlag("disable-sliding-window", "", nil, false, "Disables sliding window.", vllmGroupModel),
		boolFlag("no-disable-sliding-window", "", nil, false, "Keeps sliding window enabled when supported.", vllmGroupModel),
		boolFlag("disable-cascade-attn", "", nil, true, "Disables cascade attention.", vllmGroupModel),
		boolFlag("no-disable-cascade-attn", "", nil, false, "Keeps cascade attention enabled.", vllmGroupModel),
		intFlag("max-logprobs", "", nil, 20, "Maximum returned logprobs; -1 removes the limit.", vllmGroupModel, nil, nil),
		enumFlag("logprobs-mode", "", nil, []string{"raw_logprobs", "processed_logprobs", "raw_logits", "processed_logits"}, "raw_logprobs", "Returned logprobs content.", vllmGroupModel),
		strFlag("generation-config", "", nil, "auto", "Generation config source: auto, vllm or path.", vllmGroupModel, false),
		strFlag("override-generation-config", "", nil, "{}", "Overrides generation config with JSON.", vllmGroupModel, false),
		boolFlag("enable-prompt-embeds", "", nil, false, "Accepts prompt_embeds as input; use only with trusted users.", vllmGroupModel),
		boolFlag("no-enable-prompt-embeds", "", nil, false, "Disables input via prompt_embeds.", vllmGroupModel),
		boolFlag("skip-tokenizer-init", "", nil, false, "Skips tokenizer init and expects token IDs.", vllmGroupModel),
		boolFlag("no-skip-tokenizer-init", "", nil, false, "Initializes tokenizer normally.", vllmGroupModel),
		strFlag("pooler-config", "", nil, nil, "Pooling config for embedding models.", vllmGroupModel, false),
		strFlag("allowed-local-media-path", "", nil, "", "Allows reading local media; security risk.", vllmGroupModel, false),
		strFlag("allowed-media-domains", "", nil, nil, "Restricts multimodal media domains.", vllmGroupModel, false),
		intFlag("renderer-num-workers", "", nil, 1, "Rendering pool threads.", vllmGroupModel, ptrutil.Ptr(1), nil),
		strFlag("logits-processors", "", nil, nil, "Custom logits processor classes.", vllmGroupModel, false),
		strFlag("override-attention-dtype", "", nil, nil, "Overrides attention dtype. Removed in vLLM 0.28 and later.", vllmGroupModel, false),
		boolFlag("return-sampling-mask", "", nil, false, "Returns the post-processing token support mask for each sample. Requires vLLM 0.28 or later.", vllmGroupModel),
		boolFlag("no-return-sampling-mask", "", nil, false, "Omits the per-sample token support mask. Requires vLLM 0.28 or later.", vllmGroupModel),
		boolFlag("enable-trace-replay", "", nil, false, "Allows requests to set SamplingParams.trace_decode_token_ids, forcing decoding to follow a predetermined token sequence while still computing real logprobs; reserves a per-request trace buffer, so it is for debugging and RL workflows only. Requires vLLM 0.28.1 or later.", vllmGroupModel),
		boolFlag("no-enable-trace-replay", "", nil, false, "Rejects trace_decode_token_ids and reserves no trace buffer. Requires vLLM 0.28.1 or later.", vllmGroupModel),
		strFlag("io-processor-plugin", "", nil, nil, "IOProcessor plugin loaded at startup.", vllmGroupModel, false),
		boolFlag("allow-deprecated-quantization", "", nil, false, "Allows obsolete quantizations.", vllmGroupModel),
		boolFlag("no-allow-deprecated-quantization", "", nil, false, "Blocks obsolete quantizations.", vllmGroupModel),
		boolFlag("enable-cumem-allocator", "", nil, false, "Enables the custom cumem allocator for advanced GPU memory features such as multi-node NVLink; sleep mode enables it automatically. Requires vLLM 0.23 or later.", vllmGroupModel),
		boolFlag("no-enable-cumem-allocator", "", nil, false, "Disables the custom cumem allocator. Requires vLLM 0.23 or later.", vllmGroupModel),
		boolFlag("enable-return-routed-experts", "", nil, false, "Returns routed experts.", vllmGroupModel),
		boolFlag("no-enable-return-routed-experts", "", nil, false, "Does not return routed experts.", vllmGroupModel),
		boolFlag("use-fp64-gumbel", "", nil, false, "Uses FP64 Gumbel noise in the sampler to reduce ties, at lower kernel throughput. Requires vLLM 0.23 or later.", vllmGroupModel),
		boolFlag("no-use-fp64-gumbel", "", nil, false, "Uses FP32 Gumbel noise in the sampler. Requires vLLM 0.23 or later.", vllmGroupModel),
		strFlag("quantization-config", "", nil, nil, "Quantization configuration in JSON with per-layer-kind specs and ignore patterns. Requires vLLM 0.23 or later.", vllmGroupModel, false),
		strFlag("model-class-overrides", "", nil, "{}", "Overrides the model class for one or more architectures in JSON, mapping an architecture name to a module:class target; for development and debugging only. Requires vLLM 0.23.1.dev968 or later.", vllmGroupModel, false),

		strFlag("load-format", "", nil, "auto", "Format of weights to load: auto, safetensors, pt, instanttensor, npcache, dummy, tensorizer, runai_streamer, runai_streamer_sharded, bitsandbytes, sharded_state, gguf, mistral, modelexpress, or a plugin-provided value.", vllmGroupLoad, false),
		strFlag("download-dir", "", nil, nil, "Weights download/cache directory.", vllmGroupLoad, false),
		strFlag("ignore-patterns", "", nil, "['original/**/*']", "Patterns to ignore when loading weights.", vllmGroupLoad, false),
		strFlag("model-loader-extra-config", "", nil, "{}", "Extra JSON config passed to the loader.", vllmGroupLoad, false),
		enumFlag("safetensors-load-strategy", "", nil, []string{"None", "lazy", "eager", "prefetch", "torchao"}, nil, "Safetensors read strategy.", vllmGroupLoad),
		strFlag("safetensors-prefetch-block-size", "", nil, "16M", "Prefetch read size. Requires vLLM 0.23 or later.", vllmGroupLoad, false),
		intFlag("safetensors-prefetch-num-threads", "", nil, 8, "Prefetch threads. Requires vLLM 0.23 or later.", vllmGroupLoad, ptrutil.Ptr(1), nil),
		strFlag("pt-load-map-location", "", nil, "cpu", "torch.load map_location.", vllmGroupLoad, false),
		boolFlag("use-tqdm-on-load", "", nil, true, "Shows progress bar during loading.", vllmGroupLoad),
		boolFlag("no-use-tqdm-on-load", "", nil, false, "Disables progress bar during loading.", vllmGroupLoad),

		strFlag("attention-backend", "", nil, nil, "Attention backend; auto/None lets vLLM decide.", vllmGroupAttention, false),
		// vLLM resolves this via MambaBackendEnum[value.upper()], so the uppercase
		// member names are equally valid; keywords let them through the enum check.
		withKeywords(enumFlag("mamba-backend", "", nil, []string{"triton", "flashinfer", "cpu"}, "triton", "Mamba SSM backend; cpu requires vLLM 0.26.1 or later.", vllmGroupAttention), "TRITON", "FLASHINFER", "CPU"),
		enumFlag("mamba-ssu-algorithm", "", nil, []string{"auto", "simple", "vertical", "horizontal", "None"}, nil, "Mamba SSU (state space update) algorithm. Requires vLLM 0.26.1 or later.", vllmGroupAttention),
		boolFlag("enable-mamba-cache-stochastic-rounding", "", nil, false, "Uses stochastic rounding in fp16 SSM cache.", vllmGroupAttention),
		boolFlag("no-enable-mamba-cache-stochastic-rounding", "", nil, false, "Disables stochastic rounding in SSM cache.", vllmGroupAttention),
		intFlag("mamba-cache-philox-rounds", "", nil, 0, "Philox PRNG rounds for stochastic rounding.", vllmGroupAttention, ptrutil.Ptr(0), nil),

		strFlag("reasoning-parser-plugin", "", nil, "", "Reasoning parser plugin loaded dynamically.", vllmGroupStructured, false),
		strFlag("structured-outputs-config", "", nil, nil, "Full structured output config in JSON.", vllmGroupStructured, false),

		intFlag("tensor-parallel-size", "tp", nil, 1, "Tensor parallelism groups.", vllmGroupParallel, ptrutil.Ptr(1), nil),
		intFlag("pipeline-parallel-size", "pp", nil, 1, "Pipeline parallelism groups.", vllmGroupParallel, ptrutil.Ptr(1), nil),
		intFlag("data-parallel-size", "dp", nil, 1, "Data parallelism groups.", vllmGroupParallel, ptrutil.Ptr(1), nil),
		intFlag("data-parallel-size-local", "dpl", nil, nil, "Local DP replicas on this node.", vllmGroupParallel, ptrutil.Ptr(1), nil),
		intFlag("data-parallel-rank", "dpn", nil, nil, "DP rank of this instance for external LB/MoE.", vllmGroupParallel, ptrutil.Ptr(0), nil),
		intFlag("data-parallel-start-rank", "dpr", nil, nil, "Initial DP rank on secondary nodes.", vllmGroupParallel, ptrutil.Ptr(0), nil),
		strFlag("data-parallel-address", "dpa", nil, nil, "Address of the DP cluster head node.", vllmGroupParallel, false),
		portFlag("data-parallel-rpc-port", "dpp", 29550, "Data parallelism RPC port.", vllmGroupParallel),
		enumFlag("data-parallel-backend", "dpb", nil, []string{"mp", "ray"}, "mp", "Data parallelism backend.", vllmGroupParallel),
		boolFlag("data-parallel-external-lb", "dpe", nil, false, "One-pod-per-rank external LB mode for MoE.", vllmGroupParallel),
		boolFlag("no-data-parallel-external-lb", "", nil, false, "Disables external DP load-balancing mode.", vllmGroupParallel),
		boolFlag("data-parallel-hybrid-lb", "dph", nil, false, "Per-node hybrid LB mode.", vllmGroupParallel),
		boolFlag("no-data-parallel-hybrid-lb", "", nil, false, "Disables hybrid DP load-balancing mode.", vllmGroupParallel),
		intFlag("decode-context-parallel-size", "dcp", nil, 1, "Decode context parallel groups.", vllmGroupParallel, ptrutil.Ptr(1), nil),
		intFlag("prefill-context-parallel-size", "pcp", nil, 1, "Prefill context parallel groups.", vllmGroupParallel, ptrutil.Ptr(1), nil),
		boolFlag("enable-expert-parallel", "ep", nil, false, "Uses expert parallelism in MoE layers.", vllmGroupParallel),
		boolFlag("no-enable-expert-parallel", "", nil, false, "Disables expert parallelism in MoE layers.", vllmGroupParallel),
		boolFlag("enable-eplb", "", nil, false, "Enables expert-parallel load balancing.", vllmGroupParallel),
		boolFlag("no-enable-eplb", "", nil, false, "Disables EPLB.", vllmGroupParallel),
		strFlag("eplb-config", "", nil, nil, "EPLB configuration in JSON.", vllmGroupParallel, false),
		enumFlag("expert-placement-strategy", "", nil, []string{"linear", "round_robin"}, "linear", "MoE expert placement strategy.", vllmGroupParallel),
		enumFlag("all2all-backend", "", nil, []string{"allgather_reducescatter", "deepep_high_throughput", "deepep_low_latency", "deepep_v2", "flashinfer_all2allv", "flashinfer_nvlink_one_sided", "flashinfer_nvlink_two_sided", "mori", "mori_high_throughput", "mori_low_latency", "naive", "nixl_ep", "pplx"}, "allgather_reducescatter", "All2all communication backend for MoE expert parallelism; vLLM 0.20.x spells the MoRI backend \"mori\" and vLLM 0.23 or later splits it into mori_high_throughput and mori_low_latency. deepep_v2 requires vLLM 0.23 or later.", vllmGroupParallel),
		strFlag("distributed-executor-backend", "", nil, nil, "Distributed workers backend: mp, ray, uni, external_launcher, or a custom Executor class; None selects automatically.", vllmGroupParallel, false),
		boolFlag("disable-custom-all-reduce", "", nil, false, "Disables custom all-reduce and uses NCCL.", vllmGroupParallel),
		boolFlag("no-disable-custom-all-reduce", "", nil, false, "Allows custom all-reduce.", vllmGroupParallel),
		intFlag("nnodes", "n", nil, 1, "Number of nodes for multi-node mp.", vllmGroupParallel, ptrutil.Ptr(1), nil),
		intFlag("node-rank", "r", nil, 0, "Node rank.", vllmGroupParallel, ptrutil.Ptr(0), nil),
		strFlag("master-addr", "", nil, "127.0.0.1", "Master address for multi-node mp.", vllmGroupParallel, false),
		portFlag("master-port", "", 29501, "Master port for multi-node mp.", vllmGroupParallel),
		intFlag("max-parallel-loading-workers", "", nil, nil, "Parallel loading workers to avoid RAM OOM.", vllmGroupParallel, ptrutil.Ptr(1), nil),
		boolFlag("numa-bind", "", nil, false, "NUMA binding for GPU workers.", vllmGroupParallel),
		boolFlag("no-numa-bind", "", nil, false, "Disables NUMA binding.", vllmGroupParallel),
		strFlag("numa-bind-nodes", "", nil, nil, "List of NUMA nodes per GPU.", vllmGroupParallel, false),
		strFlag("numa-bind-cpus", "", nil, nil, "List of CPUs per GPU for NUMA binding.", vllmGroupParallel, false),
		boolFlag("enable-dbo", "", nil, false, "Enables Dual Batch Overlap.", vllmGroupParallel),
		boolFlag("no-enable-dbo", "", nil, false, "Disables Dual Batch Overlap.", vllmGroupParallel),
		intFlag("dbo-prefill-token-threshold", "", nil, 512, "Token threshold for DBO prefill microbatching.", vllmGroupParallel, ptrutil.Ptr(0), nil),
		intFlag("dbo-decode-token-threshold", "", nil, 32, "Token threshold for DBO decode microbatching.", vllmGroupParallel, ptrutil.Ptr(0), nil),
		strFlag("worker-cls", "", nil, "auto", "Worker class.", vllmGroupParallel, false),
		strFlag("worker-extension-cls", "", nil, "", "Worker extension class.", vllmGroupParallel, false),
		boolFlag("enable-elastic-ep", "", nil, false, "Enables elastic expert parallelism with stateless NCCL.", vllmGroupParallel),
		boolFlag("no-enable-elastic-ep", "", nil, false, "Disables elastic expert parallelism.", vllmGroupParallel),
		boolFlag("enable-ep-weight-filter", "", nil, false, "Each rank reads only its expert weights.", vllmGroupParallel),
		boolFlag("no-enable-ep-weight-filter", "", nil, false, "Each rank reads the normal set of expert weights.", vllmGroupParallel),
		intFlag("ubatch-size", "", nil, 0, "Ubatch size.", vllmGroupParallel, ptrutil.Ptr(0), nil),
		intFlag("cp-kv-cache-interleave-size", "", nil, 1, "KV interleave in DCP/PCP.", vllmGroupParallel, ptrutil.Ptr(0), nil),
		enumFlag("dcp-comm-backend", "", nil, []string{"ag_rs", "a2a"}, "ag_rs", "DCP communication backend.", vllmGroupParallel),
		intFlag("distributed-timeout-seconds", "", nil, nil, "Distributed operations timeout.", vllmGroupParallel, ptrutil.Ptr(1), nil),
		boolFlag("ray-workers-use-nsight", "", nil, false, "Ray worker profiling with nsight.", vllmGroupParallel),
		boolFlag("no-ray-workers-use-nsight", "", nil, false, "Disables nsight on Ray workers.", vllmGroupParallel),
		intFlag("cpu-distributed-timeout-seconds", "", nil, nil, "Timeout for CPU communication groups; None uses the PyTorch default. Requires vLLM 0.23 or later.", vllmGroupParallel, ptrutil.Ptr(1), nil),
		boolFlag("data-parallel-multi-port-external-lb", "dpm", nil, false, "Runs a node-local supervisor with one external-LB API server per local DP rank. Requires vLLM 0.23 or later.", vllmGroupParallel),
		intFlag("dcp-kv-cache-interleave-size", "", nil, 1, "Deprecated: replaced by cp-kv-cache-interleave-size.", vllmGroupParallel, ptrutil.Ptr(0), nil),
		boolFlagAuto("disable-nccl-for-dp-synchronization", "", nil, "Uses Gloo instead of NCCL for the DP synchronization all-reduce; unset lets the backend decide.", vllmGroupParallel),
		boolFlag("no-disable-nccl-for-dp-synchronization", "", nil, false, "Allows NCCL for the DP synchronization all-reduce.", vllmGroupParallel),
		strFlag("device-ids", "", nil, nil, "Comma-separated physical GPU device IDs or UUIDs to use, for example \"0,1\"; avoids CUDA_VISIBLE_DEVICES and keeps full GPU topology visible. No effect with Ray executors. Requires vLLM 0.23 or later.", vllmGroupParallel, false),
		boolFlag("enable-fault-tolerance", "", nil, false, "Enables fault tolerance for detailed error recovery, such as scaling down a faulted DPEngineCore; requires api-server-count 1. Requires vLLM 0.26.1 or later.", vllmGroupParallel),
		boolFlag("no-enable-fault-tolerance", "", nil, false, "Disables fault-tolerant error recovery. Requires vLLM 0.26.1 or later.", vllmGroupParallel),
		boolFlagAuto("dcp-q-replicate", "", nil, "Replicates the MLA query projection inside each decode-context-parallel group so decode can skip the query all-gather; unset lets the backend decide. Requires vLLM 0.28.1 or later.", vllmGroupParallel),
		boolFlag("no-dcp-q-replicate", "", nil, false, "Keeps the standard MLA decode query all-gather. Requires vLLM 0.28.1 or later.", vllmGroupParallel),
		boolFlagAuto("enable-batch-sharded-sampling", "", nil, "Shards sampling across tensor-parallel ranks so each rank samples a slice of the batch; requires tensor-parallel-size above 1, max-num-seqs at least tensor-parallel-size, and non-negative max-logprobs. Unset lets the backend decide. Requires vLLM 0.28.1 or later.", vllmGroupParallel),
		boolFlag("no-enable-batch-sharded-sampling", "", nil, false, "Every tensor-parallel rank samples the whole batch. Requires vLLM 0.28.1 or later.", vllmGroupParallel),

		floatFlag("gpu-memory-utilization", "", nil, 0.92, "Fraction of VRAM used by the engine.", vllmGroupKV, ptrutil.Ptr(0.0), ptrutil.Ptr(1.0)),
		strFlag("kv-cache-memory-bytes", "", nil, nil, "Fixed KV cache size per GPU; ignores the fraction.", vllmGroupKV, false),
		enumFlag("kv-cache-dtype", "", nil, []string{"auto", "bfloat16", "float16", "fp8", "fp8_ds_mla", "fp8_e4m3", "fp8_e5m2", "fp8_inc", "fp8_per_token_head", "int4_per_token_head", "int8_per_token_head", "nvfp4", "nvfp4_4over6", "turboquant_3bit_nc", "turboquant_4bit_nc", "turboquant_k3v4_nc", "turboquant_k8v4"}, "auto", "KV cache data type; nvfp4_4over6 requires vLLM 0.26.1 or later and int4_per_token_head requires vLLM 0.23 or later.", vllmGroupKV),
		strFlag("kv-cache-dtype-skip-layers", "", nil, "[]", "Layers or types that skip KV quantization.", vllmGroupKV, false),
		intFlag("block-size", "", nil, nil, "Tokens per cache block.", vllmGroupKV, ptrutil.Ptr(1), nil),
		boolFlagAuto("enable-prefix-caching", "", nil, "Reuses KV from already-processed prefixes; unset lets the backend decide, which enables it on supported models.", vllmGroupKV),
		boolFlag("no-enable-prefix-caching", "", nil, false, "Disables prefix caching.", vllmGroupKV),
		enumFlag("prefix-caching-hash-algo", "", nil, []string{"sha256", "sha256_cbor", "xxhash", "xxhash_cbor"}, "sha256", "Hash used in prefix caching.", vllmGroupKV),
		intFlag("num-gpu-blocks-override", "", nil, nil, "Overrides number of GPU blocks for preemption tests.", vllmGroupKV, ptrutil.Ptr(1), nil),
		floatFlag("kv-offloading-size", "", nil, nil, "KV offload buffer to CPU in GiB.", vllmGroupKV, ptrutil.Ptr(0.0), nil),
		enumFlag("kv-offloading-backend", "", nil, []string{"native", "lmcache"}, "native", "KV offload backend.", vllmGroupKV),
		intFlag("mamba-block-size", "", nil, nil, "Mamba cache block; multiple of 8.", vllmGroupKV, ptrutil.Ptr(1), nil),
		enumFlag("mamba-cache-dtype", "", nil, []string{"auto", "bfloat16", "float16", "float32"}, "auto", "Mamba cache dtype; bfloat16 requires vLLM 0.23 or later.", vllmGroupKV),
		enumFlag("mamba-ssm-cache-dtype", "", nil, []string{"auto", "bfloat16", "float16", "float32"}, "auto", "Mamba SSM state dtype; bfloat16 requires vLLM 0.23 or later.", vllmGroupKV),
		enumFlag("mamba-cache-mode", "", nil, []string{"none", "all", "align"}, "none", "Cache strategy for Mamba layers.", vllmGroupKV),
		boolFlag("calculate-kv-scales", "", nil, false, "Deprecated: dynamically calculates k/v_scale in fp8. Present but deprecation-warned through vLLM 0.27.1; removed in vLLM 0.28 and later.", vllmGroupKV),
		boolFlag("no-calculate-kv-scales", "", nil, false, "Disables dynamic calculation of fp8 KV scales. Removed in vLLM 0.28 and later.", vllmGroupKV),
		intFlag("prefix-cache-retention-interval", "", nil, nil, "Token interval between retained sliding-window and Mamba prefix-cache checkpoints; 0 retains only semantic checkpoints, a positive value must be a multiple of the scheduler block size, and unset retains checkpoints densely. Requires vLLM 0.28.1 or later.", vllmGroupKV, ptrutil.Ptr(0), nil),
		boolFlag("kv-sharing-fast-prefill", "", nil, false, "WIP prefill optimization in KV sharing.", vllmGroupKV),
		boolFlag("no-kv-sharing-fast-prefill", "", nil, false, "Disables fast prefill in KV sharing.", vllmGroupKV),
		floatFlag("watermark", "", nil, 0.0, "Fraction of total KV cache blocks kept free as headroom when admitting waiting or preempted requests; 0 disables the watermark. Requires vLLM 0.23 or later.", vllmGroupKV, ptrutil.Ptr(0.0), ptrutil.Ptr(1.0)),
		intFlag("prefix-match-unit", "", nil, nil, "Finest token boundary a prefix-cache hit can land on; every KV cache group block-size must be divisible by it. Requires vLLM 0.26 or later.", vllmGroupKV, ptrutil.Ptr(1), nil),
		boolFlag("use-replayssm", "", nil, false, "Uses the ReplaySSM Mamba2 decode kernel, caching recent SSM inputs instead of storing the full state each step; requires mamba-cache-mode none or align and the Triton mamba backend. Requires vLLM 0.26.1 or later.", vllmGroupKV),
		boolFlag("no-use-replayssm", "", nil, false, "Uses the standard Mamba2 decode kernel. Requires vLLM 0.26.1 or later.", vllmGroupKV),
		intFlag("replayssm-buffer-len", "", nil, 16, "ReplaySSM history ring-buffer length; the checkpoint state flushes to HBM every N steps. Requires vLLM 0.26.1 or later.", vllmGroupKV, ptrutil.Ptr(1), nil),

		floatFlag("cpu-offload-gb", "", nil, float64(0), "CPU weight offload space per GPU, in GiB.", vllmGroupWeightOffload, ptrutil.Ptr(0.0), nil),
		enumFlag("offload-backend", "", nil, []string{"auto", "uva", "prefetch"}, "auto", "Weight offload backend.", vllmGroupWeightOffload),
		strFlag("cpu-offload-params", "", nil, nil, "Parameter name segments to offload via UVA.", vllmGroupWeightOffload, false),
		intFlag("offload-group-size", "", nil, 0, "Groups every N layers for grouped offload.", vllmGroupWeightOffload, ptrutil.Ptr(0), nil),
		intFlag("offload-num-in-group", "", nil, 1, "Number of layers to offload per group.", vllmGroupWeightOffload, ptrutil.Ptr(1), nil),
		intFlag("offload-prefetch-step", "", nil, 1, "Layers to prefetch ahead.", vllmGroupWeightOffload, ptrutil.Ptr(0), nil),
		strFlag("offload-params", "", nil, nil, "Name segments for prefetch offloading.", vllmGroupWeightOffload, false),

		strFlag("limit-mm-per-prompt", "", nil, "{}", "Maximum items per modality per prompt.", vllmGroupMultimodal, false),
		boolFlag("language-model-only", "", nil, false, "Disables all multimodal inputs.", vllmGroupMultimodal),
		boolFlag("no-language-model-only", "", nil, false, "Allows multimodal inputs.", vllmGroupMultimodal),
		strFlag("mm-processor-kwargs", "", nil, nil, "Args for the model's multimodal processor.", vllmGroupMultimodal, false),
		enumFlag("mm-processor-device", "", nil, []string{"auto", "cpu", "cuda"}, "auto", "Device the HF multimodal processor runs image/video transforms on; only affects HF \"fast\" torchvision-backed processors. Requires vLLM 0.28 or later.", vllmGroupMultimodal),
		boolFlagAuto("mm-device-do-normalize", "", nil, "Moves do_normalize computation in multimodal preprocessing onto the device before the ViT, saving CPU work; unset lets the backend decide. Requires vLLM 0.28 or later.", vllmGroupMultimodal),
		boolFlag("no-mm-device-do-normalize", "", nil, false, "Keeps do_normalize computation on CPU. Requires vLLM 0.28 or later.", vllmGroupMultimodal),
		floatFlag("mm-processor-cache-gb", "", nil, float64(4), "Multimodal processor cache in GiB.", vllmGroupMultimodal, ptrutil.Ptr(0.0), nil),
		enumFlag("mm-processor-cache-type", "", nil, []string{"lru", "shm"}, "lru", "Multimodal processor cache type.", vllmGroupMultimodal),
		enumFlag("mm-hasher-algorithm", "", nil, []string{"blake3", "sha256", "sha512"}, "blake3", "Hash algorithm for multimodal input caching; use sha256 or sha512 for FIPS-compliant deployments. Requires vLLM 0.28 or later.", vllmGroupMultimodal),
		intFlag("mm-shm-cache-max-object-size-mb", "", nil, 128, "Per-object limit in shm cache, in MiB.", vllmGroupMultimodal, ptrutil.Ptr(0), nil),
		strFlag("media-io-kwargs", "", nil, "{}", "Media processing args, such as num_frames.", vllmGroupMultimodal, false),
		boolFlag("interleave-mm-strings", "", nil, false, "Fully interleaved multimodal prompts.", vllmGroupMultimodal),
		boolFlag("no-interleave-mm-strings", "", nil, false, "Disables full multimodal string interleaving.", vllmGroupMultimodal),
		boolFlag("enable-mm-embeds", "", nil, false, "Accepts multimodal embeddings as input.", vllmGroupMultimodal),
		boolFlag("no-enable-mm-embeds", "", nil, false, "Disables multimodal embeddings as input.", vllmGroupMultimodal),
		boolFlag("skip-mm-profiling", "", nil, false, "Skips multimodal memory profiling.", vllmGroupMultimodal),
		boolFlag("no-skip-mm-profiling", "", nil, false, "Runs multimodal memory profiling.", vllmGroupMultimodal),
		enumFlag("mm-encoder-tp-mode", "", nil, []string{"weights", "data"}, "weights", "How the multimodal encoder uses tensor parallelism.", vllmGroupMultimodal),
		strFlag("mm-encoder-attn-backend", "", nil, nil, "ViT encoder attention backend.", vllmGroupMultimodal, false),
		enumFlag("mm-encoder-attn-dtype", "", nil, []string{"fp8", "None"}, nil, "ViT encoder attention dtype.", vllmGroupMultimodal),
		strFlag("mm-encoder-fp8-scale-path", "", nil, nil, "Path to encoder FP8 scales.", vllmGroupMultimodal, false),
		strFlag("mm-encoder-fp8-scale-save-path", "", nil, nil, "Path to save encoder FP8 scales.", vllmGroupMultimodal, false),
		floatFlag("mm-encoder-fp8-scale-save-margin", "", nil, 1.5, "Encoder FP8 scales margin.", vllmGroupMultimodal, ptrutil.Ptr(0.0), nil),
		boolFlag("mm-encoder-only", "", nil, false, "Runs only the multimodal encoder and skips the LM.", vllmGroupMultimodal),
		boolFlag("no-mm-encoder-only", "", nil, false, "Runs multimodal encoder and LM.", vllmGroupMultimodal),
		enumFlag("mm-tensor-ipc", "", nil, []string{"direct_rpc", "torch_shm"}, "direct_rpc", "Multimodal tensor IPC method.", vllmGroupMultimodal),
		floatFlag("video-pruning-rate", "", nil, nil, "Fraction of video tokens pruned by EVS.", vllmGroupMultimodal, ptrutil.Ptr(0.0), ptrutil.Ptr(1.0)),
		floatFlag("mm-ipc-gpu-memory-gb", "", nil, 0.0, "GPU memory in GiB reserved on the engine device for GPU-side multimodal work in the API server process, such as hardware video decoding. Requires vLLM 0.23.1.dev968 or later.", vllmGroupMultimodal, ptrutil.Ptr(0.0), nil),
		enumFlag("video-pruning-method", "", nil, []string{"evs", "vidcom2"}, "evs", "Video token pruning algorithm used when video-pruning-rate is above 0: evs (Efficient Video Sampling) or vidcom2 (Video Compression Commander). Requires vLLM 0.28 or later.", vllmGroupMultimodal),

		boolFlagAuto("enable-lora", "", nil, "Enables LoRA adapters; unset lets the backend decide.", vllmGroupLora),
		boolFlag("no-enable-lora", "", nil, false, "Disables LoRA adapters.", vllmGroupLora),
		intFlag("max-loras", "", nil, 1, "Maximum LoRAs in a single batch.", vllmGroupLora, ptrutil.Ptr(1), nil),
		intFlag("max-lora-rank", "", nil, 16, "Maximum LoRA rank; allowed values: 1, 8, 16, 32, 64, 128, 256, 320, 512.", vllmGroupLora, ptrutil.Ptr(1), ptrutil.Ptr(512)),
		intFlag("max-cpu-loras", "", nil, nil, "Maximum LoRAs in RAM; must be >= max_loras.", vllmGroupLora, ptrutil.Ptr(1), nil),
		enumFlag("lora-dtype", "", nil, []string{"auto", "float16", "bfloat16"}, "auto", "LoRAs dtype.", vllmGroupLora),
		strFlag("lora-target-modules", "", nil, nil, "Restricts LoRA to module suffixes.", vllmGroupLora, false),
		boolFlag("fully-sharded-loras", "", nil, false, "LoRA layers fully sharded by TP.", vllmGroupLora),
		boolFlag("no-fully-sharded-loras", "", nil, false, "Uses LoRA without full TP sharding.", vllmGroupLora),
		strFlag("default-mm-loras", "", nil, nil, "Maps modalities to LoRA paths.", vllmGroupLora, false),
		boolFlag("enable-tower-connector-lora", "", nil, false, "Enables LoRA in multimodal model encoder/connector.", vllmGroupLora),
		boolFlag("no-enable-tower-connector-lora", "", nil, false, "Disables LoRA in multimodal encoder/connector.", vllmGroupLora),
		boolFlag("specialize-active-lora", "", nil, false, "CUDA graphs by active LoRAs count.", vllmGroupLora),
		boolFlag("no-specialize-active-lora", "", nil, false, "Disables CUDA graph specialization by active LoRAs.", vllmGroupLora),
		boolFlag("enable-mixed-moe-lora-format", "", nil, false, "Forces the universal 2D MoE LoRA wrapper so 2D and 3D MoE LoRA adapters can be served together. Requires vLLM 0.23 or later.", vllmGroupLora),
		boolFlag("no-enable-mixed-moe-lora-format", "", nil, false, "Keeps model-driven MoE LoRA format selection. Requires vLLM 0.23 or later.", vllmGroupLora),
		boolFlag("enable-moe-shared-loras", "", nil, false, "Loads MoE expert adapters in the shared-outer layout, sharing the gate/up lora_A and down lora_B across all experts instead of storing them per expert. Requires vLLM 0.26 or later.", vllmGroupLora),
		boolFlag("no-enable-moe-shared-loras", "", nil, false, "Loads MoE expert adapters per expert. Requires vLLM 0.26 or later.", vllmGroupLora),

		strFlag("otlp-traces-endpoint", "", nil, nil, "OpenTelemetry endpoint for traces.", vllmGroupObservability, false),
		enumFlag("collect-detailed-traces", "", nil, []string{"all", "model", "worker", "None", "model,worker", "model,all", "worker,model", "worker,all", "all,model", "all,worker"}, nil, "Detailed traces by module.", vllmGroupObservability),
		strFlag("show-hidden-metrics-for-version", "", nil, nil, "Re-enables Prometheus metrics deprecated in one version.", vllmGroupObservability, false),
		boolFlag("enable-server-load-tracking", "", nil, false, "Tracks server load.", vllmGroupObservability),
		boolFlag("no-enable-server-load-tracking", "", nil, false, "Disables server load tracking.", vllmGroupObservability),
		boolFlag("cudagraph-metrics", "", nil, false, "CUDA graph metrics.", vllmGroupObservability),
		boolFlag("no-cudagraph-metrics", "", nil, false, "Disables CUDA graph metrics.", vllmGroupObservability),
		boolFlag("kv-cache-metrics", "", nil, false, "KV cache residency metrics.", vllmGroupObservability),
		boolFlag("no-kv-cache-metrics", "", nil, false, "Disables KV cache metrics.", vllmGroupObservability),
		floatFlag("kv-cache-metrics-sample", "", nil, 0.01, "Sampling rate for KV cache metrics.", vllmGroupObservability, ptrutil.Ptr(0.0), ptrutil.Ptr(1.0)),
		boolFlag("enable-mfu-metrics", "", nil, false, "Enables Model FLOPs Utilization metrics.", vllmGroupObservability),
		boolFlag("no-enable-mfu-metrics", "", nil, false, "Disables MFU metrics.", vllmGroupObservability),
		boolFlag("enable-layerwise-nvtx-tracing", "", nil, false, "Layer-wise NVTX tracing.", vllmGroupObservability),
		boolFlag("no-enable-layerwise-nvtx-tracing", "", nil, false, "Disables per-layer NVTX tracing.", vllmGroupObservability),
		boolFlag("enable-logging-iteration-details", "", nil, false, "Logs details per iteration.", vllmGroupObservability),
		boolFlag("no-enable-logging-iteration-details", "", nil, false, "Disables detailed logs per iteration.", vllmGroupObservability),
		boolFlag("jit-monitor-verbose", "", nil, false, "Logs every Triton JIT compile with its dispatch key; verbose, for debugging. Requires vLLM 0.23 or later.", vllmGroupObservability),
		boolFlag("no-jit-monitor-verbose", "", nil, false, "Disables verbose Triton JIT compile logging. Requires vLLM 0.23 or later.", vllmGroupObservability),
		enumFlag("jit-monitor-mode", "", nil, []string{"warn", "error"}, "warn", "How to handle post-warmup Triton JIT compilation events. Requires vLLM 0.23 or later.", vllmGroupObservability),
		boolFlag("enable-per-request-metrics", "", nil, false, "Includes per-request timing metrics in API responses. Requires vLLM 0.23.1.dev968 or later.", vllmGroupObservability),
		boolFlag("no-enable-per-request-metrics", "", nil, false, "Omits per-request timing metrics from API responses. Requires vLLM 0.23.1.dev968 or later.", vllmGroupObservability),
		enumFlag("per-request-spec-decode-metrics", "", nil, []string{"none", "summary", "detailed"}, "none", "Per-request speculative-decoding acceptance metrics in the response body: summary adds mean acceptance length, draft acceptance rate and the step histogram; detailed adds the ordered per-step accepted/proposed arrays. Only reported for n == 1 requests and only when speculative decoding is enabled. Requires vLLM 0.28.1 or later.", vllmGroupObservability),

		strFlag("max-num-batched-tokens", "", nil, nil, "Maximum tokens per iteration; accepts integer or 1k.", vllmGroupScheduler, false),
		intFlag("max-num-seqs", "", nil, nil, "Maximum sequences per iteration.", vllmGroupScheduler, ptrutil.Ptr(1), nil),
		boolFlagAuto("enable-chunked-prefill", "", nil, "Chunks long prefills; unset lets the backend decide.", vllmGroupScheduler),
		boolFlag("no-enable-chunked-prefill", "", nil, false, "Disables chunked prefill.", vllmGroupScheduler),
		intFlag("long-prefill-token-threshold", "", nil, 0, "Token count at which a prompt is considered long.", vllmGroupScheduler, ptrutil.Ptr(0), nil),
		intFlag("max-num-partial-prefills", "", nil, 1, "Concurrent partial prefills; removed in vLLM 0.26.1 and later.", vllmGroupScheduler, ptrutil.Ptr(1), nil),
		intFlag("max-long-partial-prefills", "", nil, 1, "Long prompts prefilled concurrently; removed in vLLM 0.26.1 and later.", vllmGroupScheduler, ptrutil.Ptr(1), nil),
		enumFlag("scheduling-policy", "", nil, []string{"fcfs", "priority"}, "fcfs", "Scheduling policy.", vllmGroupScheduler),
		boolFlagAuto("async-scheduling", "", nil, "Asynchronous scheduling; unset lets the backend decide.", vllmGroupScheduler),
		boolFlag("no-async-scheduling", "", nil, false, "Disables asynchronous scheduling.", vllmGroupScheduler),
		boolFlag("scheduler-reserve-full-isl", "", nil, true, "Reserves the full ISL before admitting requests.", vllmGroupScheduler),
		boolFlag("no-scheduler-reserve-full-isl", "", nil, false, "Does not reserve full ISL before admitting.", vllmGroupScheduler),
		boolFlag("disable-chunked-mm-input", "", nil, false, "Does not slice multimodal item in chunked prefill.", vllmGroupScheduler),
		boolFlag("no-disable-chunked-mm-input", "", nil, false, "Allows slicing multimodal item in chunked prefill.", vllmGroupScheduler),
		strFlag("scheduler-cls", "", nil, nil, "Custom scheduler class; default uses vllm.v1.core.sched.scheduler.Scheduler.", vllmGroupScheduler, false),
		intFlag("stream-interval", "", nil, 1, "Streaming interval in tokens.", vllmGroupScheduler, ptrutil.Ptr(1), nil),
		boolFlagAuto("disable-hybrid-kv-cache-manager", "", nil, "Allocates the same KV cache size for all attention layer types; unset lets the backend decide.", vllmGroupScheduler),
		boolFlag("no-disable-hybrid-kv-cache-manager", "", nil, false, "Keeps the hybrid KV cache manager enabled.", vllmGroupScheduler),
		intFlag("prefill-schedule-interval", "", nil, 1, "For data-parallel deployments, admit new prefill requests only every N engine steps (aligned across DP ranks) to balance per-step forward-pass times. Requires vLLM 0.23 or later.", vllmGroupScheduler, ptrutil.Ptr(1), nil),
		strFlag("max-num-scheduled-tokens", "", nil, nil, "Maximum tokens the scheduler may issue in a single iteration; accepts integer or 1k. Defaults to max-num-batched-tokens. Requires vLLM 0.23.1.dev968 or later.", vllmGroupScheduler, false),

		strFlag("compilation-config", "cc", nil, nil, "torch.compile and CUDA graphs config in JSON.", vllmGroupCompilation, false),
		intFlag("optimization-level", "O", nil, 2, "Optimization level; 0 prioritizes startup, 3 performance.", vllmGroupCompilation, ptrutil.Ptr(0), ptrutil.Ptr(3)),
		enumFlag("performance-mode", "", nil, []string{"balanced", "interactivity", "throughput"}, "balanced", "Runtime profile.", vllmGroupCompilation),
		strFlag("cudagraph-capture-sizes", "", nil, nil, "Batch sizes captured in CUDA graph.", vllmGroupCompilation, false),
		intFlag("max-cudagraph-capture-size", "", nil, nil, "Largest CUDA graph capture size.", vllmGroupCompilation, ptrutil.Ptr(1), nil),

		enumFlag("moe-backend", "", nil, []string{"auto", "aiter", "batched_triton", "cutlass", "deep_gemm", "deep_gemm_mega_moe", "emulation", "flashinfer_b12x", "flashinfer_cutedsl", "flashinfer_cutlass", "flashinfer_trtllm", "flydsl", "hpc", "humming", "marlin", "triton", "triton_unfused"}, "auto", "MoE kernels backend; auto chooses based on model/hardware. batched_triton requires vLLM 0.26.1 or later, and flydsl and hpc are not accepted by every supported build.", vllmGroupKernels),
		boolFlagAuto("enable-flashinfer-autotune", "", nil, "FlashInfer autotuning during warmup; unset lets the backend decide.", vllmGroupKernels),
		boolFlag("no-enable-flashinfer-autotune", "", nil, false, "Disables FlashInfer autotuning.", vllmGroupKernels),
		strFlag("ir-op-priority", "", nil, nil, "vLLM IR op priority in forward.", vllmGroupKernels, false),
		strFlag("kernel-config", "", nil, nil, "Consolidated kernels config in JSON.", vllmGroupKernels, false),
		enumFlag("linear-backend", "", nil, []string{"auto", "aiter", "conch", "cutlass", "deep_gemm", "emulation", "exllama", "fbgemm", "flashinfer_b12x", "flashinfer_cudnn", "flashinfer_cutedsl", "flashinfer_cutlass", "flashinfer_trtllm", "humming", "machete", "marlin", "torch", "triton", "xpu", "xpu_woq"}, "auto", "Backend for quantized linear layer GEMM kernels. Requires vLLM 0.23 or later; humming, xpu and xpu_woq are not accepted by every supported build.", vllmGroupKernels),
		boolFlag("enable-bf16x3-router-gemm", "", nil, false, "Uses the experimental SM100 BF16x3 CuteDSL router GEMM. Requires vLLM 0.26 or later.", vllmGroupKernels),
		boolFlag("no-enable-bf16x3-router-gemm", "", nil, false, "Uses the standard router GEMM. Requires vLLM 0.26 or later.", vllmGroupKernels),

		strFlag("speculative-config", "sc", nil, nil, "Speculative decoding configuration in JSON.", vllmGroupAdvancedConfigs, false),
		enumFlag("spec-method", "", nil, []string{"bailing_hybrid_mtp", "bailing_hybrid_v3_mtp", "custom_class", "deepseek_mtp", "dflash", "draft_model", "dspark", "eagle", "eagle3", "ernie_mtp", "exaone4_5_mtp", "exaone_moe_mtp", "extract_hidden_states", "gemma4_mtp", "glm4_moe_lite_mtp", "glm4_moe_mtp", "glm_ocr_mtp", "hy_v3_mtp", "inkling_mtp", "kimi_k3_mtp", "longcat_flash_mtp", "medusa", "mimo_mtp", "mimo_v2_mtp", "minimax_m3_mtp", "mlp_speculator", "mtp", "nemotron_h_mtp", "ngram", "ngram_gpu", "pangu_ultra_moe_mtp", "qwen3_5_mtp", "qwen3_next_mtp", "step3p5_mtp", "suffix", "None"}, nil, "Speculative decoding method; auto-detected from spec-model when possible. Requires vLLM 0.23 or later; on older builds pass the method inside speculative-config instead. bailing_hybrid_v3_mtp and kimi_k3_mtp require vLLM 0.26.1 or later, and bailing_hybrid_mtp, dspark, inkling_mtp and minimax_m3_mtp are not accepted by every supported build.", vllmGroupAdvancedConfigs),
		strFlag("spec-model", "", nil, nil, "Draft model, eagle head, or additional weights for speculative decoding. Requires vLLM 0.23 or later.", vllmGroupAdvancedConfigs, false),
		intFlag("spec-tokens", "", nil, nil, "Number of speculative tokens; defaults from the draft model config. Requires vLLM 0.23 or later.", vllmGroupAdvancedConfigs, ptrutil.Ptr(1), nil),
		strFlag("kv-transfer-config", "", nil, nil, "Distributed KV cache transfer for disaggregated prefill/decode.", vllmGroupAdvancedConfigs, false),
		strFlag("kv-events-config", "", nil, nil, "KV cache event publishing.", vllmGroupAdvancedConfigs, false),
		strFlag("ec-transfer-config", "", nil, nil, "Distributed EC cache transfer.", vllmGroupAdvancedConfigs, false),
		strFlag("weight-transfer-config", "", nil, nil, "Weight transfer during RL training.", vllmGroupAdvancedConfigs, false),
		strFlag("reasoning-config", "", nil, nil, "Reasoning model config.", vllmGroupAdvancedConfigs, false),
		strFlag("diffusion-config", "dc", nil, nil, "Diffusion LLM (dLLM) configuration in JSON; used by block-diffusion models such as DiffusionGemma. Requires vLLM 0.23 or later.", vllmGroupAdvancedConfigs, false),
		strFlag("attention-config", "ac", nil, nil, "Detailed attention config and backend overrides.", vllmGroupAdvancedConfigs, false),
		strFlag("profiler-config", "", nil, nil, "Profiling config with torch profiler.", vllmGroupAdvancedConfigs, false),
		strFlag("additional-config", "", nil, "{}", "Additional platform-specific config.", vllmGroupAdvancedConfigs, false),
		strFlag("fault-tolerance-config", "", nil, nil, "Fault tolerance configuration in JSON, such as engine_recovery_timeout_sec. Requires vLLM 0.26.1 or later.", vllmGroupAdvancedConfigs, false),
	} {
		add(spec)
	}

	return domain.BackendValidationSchema{
		SchemaVersion: 1,
		Kind:          domain.ValidationSchemaCLIFlagsV1,
		BackendKind:   domain.BackendKindVLLM,
		BackendID:     "vllm-default",
		Source: domain.SchemaSource{
			GeneratedFrom: "vLLM serve CLI argument declarations, union of vLLM 0.20.2 through 0.28.1rc1.dev118+g87b9b5b8d",
			SourceVersion: "curated-vllm-union-0.20.2-0.28.1rc1.dev118+g87b9b5b8d",
			Editable:      true,
		},
		Flags:        flags,
		Presentation: vllmPresentation(),
	}
}

func vllmPresentation() *domain.Presentation {
	return &domain.Presentation{Groups: []domain.PresentationGroup{
		{Name: vllmGroupEssentials, Highlighted: true, Flags: []string{"host", "port", "api-key", "served-model-name", "dtype", "max-model-len", "quantization", "tensor-parallel-size", "device-ids", "gpu-memory-utilization", "kv-cache-dtype", "attention-backend", "enable-prefix-caching", "max-num-batched-tokens", "max-num-seqs", "enable-chunked-prefill", "performance-mode", "speculative-config", "uvicorn-log-level"}},
		{Name: vllmGroupServer, Flags: []string{"config", "api-server-count", "headless", "grpc", "disable-log-stats", "enable-log-requests", "no-enable-log-requests", "aggregate-engine-logging", "shutdown-timeout", "gdn-prefill-backend", "kda-prefill-backend", "fail-on-environ-validation", "no-fail-on-environ-validation"}},
		{Name: vllmGroupFrontend, Flags: []string{"host", "port", "uds", "api-key", "root-path", "allowed-origins", "allowed-methods", "allowed-headers", "allow-credentials", "no-allow-credentials", "ssl-certfile", "ssl-keyfile", "ssl-ca-certs", "ssl-cert-reqs", "ssl-ciphers", "enable-ssl-refresh", "no-enable-ssl-refresh", "chat-template", "chat-template-content-format", "default-chat-template-kwargs", "response-role", "enable-auto-tool-choice", "no-enable-auto-tool-choice", "tool-call-parser", "tool-parser-plugin", "reasoning-parser", "lora-modules", "max-log-len", "enable-request-id-headers", "no-enable-request-id-headers", "disable-fastapi-docs", "no-disable-fastapi-docs", "enable-offline-docs", "no-enable-offline-docs", "disable-uvicorn-access-log", "no-disable-uvicorn-access-log", "disable-access-log-for-endpoints", "uvicorn-log-level", "middleware", "return-tokens-as-token-ids", "no-return-tokens-as-token-ids", "enable-prompt-tokens-details", "no-enable-prompt-tokens-details", "enable-force-include-usage", "no-enable-force-include-usage", "h11-max-header-count", "h11-max-incomplete-event-size", "data-parallel-supervisor-port", "dp-supervisor-probe-failure-threshold", "dp-supervisor-probe-interval-s", "dp-supervisor-probe-timeout-s", "enable-flash-late-interaction", "no-enable-flash-late-interaction", "enable-log-deltas", "no-enable-log-deltas", "enable-log-outputs", "no-enable-log-outputs", "enable-tokenizer-info-endpoint", "no-enable-tokenizer-info-endpoint", "exclude-tools-when-tool-choice-none", "no-exclude-tools-when-tool-choice-none", "fingerprint-mode", "fingerprint-value", "log-config-file", "log-error-stack", "no-log-error-stack", "tokens-only", "no-tokens-only", "tool-server", "sse-keep-alive-interval", "trust-request-chat-template", "no-trust-request-chat-template", "cohere-is-reasoning-model", "no-cohere-is-reasoning-model", "cohere-format"}},
		{Name: vllmGroupModel, Flags: []string{"served-model-name", "tokenizer", "tokenizer-mode", "revision", "code-revision", "tokenizer-revision", "dtype", "max-model-len", "quantization", "seed", "trust-remote-code", "no-trust-remote-code", "hf-token", "hf-overrides", "hf-config-path", "config-format", "model-impl", "runner", "convert", "enforce-eager", "no-enforce-eager", "enable-sleep-mode", "no-enable-sleep-mode", "disable-sliding-window", "no-disable-sliding-window", "disable-cascade-attn", "no-disable-cascade-attn", "max-logprobs", "logprobs-mode", "generation-config", "override-generation-config", "enable-prompt-embeds", "no-enable-prompt-embeds", "skip-tokenizer-init", "no-skip-tokenizer-init", "pooler-config", "allowed-local-media-path", "allowed-media-domains", "renderer-num-workers", "logits-processors", "override-attention-dtype", "return-sampling-mask", "no-return-sampling-mask", "enable-trace-replay", "no-enable-trace-replay", "io-processor-plugin", "allow-deprecated-quantization", "no-allow-deprecated-quantization", "enable-cumem-allocator", "no-enable-cumem-allocator", "enable-return-routed-experts", "no-enable-return-routed-experts", "use-fp64-gumbel", "no-use-fp64-gumbel", "quantization-config", "model-class-overrides"}},
		{Name: vllmGroupLoad, Flags: []string{"load-format", "download-dir", "ignore-patterns", "model-loader-extra-config", "safetensors-load-strategy", "safetensors-prefetch-block-size", "safetensors-prefetch-num-threads", "pt-load-map-location", "use-tqdm-on-load", "no-use-tqdm-on-load"}},
		{Name: vllmGroupAttention, Flags: []string{"attention-backend", "mamba-backend", "mamba-ssu-algorithm", "enable-mamba-cache-stochastic-rounding", "no-enable-mamba-cache-stochastic-rounding", "mamba-cache-philox-rounds"}},
		{Name: vllmGroupStructured, Flags: []string{"reasoning-parser", "reasoning-parser-plugin", "structured-outputs-config"}},
		{Name: vllmGroupParallel, Flags: []string{"tensor-parallel-size", "pipeline-parallel-size", "data-parallel-size", "data-parallel-size-local", "data-parallel-rank", "data-parallel-start-rank", "data-parallel-address", "data-parallel-rpc-port", "data-parallel-backend", "data-parallel-external-lb", "no-data-parallel-external-lb", "data-parallel-hybrid-lb", "no-data-parallel-hybrid-lb", "decode-context-parallel-size", "prefill-context-parallel-size", "enable-expert-parallel", "no-enable-expert-parallel", "enable-eplb", "no-enable-eplb", "eplb-config", "expert-placement-strategy", "all2all-backend", "distributed-executor-backend", "disable-custom-all-reduce", "no-disable-custom-all-reduce", "nnodes", "node-rank", "master-addr", "master-port", "max-parallel-loading-workers", "numa-bind", "no-numa-bind", "numa-bind-nodes", "numa-bind-cpus", "enable-dbo", "no-enable-dbo", "dbo-prefill-token-threshold", "dbo-decode-token-threshold", "worker-cls", "worker-extension-cls", "enable-elastic-ep", "no-enable-elastic-ep", "enable-ep-weight-filter", "no-enable-ep-weight-filter", "ubatch-size", "cp-kv-cache-interleave-size", "dcp-comm-backend", "distributed-timeout-seconds", "ray-workers-use-nsight", "no-ray-workers-use-nsight", "cpu-distributed-timeout-seconds", "data-parallel-multi-port-external-lb", "dcp-kv-cache-interleave-size", "disable-nccl-for-dp-synchronization", "no-disable-nccl-for-dp-synchronization", "device-ids", "enable-fault-tolerance", "no-enable-fault-tolerance", "dcp-q-replicate", "no-dcp-q-replicate", "enable-batch-sharded-sampling", "no-enable-batch-sharded-sampling"}},
		{Name: vllmGroupKV, Flags: []string{"gpu-memory-utilization", "kv-cache-memory-bytes", "kv-cache-dtype", "kv-cache-dtype-skip-layers", "block-size", "enable-prefix-caching", "no-enable-prefix-caching", "prefix-caching-hash-algo", "num-gpu-blocks-override", "kv-offloading-size", "kv-offloading-backend", "mamba-block-size", "mamba-cache-dtype", "mamba-ssm-cache-dtype", "mamba-cache-mode", "calculate-kv-scales", "no-calculate-kv-scales", "prefix-cache-retention-interval", "kv-sharing-fast-prefill", "no-kv-sharing-fast-prefill", "watermark", "prefix-match-unit", "use-replayssm", "no-use-replayssm", "replayssm-buffer-len"}},
		{Name: vllmGroupWeightOffload, Flags: []string{"cpu-offload-gb", "offload-backend", "cpu-offload-params", "offload-group-size", "offload-num-in-group", "offload-prefetch-step", "offload-params"}},
		{Name: vllmGroupMultimodal, Flags: []string{"limit-mm-per-prompt", "language-model-only", "no-language-model-only", "mm-processor-kwargs", "mm-processor-device", "no-mm-device-do-normalize", "mm-device-do-normalize", "mm-processor-cache-gb", "mm-processor-cache-type", "mm-hasher-algorithm", "mm-shm-cache-max-object-size-mb", "media-io-kwargs", "interleave-mm-strings", "no-interleave-mm-strings", "enable-mm-embeds", "no-enable-mm-embeds", "skip-mm-profiling", "no-skip-mm-profiling", "mm-encoder-tp-mode", "mm-encoder-attn-backend", "mm-encoder-attn-dtype", "mm-encoder-fp8-scale-path", "mm-encoder-fp8-scale-save-path", "mm-encoder-fp8-scale-save-margin", "mm-encoder-only", "no-mm-encoder-only", "mm-tensor-ipc", "video-pruning-rate", "mm-ipc-gpu-memory-gb", "video-pruning-method"}},
		{Name: vllmGroupLora, Flags: []string{"enable-lora", "no-enable-lora", "max-loras", "max-lora-rank", "max-cpu-loras", "lora-dtype", "lora-target-modules", "fully-sharded-loras", "no-fully-sharded-loras", "default-mm-loras", "enable-tower-connector-lora", "no-enable-tower-connector-lora", "specialize-active-lora", "no-specialize-active-lora", "enable-mixed-moe-lora-format", "no-enable-mixed-moe-lora-format", "enable-moe-shared-loras", "no-enable-moe-shared-loras"}},
		{Name: vllmGroupObservability, Flags: []string{"otlp-traces-endpoint", "collect-detailed-traces", "show-hidden-metrics-for-version", "enable-server-load-tracking", "no-enable-server-load-tracking", "cudagraph-metrics", "no-cudagraph-metrics", "kv-cache-metrics", "no-kv-cache-metrics", "kv-cache-metrics-sample", "enable-mfu-metrics", "no-enable-mfu-metrics", "enable-layerwise-nvtx-tracing", "no-enable-layerwise-nvtx-tracing", "enable-logging-iteration-details", "no-enable-logging-iteration-details", "jit-monitor-verbose", "no-jit-monitor-verbose", "jit-monitor-mode", "enable-per-request-metrics", "no-enable-per-request-metrics", "per-request-spec-decode-metrics"}},
		{Name: vllmGroupScheduler, Flags: []string{"max-num-batched-tokens", "max-num-seqs", "enable-chunked-prefill", "no-enable-chunked-prefill", "long-prefill-token-threshold", "max-num-partial-prefills", "max-long-partial-prefills", "scheduling-policy", "async-scheduling", "no-async-scheduling", "scheduler-reserve-full-isl", "no-scheduler-reserve-full-isl", "disable-chunked-mm-input", "no-disable-chunked-mm-input", "scheduler-cls", "stream-interval", "disable-hybrid-kv-cache-manager", "no-disable-hybrid-kv-cache-manager", "prefill-schedule-interval", "max-num-scheduled-tokens"}},
		{Name: vllmGroupCompilation, Flags: []string{"compilation-config", "optimization-level", "performance-mode", "cudagraph-capture-sizes", "max-cudagraph-capture-size"}},
		{Name: vllmGroupKernels, Flags: []string{"moe-backend", "enable-flashinfer-autotune", "no-enable-flashinfer-autotune", "ir-op-priority", "kernel-config", "linear-backend", "enable-bf16x3-router-gemm", "no-enable-bf16x3-router-gemm"}},
		{Name: vllmGroupAdvancedConfigs, Flags: []string{"speculative-config", "kv-transfer-config", "kv-events-config", "ec-transfer-config", "weight-transfer-config", "reasoning-config", "diffusion-config", "attention-config", "profiler-config", "additional-config", "spec-method", "spec-model", "spec-tokens", "fault-tolerance-config"}},
	}}
}
