package backendschema

import "github.com/quantmind-br/model-loader/internal/domain"

const (
	vllmGroupEssentials      = "Essentials"
	vllmGroupServer          = "1. Server and General"
	vllmGroupFrontend        = "2. Frontend (OpenAI API)"
	vllmGroupModel           = "3. Model (ModelConfig)"
	vllmGroupLoad            = "4. Weight Loading (LoadConfig)"
	vllmGroupAttention       = "5. Attention and Mamba"
	vllmGroupStructured      = "6. Structured Outputs and Reasoning"
	vllmGroupParallel        = "7. Parallelism and Distributed Execution"
	vllmGroupKV              = "8. KV Cache"
	vllmGroupWeightOffload   = "9. Weight Offloading"
	vllmGroupMultimodal      = "10. Multimodal"
	vllmGroupLora            = "11. LoRA"
	vllmGroupObservability   = "12. Observability and Metrics"
	vllmGroupScheduler       = "13. Scheduler"
	vllmGroupCompilation     = "14. Compilation and CUDA Graphs"
	vllmGroupKernels         = "15. Kernels and MoE"
	vllmGroupAdvancedConfigs = "16. Advanced Configs (VllmConfig)"
)

// CuratedVLLMSchema returns the hand-curated vLLM serve schema based on
// docs/model-loader/vllm.md. The profile model field is handled separately,
// so positional model_tag and --model are intentionally omitted.
func CuratedVLLMSchema() domain.BackendValidationSchema {
	flags := map[string]domain.FlagSpec{}
	add := func(spec domain.FlagSpec) {
		flags[spec.Long] = spec
	}

	for _, spec := range []domain.FlagSpec{
		strFlag("config", "", nil, nil, "Reads CLI options from a YAML file.", vllmGroupServer, false),
		intFlag("api-server-count", "asc", nil, nil, "Number of API server processes to run; default follows data_parallel_size.", vllmGroupServer, intPtr(1), nil),
		boolFlag("headless", "", nil, false, "Runs without an HTTP frontend on secondary nodes in multi-node data parallel mode.", vllmGroupServer),
		boolFlag("grpc", "", nil, false, "Starts a gRPC server instead of OpenAI HTTP; requires vllm[grpc].", vllmGroupServer),
		boolFlag("disable-log-stats", "", nil, false, "Disables statistics logging.", vllmGroupServer),
		boolFlag("enable-log-requests", "", nil, false, "Logs request information; DEBUG may include prompts.", vllmGroupServer),
		boolFlag("no-enable-log-requests", "", nil, false, "Explicitly disables request logging.", vllmGroupServer),
		boolFlag("aggregate-engine-logging", "", nil, false, "Logs aggregated statistics in data parallelism.", vllmGroupServer),
		intFlag("shutdown-timeout", "", nil, 0, "Shutdown timeout in seconds; 0 aborts immediately.", vllmGroupServer, intPtr(0), nil),
		enumFlag("gdn-prefill-backend", "", nil, []string{"flashinfer", "triton"}, nil, "Selects the GDN prefill backend.", vllmGroupServer),
		boolFlag("fail-on-environ-validation", "", nil, false, "Fatal error if environment validation fails.", vllmGroupServer),
		boolFlag("no-fail-on-environ-validation", "", nil, false, "Ignores non-fatal environment validation failures.", vllmGroupServer),

		strFlag("host", "", nil, nil, "Listen address; None listens on all interfaces.", vllmGroupFrontend, false),
		portFlag("port", "", 8000, "HTTP server port.", vllmGroupFrontend),
		strFlag("uds", "", nil, nil, "Unix domain socket; ignores host/port when set.", vllmGroupFrontend, false),
		strFlag("api-key", "", nil, nil, "Requires one of the keys in the request header.", vllmGroupFrontend, false),
		strFlag("root-path", "", nil, nil, "FastAPI root_path behind a path-routing proxy.", vllmGroupFrontend, false),
		strFlag("allowed-origins", "", nil, "['*']", "Origins allowed by CORS.", vllmGroupFrontend, false),
		strFlag("allowed-methods", "", nil, "['*']", "Methods allowed by CORS.", vllmGroupFrontend, false),
		strFlag("allowed-headers", "", nil, "['*']", "Headers allowed by CORS.", vllmGroupFrontend, false),
		boolFlag("allow-credentials", "", nil, false, "Allows CORS credentials.", vllmGroupFrontend),
		boolFlag("no-allow-credentials", "", nil, false, "Disables CORS credentials.", vllmGroupFrontend),
		strFlag("ssl-certfile", "", nil, nil, "SSL certificate.", vllmGroupFrontend, false),
		strFlag("ssl-keyfile", "", nil, nil, "SSL key.", vllmGroupFrontend, false),
		strFlag("ssl-ca-certs", "", nil, nil, "CA file for SSL.", vllmGroupFrontend, false),
		intFlag("ssl-cert-reqs", "", nil, 0, "Requires client certificate according to stdlib ssl.", vllmGroupFrontend, intPtr(0), nil),
		strFlag("ssl-ciphers", "", nil, nil, "TLS 1.2 and below ciphers.", vllmGroupFrontend, false),
		boolFlag("enable-ssl-refresh", "", nil, false, "Reloads SSL context when files change.", vllmGroupFrontend),
		boolFlag("no-enable-ssl-refresh", "", nil, false, "Disables automatic SSL context reload.", vllmGroupFrontend),
		strFlag("chat-template", "", nil, nil, "Custom chat template or file.", vllmGroupFrontend, false),
		enumFlag("chat-template-content-format", "", nil, []string{"auto", "openai", "string"}, "auto", "Content format in the template.", vllmGroupFrontend),
		strFlag("default-chat-template-kwargs", "", nil, nil, "Default JSON arguments for the template.", vllmGroupFrontend, false),
		strFlag("response-role", "", nil, "assistant", "Role assigned to the response.", vllmGroupFrontend, false),
		boolFlag("enable-auto-tool-choice", "", nil, false, "Enables automatic tool choice.", vllmGroupFrontend),
		boolFlag("no-enable-auto-tool-choice", "", nil, false, "Disables automatic tool choice.", vllmGroupFrontend),
		strFlag("tool-call-parser", "", nil, nil, "Tool-call parser for the model.", vllmGroupFrontend, false),
		strFlag("tool-parser-plugin", "", nil, nil, "Tool parser plugin.", vllmGroupFrontend, false),
		strFlag("reasoning-parser", "", nil, "", "Reasoning-content parser in OpenAI format.", vllmGroupFrontend, false),
		strFlag("lora-modules", "", nil, nil, "Defines LoRA modules exposed in the API.", vllmGroupFrontend, false),
		intFlag("max-log-len", "", nil, nil, "Truncates prompt and output logs.", vllmGroupFrontend, intPtr(0), nil),
		boolFlag("enable-request-id-headers", "", nil, false, "Adds X-Request-Id to responses.", vllmGroupFrontend),
		boolFlag("no-enable-request-id-headers", "", nil, false, "Disables X-Request-Id in responses.", vllmGroupFrontend),
		boolFlag("disable-fastapi-docs", "", nil, false, "Disables Swagger, ReDoc, and OpenAPI.", vllmGroupFrontend),
		boolFlag("no-disable-fastapi-docs", "", nil, false, "Keeps Swagger, ReDoc, and OpenAPI enabled.", vllmGroupFrontend),
		boolFlag("enable-offline-docs", "", nil, false, "Uses offline FastAPI docs with embedded assets.", vllmGroupFrontend),
		boolFlag("no-enable-offline-docs", "", nil, false, "Disables offline FastAPI docs.", vllmGroupFrontend),
		boolFlag("disable-uvicorn-access-log", "", nil, false, "Disables uvicorn access log.", vllmGroupFrontend),
		boolFlag("no-disable-uvicorn-access-log", "", nil, false, "Keeps uvicorn access log enabled.", vllmGroupFrontend),
		strFlag("disable-access-log-for-endpoints", "", nil, nil, "Suppresses access logs for comma-separated endpoints.", vllmGroupFrontend, false),
		enumFlag("uvicorn-log-level", "", nil, []string{"critical", "error", "warning", "info", "debug", "trace"}, "info", "Uvicorn log level.", vllmGroupFrontend),
		strFlag("middleware", "", nil, "[]", "Extra ASGI middleware; repeatable.", vllmGroupFrontend, false),
		boolFlag("return-tokens-as-token-ids", "", nil, false, "Returns tokens as token IDs.", vllmGroupFrontend),
		boolFlag("no-return-tokens-as-token-ids", "", nil, false, "Returns tokens as text when possible.", vllmGroupFrontend),
		boolFlag("enable-prompt-tokens-details", "", nil, false, "Adds prompt token details to usage.", vllmGroupFrontend),
		boolFlag("no-enable-prompt-tokens-details", "", nil, false, "Disables prompt token details in usage.", vllmGroupFrontend),
		boolFlag("enable-force-include-usage", "", nil, false, "Forces usage inclusion in responses.", vllmGroupFrontend),
		boolFlag("no-enable-force-include-usage", "", nil, false, "Does not force usage inclusion in responses.", vllmGroupFrontend),
		intFlag("h11-max-header-count", "", nil, 256, "Maximum HTTP headers.", vllmGroupFrontend, intPtr(1), nil),
		intFlag("h11-max-incomplete-event-size", "", nil, 4194304, "Maximum incomplete HTTP event size in bytes.", vllmGroupFrontend, intPtr(1), nil),

		strFlag("served-model-name", "", nil, nil, "Model name in the API and metrics; default uses the model.", vllmGroupModel, false),
		strFlag("tokenizer", "", nil, nil, "Tokenizer alternativo; default usa o modelo.", vllmGroupModel, false),
		enumFlag("tokenizer-mode", "", nil, []string{"auto", "hf", "slow", "mistral"}, "auto", "Tokenizer mode.", vllmGroupModel),
		strFlag("revision", "", nil, nil, "Branch, tag ou commit do modelo no Hugging Face.", vllmGroupModel, false),
		strFlag("code-revision", "", nil, nil, "Branch, tag, or commit of remote code.", vllmGroupModel, false),
		strFlag("tokenizer-revision", "", nil, nil, "Branch, tag ou commit do tokenizer.", vllmGroupModel, false),
		enumFlag("dtype", "", nil, []string{"auto", "bfloat16", "float16", "float32", "half", "float"}, "auto", "Data type for weights and activations.", vllmGroupModel),
		strFlag("max-model-len", "", nil, nil, "Total context length; accepts integer, 1k, auto, or -1.", vllmGroupModel, false),
		strFlag("quantization", "q", nil, nil, "Weight quantization method.", vllmGroupModel, false),
		intFlag("seed", "", nil, 0, "Seed global de reprodutibilidade.", vllmGroupModel, nil, nil),
		boolFlag("trust-remote-code", "", nil, false, "Trusts remote Hugging Face code.", vllmGroupModel),
		boolFlag("no-trust-remote-code", "", nil, false, "Disables execution of remote Hugging Face code.", vllmGroupModel),
		strFlag("hf-token", "", nil, nil, "Bearer token para arquivos remotos; True usa token local.", vllmGroupModel, false),
		strFlag("hf-overrides", "", nil, "{}", "Overrides HF config with JSON.", vllmGroupModel, false),
		strFlag("hf-config-path", "", nil, nil, "Caminho de config HF alternativa.", vllmGroupModel, false),
		enumFlag("config-format", "", nil, []string{"auto", "hf", "mistral"}, "auto", "Model config format.", vllmGroupModel),
		enumFlag("model-impl", "", nil, []string{"auto", "vllm", "transformers", "terratorch"}, "auto", "Model implementation.", vllmGroupModel),
		enumFlag("runner", "", nil, []string{"auto", "generate", "pooling", "draft"}, "auto", "Model runner type.", vllmGroupModel),
		enumFlag("convert", "", nil, []string{"auto", "classify", "embed", "none"}, "auto", "Adapts the model, for example from generation to pooling.", vllmGroupModel),
		boolFlag("enforce-eager", "", nil, false, "Forces eager mode, without CUDA graph.", vllmGroupModel),
		boolFlag("no-enforce-eager", "", nil, false, "Allows CUDA graphs and compilation when applicable.", vllmGroupModel),
		boolFlag("enable-sleep-mode", "", nil, false, "Enables engine sleep mode on CUDA/HIP.", vllmGroupModel),
		boolFlag("no-enable-sleep-mode", "", nil, false, "Disables engine sleep mode.", vllmGroupModel),
		boolFlag("disable-sliding-window", "", nil, false, "Disables sliding window.", vllmGroupModel),
		boolFlag("no-disable-sliding-window", "", nil, false, "Keeps sliding window enabled when supported.", vllmGroupModel),
		boolFlag("disable-cascade-attn", "", nil, true, "Disables cascade attention.", vllmGroupModel),
		boolFlag("no-disable-cascade-attn", "", nil, false, "Keeps cascade attention enabled.", vllmGroupModel),
		intFlag("max-logprobs", "", nil, 20, "Maximum returned logprobs; -1 removes the limit.", vllmGroupModel, nil, nil),
		enumFlag("logprobs-mode", "", nil, []string{"raw_logprobs", "processed_logprobs", "raw_logits", "processed_logits"}, "raw_logprobs", "Returned logprobs content.", vllmGroupModel),
		strFlag("generation-config", "", nil, "auto", "Origem da generation config: auto, vllm ou caminho.", vllmGroupModel, false),
		strFlag("override-generation-config", "", nil, "{}", "Overrides generation config with JSON.", vllmGroupModel, false),
		boolFlag("enable-prompt-embeds", "", nil, false, "Accepts prompt_embeds as input; use only with trusted users.", vllmGroupModel),
		boolFlag("no-enable-prompt-embeds", "", nil, false, "Disables input via prompt_embeds.", vllmGroupModel),
		boolFlag("skip-tokenizer-init", "", nil, false, "Pula init do tokenizer e espera token IDs.", vllmGroupModel),
		boolFlag("no-skip-tokenizer-init", "", nil, false, "Inicializa o tokenizer normalmente.", vllmGroupModel),
		strFlag("pooler-config", "", nil, nil, "Config de pooling para modelos de embedding.", vllmGroupModel, false),
		strFlag("allowed-local-media-path", "", nil, nil, "Allows reading local media; security risk.", vllmGroupModel, false),
		strFlag("allowed-media-domains", "", nil, nil, "Restricts multimodal media domains.", vllmGroupModel, false),
		intFlag("renderer-num-workers", "", nil, 1, "Rendering pool threads.", vllmGroupModel, intPtr(1), nil),
		strFlag("logits-processors", "", nil, nil, "Classes de logits processors customizados.", vllmGroupModel, false),
		strFlag("override-attention-dtype", "", nil, nil, "Overrides attention dtype.", vllmGroupModel, false),
		strFlag("io-processor-plugin", "", nil, nil, "Plugin IOProcessor carregado no startup.", vllmGroupModel, false),
		boolFlag("allow-deprecated-quantization", "", nil, false, "Allows obsolete quantizations.", vllmGroupModel),
		boolFlag("no-allow-deprecated-quantization", "", nil, false, "Blocks obsolete quantizations.", vllmGroupModel),

		enumFlag("load-format", "", nil, []string{"auto", "safetensors", "pt", "dummy", "tensorizer", "runai_streamer", "bitsandbytes", "gguf", "mistral"}, "auto", "Format of weights to load.", vllmGroupLoad),
		strFlag("download-dir", "", nil, nil, "Weights download/cache directory.", vllmGroupLoad, false),
		strFlag("ignore-patterns", "", nil, "['original/**/*']", "Patterns to ignore when loading weights.", vllmGroupLoad, false),
		strFlag("model-loader-extra-config", "", nil, "{}", "Config extra em JSON passada ao loader.", vllmGroupLoad, false),
		enumFlag("safetensors-load-strategy", "", nil, []string{"None", "lazy", "eager", "prefetch", "torchao"}, nil, "Safetensors read strategy.", vllmGroupLoad),
		strFlag("safetensors-prefetch-block-size", "", nil, "16M", "Prefetch read size.", vllmGroupLoad, false),
		intFlag("safetensors-prefetch-num-threads", "", nil, 8, "Prefetch threads.", vllmGroupLoad, intPtr(1), nil),
		strFlag("pt-load-map-location", "", nil, "cpu", "map_location do torch.load.", vllmGroupLoad, false),
		boolFlag("use-tqdm-on-load", "", nil, true, "Mostra barra de progresso no load.", vllmGroupLoad),
		boolFlag("no-use-tqdm-on-load", "", nil, false, "Disables progress bar during loading.", vllmGroupLoad),

		strFlag("attention-backend", "", nil, nil, "Attention backend; auto/None lets vLLM decide.", vllmGroupAttention, false),
		strFlag("mamba-backend", "", nil, "TRITON", "Backend Mamba SSM.", vllmGroupAttention, false),
		boolFlag("enable-mamba-cache-stochastic-rounding", "", nil, false, "Uses stochastic rounding in fp16 SSM cache.", vllmGroupAttention),
		boolFlag("no-enable-mamba-cache-stochastic-rounding", "", nil, false, "Disables stochastic rounding in SSM cache.", vllmGroupAttention),
		intFlag("mamba-cache-philox-rounds", "", nil, 0, "Philox PRNG rounds for stochastic rounding.", vllmGroupAttention, intPtr(0), nil),

		strFlag("reasoning-parser-plugin", "", nil, "", "Plugin de reasoning parser carregado dinamicamente.", vllmGroupStructured, false),
		strFlag("structured-outputs-config", "", nil, nil, "Full structured output config in JSON.", vllmGroupStructured, false),

		intFlag("tensor-parallel-size", "tp", nil, 1, "Grupos de tensor parallelism.", vllmGroupParallel, intPtr(1), nil),
		intFlag("pipeline-parallel-size", "pp", nil, 1, "Grupos de pipeline parallelism.", vllmGroupParallel, intPtr(1), nil),
		intFlag("data-parallel-size", "dp", nil, 1, "Grupos de data parallelism.", vllmGroupParallel, intPtr(1), nil),
		intFlag("data-parallel-size-local", "dpl", nil, nil, "Local DP replicas on this node.", vllmGroupParallel, intPtr(1), nil),
		intFlag("data-parallel-rank", "dpn", nil, nil, "DP rank of this instance for external LB/MoE.", vllmGroupParallel, intPtr(0), nil),
		intFlag("data-parallel-start-rank", "dpr", nil, nil, "Initial DP rank on secondary nodes.", vllmGroupParallel, intPtr(0), nil),
		strFlag("data-parallel-address", "dpa", nil, nil, "Address of the DP cluster head node.", vllmGroupParallel, false),
		portFlag("data-parallel-rpc-port", "dpp", 0, "Data parallelism RPC port.", vllmGroupParallel),
		enumFlag("data-parallel-backend", "dpb", nil, []string{"mp", "ray"}, "mp", "Backend do data parallelism.", vllmGroupParallel),
		boolFlag("data-parallel-external-lb", "dpe", nil, false, "One-pod-per-rank external LB mode for MoE.", vllmGroupParallel),
		boolFlag("data-parallel-hybrid-lb", "dph", nil, false, "Per-node hybrid LB mode.", vllmGroupParallel),
		intFlag("decode-context-parallel-size", "dcp", nil, 1, "Grupos de decode context parallel.", vllmGroupParallel, intPtr(1), nil),
		intFlag("prefill-context-parallel-size", "pcp", nil, 1, "Grupos de prefill context parallel.", vllmGroupParallel, intPtr(1), nil),
		boolFlag("enable-expert-parallel", "ep", nil, false, "Uses expert parallelism in MoE layers.", vllmGroupParallel),
		boolFlag("no-enable-expert-parallel", "", nil, false, "Disables expert parallelism in MoE layers.", vllmGroupParallel),
		boolFlag("enable-eplb", "", nil, false, "Enables expert-parallel load balancing.", vllmGroupParallel),
		boolFlag("no-enable-eplb", "", nil, false, "Disables EPLB.", vllmGroupParallel),
		strFlag("eplb-config", "", nil, nil, "EPLB configuration in JSON.", vllmGroupParallel, false),
		enumFlag("expert-placement-strategy", "", nil, []string{"linear", "round_robin"}, "linear", "Posicionamento de experts MoE.", vllmGroupParallel),
		strFlag("all2all-backend", "", nil, "allgather_reducescatter", "All2all communication backend for MoE.", vllmGroupParallel, false),
		enumFlag("distributed-executor-backend", "", nil, []string{"mp", "ray", "uni", "external_launcher"}, nil, "Distributed workers backend; None selects automatically.", vllmGroupParallel),
		boolFlag("disable-custom-all-reduce", "", nil, false, "Disables custom all-reduce and uses NCCL.", vllmGroupParallel),
		boolFlag("no-disable-custom-all-reduce", "", nil, false, "Allows custom all-reduce.", vllmGroupParallel),
		intFlag("nnodes", "n", nil, 1, "Number of nodes for multi-node mp.", vllmGroupParallel, intPtr(1), nil),
		intFlag("node-rank", "r", nil, 0, "Node rank.", vllmGroupParallel, intPtr(0), nil),
		strFlag("master-addr", "", nil, "127.0.0.1", "Master address for multi-node mp.", vllmGroupParallel, false),
		portFlag("master-port", "", 29501, "Master port for multi-node mp.", vllmGroupParallel),
		intFlag("max-parallel-loading-workers", "", nil, nil, "Parallel loading workers to avoid RAM OOM.", vllmGroupParallel, intPtr(1), nil),
		boolFlag("numa-bind", "", nil, false, "NUMA binding for GPU workers.", vllmGroupParallel),
		boolFlag("no-numa-bind", "", nil, false, "Disables NUMA binding.", vllmGroupParallel),
		strFlag("numa-bind-nodes", "", nil, nil, "List of NUMA nodes per GPU.", vllmGroupParallel, false),
		strFlag("numa-bind-cpus", "", nil, nil, "List of CPUs per GPU for NUMA binding.", vllmGroupParallel, false),
		boolFlag("enable-dbo", "", nil, false, "Enables Dual Batch Overlap.", vllmGroupParallel),
		boolFlag("no-enable-dbo", "", nil, false, "Disables Dual Batch Overlap.", vllmGroupParallel),
		intFlag("dbo-prefill-token-threshold", "", nil, 512, "Token threshold for DBO prefill microbatching.", vllmGroupParallel, intPtr(0), nil),
		intFlag("dbo-decode-token-threshold", "", nil, 32, "Token threshold for DBO decode microbatching.", vllmGroupParallel, intPtr(0), nil),
		strFlag("worker-cls", "", nil, "auto", "Worker class.", vllmGroupParallel, false),
		strFlag("worker-extension-cls", "", nil, nil, "Worker extension class.", vllmGroupParallel, false),
		boolFlag("enable-elastic-ep", "", nil, false, "Enables elastic expert parallelism with stateless NCCL.", vllmGroupParallel),
		boolFlag("no-enable-elastic-ep", "", nil, false, "Disables elastic expert parallelism.", vllmGroupParallel),
		boolFlag("enable-ep-weight-filter", "", nil, false, "Each rank reads only its expert weights.", vllmGroupParallel),
		boolFlag("no-enable-ep-weight-filter", "", nil, false, "Each rank reads the normal set of expert weights.", vllmGroupParallel),
		intFlag("ubatch-size", "", nil, 0, "Ubatch size.", vllmGroupParallel, intPtr(0), nil),
		intFlag("cp-kv-cache-interleave-size", "", nil, nil, "KV interleave in DCP/PCP.", vllmGroupParallel, intPtr(0), nil),
		enumFlag("dcp-comm-backend", "", nil, []string{"ag_rs", "a2a"}, "ag_rs", "DCP communication backend.", vllmGroupParallel),
		intFlag("distributed-timeout-seconds", "", nil, nil, "Distributed operations timeout.", vllmGroupParallel, intPtr(1), nil),
		boolFlag("ray-workers-use-nsight", "", nil, false, "Ray worker profiling with nsight.", vllmGroupParallel),
		boolFlag("no-ray-workers-use-nsight", "", nil, false, "Disables nsight on Ray workers.", vllmGroupParallel),

		floatFlag("gpu-memory-utilization", "", nil, 0.92, "Fraction of VRAM used by the engine.", vllmGroupKV, floatPtr(0), floatPtr(1)),
		strFlag("kv-cache-memory-bytes", "", nil, nil, "Fixed KV cache size per GPU; ignores the fraction.", vllmGroupKV, false),
		enumFlag("kv-cache-dtype", "", nil, []string{"auto", "fp8", "fp8_e4m3", "fp8_e5m2", "bfloat16", "float16"}, "auto", "KV cache data type.", vllmGroupKV),
		strFlag("kv-cache-dtype-skip-layers", "", nil, "[]", "Layers or types that skip KV quantization.", vllmGroupKV, false),
		intFlag("block-size", "", nil, nil, "Tokens por bloco de cache.", vllmGroupKV, intPtr(1), nil),
		boolFlag("enable-prefix-caching", "", nil, false, "Reuses KV from already-processed prefixes.", vllmGroupKV),
		boolFlag("no-enable-prefix-caching", "", nil, false, "Disables prefix caching.", vllmGroupKV),
		enumFlag("prefix-caching-hash-algo", "", nil, []string{"sha256", "sha256_cbor", "xxhash", "xxhash_cbor"}, "sha256", "Hash usado no prefix caching.", vllmGroupKV),
		intFlag("num-gpu-blocks-override", "", nil, nil, "Overrides number of GPU blocks for preemption tests.", vllmGroupKV, intPtr(1), nil),
		floatFlag("kv-offloading-size", "", nil, nil, "Buffer de offload do KV para CPU em GiB.", vllmGroupKV, floatPtr(0), nil),
		enumFlag("kv-offloading-backend", "", nil, []string{"native", "lmcache"}, "native", "Backend de offload do KV.", vllmGroupKV),
		intFlag("mamba-block-size", "", nil, nil, "Mamba cache block; multiple of 8.", vllmGroupKV, intPtr(1), nil),
		enumFlag("mamba-cache-dtype", "", nil, []string{"auto", "float16", "float32"}, "auto", "Mamba cache dtype.", vllmGroupKV),
		enumFlag("mamba-ssm-cache-dtype", "", nil, []string{"auto", "float16", "float32"}, "auto", "Dtype do estado SSM Mamba.", vllmGroupKV),
		enumFlag("mamba-cache-mode", "", nil, []string{"none", "all", "align"}, "none", "Cache strategy for Mamba layers.", vllmGroupKV),
		boolFlag("calculate-kv-scales", "", nil, false, "Deprecated: dynamically calculates k/v_scale in fp8.", vllmGroupKV),
		boolFlag("no-calculate-kv-scales", "", nil, false, "Disables dynamic calculation of fp8 KV scales.", vllmGroupKV),
		boolFlag("kv-sharing-fast-prefill", "", nil, false, "WIP prefill optimization in KV sharing.", vllmGroupKV),
		boolFlag("no-kv-sharing-fast-prefill", "", nil, false, "Disables fast prefill in KV sharing.", vllmGroupKV),

		floatFlag("cpu-offload-gb", "", nil, float64(0), "CPU weight offload space per GPU, in GiB.", vllmGroupWeightOffload, floatPtr(0), nil),
		enumFlag("offload-backend", "", nil, []string{"auto", "uva", "prefetch"}, "auto", "Weight offload backend.", vllmGroupWeightOffload),
		strFlag("cpu-offload-params", "", nil, nil, "Parameter name segments to offload via UVA.", vllmGroupWeightOffload, false),
		intFlag("offload-group-size", "", nil, 0, "Groups every N layers for grouped offload.", vllmGroupWeightOffload, intPtr(0), nil),
		intFlag("offload-num-in-group", "", nil, 1, "Number of layers to offload per group.", vllmGroupWeightOffload, intPtr(0), nil),
		intFlag("offload-prefetch-step", "", nil, 1, "Layers to prefetch ahead.", vllmGroupWeightOffload, intPtr(0), nil),
		strFlag("offload-params", "", nil, nil, "Segmentos de nome para prefetch offloading.", vllmGroupWeightOffload, false),

		strFlag("limit-mm-per-prompt", "", nil, "{}", "Maximum items per modality per prompt.", vllmGroupMultimodal, false),
		boolFlag("language-model-only", "", nil, false, "Disables all multimodal inputs.", vllmGroupMultimodal),
		boolFlag("no-language-model-only", "", nil, false, "Allows multimodal inputs.", vllmGroupMultimodal),
		strFlag("mm-processor-kwargs", "", nil, nil, "Args para o processador multimodal do modelo.", vllmGroupMultimodal, false),
		floatFlag("mm-processor-cache-gb", "", nil, float64(4), "Cache do processador multimodal em GiB.", vllmGroupMultimodal, floatPtr(0), nil),
		enumFlag("mm-processor-cache-type", "", nil, []string{"lru", "shm"}, "lru", "Multimodal processor cache type.", vllmGroupMultimodal),
		intFlag("mm-shm-cache-max-object-size-mb", "", nil, 128, "Per-object limit in shm cache, in MiB.", vllmGroupMultimodal, intPtr(1), nil),
		strFlag("media-io-kwargs", "", nil, nil, "Media processing args, such as num_frames.", vllmGroupMultimodal, false),
		boolFlag("interleave-mm-strings", "", nil, false, "Prompts multimodais totalmente intercalados.", vllmGroupMultimodal),
		boolFlag("no-interleave-mm-strings", "", nil, false, "Disables full multimodal string interleaving.", vllmGroupMultimodal),
		boolFlag("enable-mm-embeds", "", nil, false, "Accepts multimodal embeddings as input.", vllmGroupMultimodal),
		boolFlag("no-enable-mm-embeds", "", nil, false, "Disables multimodal embeddings as input.", vllmGroupMultimodal),
		boolFlag("skip-mm-profiling", "", nil, false, "Skips multimodal memory profiling.", vllmGroupMultimodal),
		boolFlag("no-skip-mm-profiling", "", nil, false, "Runs multimodal memory profiling.", vllmGroupMultimodal),
		enumFlag("mm-encoder-tp-mode", "", nil, []string{"weights", "data"}, "weights", "Como o encoder multimodal usa tensor parallelism.", vllmGroupMultimodal),
		strFlag("mm-encoder-attn-backend", "", nil, nil, "ViT encoder attention backend.", vllmGroupMultimodal, false),
		enumFlag("mm-encoder-attn-dtype", "", nil, []string{"fp8", "None"}, nil, "ViT encoder attention dtype.", vllmGroupMultimodal),
		strFlag("mm-encoder-fp8-scale-path", "", nil, nil, "Caminho das escalas FP8 do encoder.", vllmGroupMultimodal, false),
		strFlag("mm-encoder-fp8-scale-save-path", "", nil, nil, "Caminho para salvar escalas FP8 do encoder.", vllmGroupMultimodal, false),
		floatFlag("mm-encoder-fp8-scale-save-margin", "", nil, 1.5, "Margem das escalas FP8 do encoder.", vllmGroupMultimodal, floatPtr(0), nil),
		boolFlag("mm-encoder-only", "", nil, false, "Runs only the multimodal encoder and skips the LM.", vllmGroupMultimodal),
		boolFlag("no-mm-encoder-only", "", nil, false, "Executa encoder multimodal e LM.", vllmGroupMultimodal),
		enumFlag("mm-tensor-ipc", "", nil, []string{"direct_rpc", "torch_shm"}, "direct_rpc", "IPC de tensores multimodais.", vllmGroupMultimodal),
		floatFlag("video-pruning-rate", "", nil, nil, "Fraction of video tokens pruned by EVS.", vllmGroupMultimodal, floatPtr(0), floatPtr(1)),

		boolFlag("enable-lora", "", nil, false, "Enables LoRA adapters.", vllmGroupLora),
		boolFlag("no-enable-lora", "", nil, false, "Disables LoRA adapters.", vllmGroupLora),
		intFlag("max-loras", "", nil, 1, "Maximum LoRAs in a single batch.", vllmGroupLora, intPtr(1), nil),
		intFlag("max-lora-rank", "", nil, 16, "Maximum LoRA rank.", vllmGroupLora, intPtr(1), intPtr(512)),
		intFlag("max-cpu-loras", "", nil, nil, "Maximum LoRAs in RAM; must be >= max_loras.", vllmGroupLora, intPtr(1), nil),
		enumFlag("lora-dtype", "", nil, []string{"auto", "float16", "bfloat16"}, "auto", "Dtype dos LoRAs.", vllmGroupLora),
		strFlag("lora-target-modules", "", nil, nil, "Restricts LoRA to module suffixes.", vllmGroupLora, false),
		boolFlag("fully-sharded-loras", "", nil, false, "LoRA layers fully sharded by TP.", vllmGroupLora),
		boolFlag("no-fully-sharded-loras", "", nil, false, "Uses LoRA without full TP sharding.", vllmGroupLora),
		strFlag("default-mm-loras", "", nil, nil, "Mapeia modalidades para caminhos LoRA.", vllmGroupLora, false),
		boolFlag("enable-tower-connector-lora", "", nil, false, "Enables LoRA in multimodal model encoder/connector.", vllmGroupLora),
		boolFlag("no-enable-tower-connector-lora", "", nil, false, "Disables LoRA in multimodal encoder/connector.", vllmGroupLora),
		boolFlag("specialize-active-lora", "", nil, false, "CUDA graphs por contagem de LoRAs ativos.", vllmGroupLora),
		boolFlag("no-specialize-active-lora", "", nil, false, "Disables CUDA graph specialization by active LoRAs.", vllmGroupLora),

		strFlag("otlp-traces-endpoint", "", nil, nil, "OpenTelemetry endpoint for traces.", vllmGroupObservability, false),
		enumFlag("collect-detailed-traces", "", nil, []string{"all", "model", "worker", "None"}, nil, "Detailed traces by module.", vllmGroupObservability),
		strFlag("show-hidden-metrics-for-version", "", nil, nil, "Re-enables Prometheus metrics deprecated in one version.", vllmGroupObservability, false),
		boolFlag("enable-server-load-tracking", "", nil, false, "Tracks server load.", vllmGroupObservability),
		boolFlag("no-enable-server-load-tracking", "", nil, false, "Disables server load tracking.", vllmGroupObservability),
		boolFlag("cudagraph-metrics", "", nil, false, "CUDA graph metrics.", vllmGroupObservability),
		boolFlag("no-cudagraph-metrics", "", nil, false, "Disables CUDA graph metrics.", vllmGroupObservability),
		boolFlag("kv-cache-metrics", "", nil, false, "KV cache residency metrics.", vllmGroupObservability),
		boolFlag("no-kv-cache-metrics", "", nil, false, "Disables KV cache metrics.", vllmGroupObservability),
		floatFlag("kv-cache-metrics-sample", "", nil, 0.01, "Sampling rate for KV cache metrics.", vllmGroupObservability, floatPtr(0), floatPtr(1)),
		boolFlag("enable-mfu-metrics", "", nil, false, "Enables Model FLOPs Utilization metrics.", vllmGroupObservability),
		boolFlag("no-enable-mfu-metrics", "", nil, false, "Disables MFU metrics.", vllmGroupObservability),
		boolFlag("enable-layerwise-nvtx-tracing", "", nil, false, "Tracing NVTX por camada.", vllmGroupObservability),
		boolFlag("no-enable-layerwise-nvtx-tracing", "", nil, false, "Disables per-layer NVTX tracing.", vllmGroupObservability),
		boolFlag("enable-logging-iteration-details", "", nil, false, "Logs details per iteration.", vllmGroupObservability),
		boolFlag("no-enable-logging-iteration-details", "", nil, false, "Disables detailed logs per iteration.", vllmGroupObservability),

		strFlag("max-num-batched-tokens", "", nil, nil, "Maximum tokens per iteration; accepts integer or 1k.", vllmGroupScheduler, false),
		intFlag("max-num-seqs", "", nil, nil, "Maximum sequences per iteration.", vllmGroupScheduler, intPtr(1), nil),
		boolFlag("enable-chunked-prefill", "", nil, false, "Fatia prefills longos.", vllmGroupScheduler),
		boolFlag("no-enable-chunked-prefill", "", nil, false, "Disables chunked prefill.", vllmGroupScheduler),
		intFlag("long-prefill-token-threshold", "", nil, 0, "Token count at which a prompt is considered long.", vllmGroupScheduler, intPtr(0), nil),
		intFlag("max-num-partial-prefills", "", nil, 1, "Prefills parciais concorrentes.", vllmGroupScheduler, intPtr(1), nil),
		intFlag("max-long-partial-prefills", "", nil, 1, "Prompts longos prefillados concorrentemente.", vllmGroupScheduler, intPtr(1), nil),
		enumFlag("scheduling-policy", "", nil, []string{"fcfs", "priority"}, "fcfs", "Scheduling policy.", vllmGroupScheduler),
		boolFlag("async-scheduling", "", nil, false, "Asynchronous scheduling.", vllmGroupScheduler),
		boolFlag("no-async-scheduling", "", nil, false, "Disables asynchronous scheduling.", vllmGroupScheduler),
		boolFlag("scheduler-reserve-full-isl", "", nil, true, "Reserva o ISL completo antes de admitir.", vllmGroupScheduler),
		boolFlag("no-scheduler-reserve-full-isl", "", nil, false, "Does not reserve full ISL before admitting.", vllmGroupScheduler),
		boolFlag("disable-chunked-mm-input", "", nil, false, "Does not slice multimodal item in chunked prefill.", vllmGroupScheduler),
		boolFlag("no-disable-chunked-mm-input", "", nil, false, "Allows slicing multimodal item in chunked prefill.", vllmGroupScheduler),
		strFlag("scheduler-cls", "", nil, "Scheduler", "Custom scheduler class.", vllmGroupScheduler, false),
		intFlag("stream-interval", "", nil, 1, "Intervalo de streaming em tokens.", vllmGroupScheduler, intPtr(1), nil),

		strFlag("compilation-config", "cc", nil, nil, "Config de torch.compile e CUDA graphs em JSON.", vllmGroupCompilation, false),
		intFlag("optimization-level", "O", nil, 2, "Optimization level; 0 prioritizes startup, 3 performance.", vllmGroupCompilation, intPtr(0), intPtr(3)),
		enumFlag("performance-mode", "", nil, []string{"balanced", "interactivity", "throughput"}, "balanced", "Runtime profile.", vllmGroupCompilation),
		strFlag("cudagraph-capture-sizes", "", nil, nil, "Tamanhos de batch capturados em CUDA graph.", vllmGroupCompilation, false),
		intFlag("max-cudagraph-capture-size", "", nil, nil, "Maior tamanho de captura de CUDA graph.", vllmGroupCompilation, intPtr(1), nil),

		strFlag("moe-backend", "", nil, "auto", "Backend dos kernels de MoE; auto escolhe pelo modelo/hardware.", vllmGroupKernels, false),
		boolFlag("enable-flashinfer-autotune", "", nil, false, "Autotuning do FlashInfer no warmup.", vllmGroupKernels),
		boolFlag("no-enable-flashinfer-autotune", "", nil, false, "Disables FlashInfer autotuning.", vllmGroupKernels),
		strFlag("ir-op-priority", "", nil, nil, "Prioridade de ops da IR do vLLM no forward.", vllmGroupKernels, false),
		strFlag("kernel-config", "", nil, nil, "Config consolidada de kernels em JSON.", vllmGroupKernels, false),

		strFlag("speculative-config", "sc", nil, nil, "Speculative decoding configuration in JSON.", vllmGroupAdvancedConfigs, false),
		strFlag("kv-transfer-config", "", nil, nil, "Distributed KV cache transfer for disaggregated prefill/decode.", vllmGroupAdvancedConfigs, false),
		strFlag("kv-events-config", "", nil, nil, "KV cache event publishing.", vllmGroupAdvancedConfigs, false),
		strFlag("ec-transfer-config", "", nil, nil, "Distributed EC cache transfer.", vllmGroupAdvancedConfigs, false),
		strFlag("weight-transfer-config", "", nil, nil, "Weight transfer during RL training.", vllmGroupAdvancedConfigs, false),
		strFlag("reasoning-config", "", nil, nil, "Config de modelo de reasoning.", vllmGroupAdvancedConfigs, false),
		strFlag("attention-config", "ac", nil, nil, "Detailed attention config and backend overrides.", vllmGroupAdvancedConfigs, false),
		strFlag("profiler-config", "", nil, nil, "Config de profiling com torch profiler.", vllmGroupAdvancedConfigs, false),
		strFlag("additional-config", "", nil, "{}", "Additional platform-specific config.", vllmGroupAdvancedConfigs, false),
	} {
		add(spec)
	}

	return domain.BackendValidationSchema{
		SchemaVersion: 1,
		Kind:          domain.ValidationSchemaCLIFlagsV1,
		BackendKind:   domain.BackendKindVLLM,
		BackendID:     "vllm-default",
		Source: domain.SchemaSource{
			GeneratedFrom: "vllm.md curated reference",
			SourceVersion: "curated-vllm",
			Editable:      true,
		},
		Flags:        flags,
		Presentation: vllmPresentation(),
	}
}

func vllmPresentation() *domain.Presentation {
	return &domain.Presentation{Groups: []domain.PresentationGroup{
		{Name: vllmGroupEssentials, Highlighted: true, Flags: []string{"host", "port", "api-key", "served-model-name", "dtype", "max-model-len", "quantization", "tensor-parallel-size", "gpu-memory-utilization", "kv-cache-dtype", "enable-prefix-caching", "max-num-batched-tokens", "max-num-seqs", "enable-chunked-prefill", "uvicorn-log-level"}},
		{Name: vllmGroupServer, Flags: []string{"config", "api-server-count", "headless", "grpc", "disable-log-stats", "enable-log-requests", "no-enable-log-requests", "aggregate-engine-logging", "shutdown-timeout", "gdn-prefill-backend", "fail-on-environ-validation", "no-fail-on-environ-validation"}},
		{Name: vllmGroupFrontend, Flags: []string{"host", "port", "uds", "api-key", "root-path", "allowed-origins", "allowed-methods", "allowed-headers", "allow-credentials", "no-allow-credentials", "ssl-certfile", "ssl-keyfile", "ssl-ca-certs", "ssl-cert-reqs", "ssl-ciphers", "enable-ssl-refresh", "no-enable-ssl-refresh", "chat-template", "chat-template-content-format", "default-chat-template-kwargs", "response-role", "enable-auto-tool-choice", "no-enable-auto-tool-choice", "tool-call-parser", "tool-parser-plugin", "reasoning-parser", "lora-modules", "max-log-len", "enable-request-id-headers", "no-enable-request-id-headers", "disable-fastapi-docs", "no-disable-fastapi-docs", "enable-offline-docs", "no-enable-offline-docs", "disable-uvicorn-access-log", "no-disable-uvicorn-access-log", "disable-access-log-for-endpoints", "uvicorn-log-level", "middleware", "return-tokens-as-token-ids", "no-return-tokens-as-token-ids", "enable-prompt-tokens-details", "no-enable-prompt-tokens-details", "enable-force-include-usage", "no-enable-force-include-usage", "h11-max-header-count", "h11-max-incomplete-event-size"}},
		{Name: vllmGroupModel, Flags: []string{"served-model-name", "tokenizer", "tokenizer-mode", "revision", "code-revision", "tokenizer-revision", "dtype", "max-model-len", "quantization", "seed", "trust-remote-code", "no-trust-remote-code", "hf-token", "hf-overrides", "hf-config-path", "config-format", "model-impl", "runner", "convert", "enforce-eager", "no-enforce-eager", "enable-sleep-mode", "no-enable-sleep-mode", "disable-sliding-window", "no-disable-sliding-window", "disable-cascade-attn", "no-disable-cascade-attn", "max-logprobs", "logprobs-mode", "generation-config", "override-generation-config", "enable-prompt-embeds", "no-enable-prompt-embeds", "skip-tokenizer-init", "no-skip-tokenizer-init", "pooler-config", "allowed-local-media-path", "allowed-media-domains", "renderer-num-workers", "logits-processors", "override-attention-dtype", "io-processor-plugin", "allow-deprecated-quantization", "no-allow-deprecated-quantization"}},
		{Name: vllmGroupLoad, Flags: []string{"load-format", "download-dir", "ignore-patterns", "model-loader-extra-config", "safetensors-load-strategy", "safetensors-prefetch-block-size", "safetensors-prefetch-num-threads", "pt-load-map-location", "use-tqdm-on-load", "no-use-tqdm-on-load"}},
		{Name: vllmGroupAttention, Flags: []string{"attention-backend", "mamba-backend", "enable-mamba-cache-stochastic-rounding", "no-enable-mamba-cache-stochastic-rounding", "mamba-cache-philox-rounds"}},
		{Name: vllmGroupStructured, Flags: []string{"reasoning-parser", "reasoning-parser-plugin", "structured-outputs-config"}},
		{Name: vllmGroupParallel, Flags: []string{"tensor-parallel-size", "pipeline-parallel-size", "data-parallel-size", "data-parallel-size-local", "data-parallel-rank", "data-parallel-start-rank", "data-parallel-address", "data-parallel-rpc-port", "data-parallel-backend", "data-parallel-external-lb", "data-parallel-hybrid-lb", "decode-context-parallel-size", "prefill-context-parallel-size", "enable-expert-parallel", "no-enable-expert-parallel", "enable-eplb", "no-enable-eplb", "eplb-config", "expert-placement-strategy", "all2all-backend", "distributed-executor-backend", "disable-custom-all-reduce", "no-disable-custom-all-reduce", "nnodes", "node-rank", "master-addr", "master-port", "max-parallel-loading-workers", "numa-bind", "no-numa-bind", "numa-bind-nodes", "numa-bind-cpus", "enable-dbo", "no-enable-dbo", "dbo-prefill-token-threshold", "dbo-decode-token-threshold", "worker-cls", "worker-extension-cls", "enable-elastic-ep", "no-enable-elastic-ep", "enable-ep-weight-filter", "no-enable-ep-weight-filter", "ubatch-size", "cp-kv-cache-interleave-size", "dcp-comm-backend", "distributed-timeout-seconds", "ray-workers-use-nsight", "no-ray-workers-use-nsight"}},
		{Name: vllmGroupKV, Flags: []string{"gpu-memory-utilization", "kv-cache-memory-bytes", "kv-cache-dtype", "kv-cache-dtype-skip-layers", "block-size", "enable-prefix-caching", "no-enable-prefix-caching", "prefix-caching-hash-algo", "num-gpu-blocks-override", "kv-offloading-size", "kv-offloading-backend", "mamba-block-size", "mamba-cache-dtype", "mamba-ssm-cache-dtype", "mamba-cache-mode", "calculate-kv-scales", "no-calculate-kv-scales", "kv-sharing-fast-prefill", "no-kv-sharing-fast-prefill"}},
		{Name: vllmGroupWeightOffload, Flags: []string{"cpu-offload-gb", "offload-backend", "cpu-offload-params", "offload-group-size", "offload-num-in-group", "offload-prefetch-step", "offload-params"}},
		{Name: vllmGroupMultimodal, Flags: []string{"limit-mm-per-prompt", "language-model-only", "no-language-model-only", "mm-processor-kwargs", "mm-processor-cache-gb", "mm-processor-cache-type", "mm-shm-cache-max-object-size-mb", "media-io-kwargs", "interleave-mm-strings", "no-interleave-mm-strings", "enable-mm-embeds", "no-enable-mm-embeds", "skip-mm-profiling", "no-skip-mm-profiling", "mm-encoder-tp-mode", "mm-encoder-attn-backend", "mm-encoder-attn-dtype", "mm-encoder-fp8-scale-path", "mm-encoder-fp8-scale-save-path", "mm-encoder-fp8-scale-save-margin", "mm-encoder-only", "no-mm-encoder-only", "mm-tensor-ipc", "video-pruning-rate"}},
		{Name: vllmGroupLora, Flags: []string{"enable-lora", "no-enable-lora", "max-loras", "max-lora-rank", "max-cpu-loras", "lora-dtype", "lora-target-modules", "fully-sharded-loras", "no-fully-sharded-loras", "default-mm-loras", "enable-tower-connector-lora", "no-enable-tower-connector-lora", "specialize-active-lora", "no-specialize-active-lora"}},
		{Name: vllmGroupObservability, Flags: []string{"otlp-traces-endpoint", "collect-detailed-traces", "show-hidden-metrics-for-version", "enable-server-load-tracking", "no-enable-server-load-tracking", "cudagraph-metrics", "no-cudagraph-metrics", "kv-cache-metrics", "no-kv-cache-metrics", "kv-cache-metrics-sample", "enable-mfu-metrics", "no-enable-mfu-metrics", "enable-layerwise-nvtx-tracing", "no-enable-layerwise-nvtx-tracing", "enable-logging-iteration-details", "no-enable-logging-iteration-details"}},
		{Name: vllmGroupScheduler, Flags: []string{"max-num-batched-tokens", "max-num-seqs", "enable-chunked-prefill", "no-enable-chunked-prefill", "long-prefill-token-threshold", "max-num-partial-prefills", "max-long-partial-prefills", "scheduling-policy", "async-scheduling", "no-async-scheduling", "scheduler-reserve-full-isl", "no-scheduler-reserve-full-isl", "disable-chunked-mm-input", "no-disable-chunked-mm-input", "scheduler-cls", "stream-interval"}},
		{Name: vllmGroupCompilation, Flags: []string{"compilation-config", "optimization-level", "performance-mode", "cudagraph-capture-sizes", "max-cudagraph-capture-size"}},
		{Name: vllmGroupKernels, Flags: []string{"moe-backend", "enable-flashinfer-autotune", "no-enable-flashinfer-autotune", "ir-op-priority", "kernel-config"}},
		{Name: vllmGroupAdvancedConfigs, Flags: []string{"speculative-config", "kv-transfer-config", "kv-events-config", "ec-transfer-config", "weight-transfer-config", "reasoning-config", "attention-config", "profiler-config", "additional-config"}},
	}}
}
