package backendschema

import "github.com/quantmind-br/model-loader/internal/domain"

const (
	sglangGroupEssentials                       = "Essenciais"
	sglangGroupServidorEGeral                   = "1. Servidor e geral"
	sglangGroupModeloETokenizer                 = "2. Modelo e tokenizer"
	sglangGroupCarregamentoDePesos              = "3. Carregamento de pesos"
	sglangGroupDtypeEQuantizacao                = "4. Dtype e quantização"
	sglangGroupMemoriaEKvCache                  = "5. Memória e KV cache"
	sglangGroupCacheDePrefixoRadixEHierarquico  = "6. Cache de prefixo: radix e hierárquico"
	sglangGroupPrefillChunkingEScheduler        = "7. Prefill, chunking e scheduler"
	sglangGroupStreamingSamplingEGramatica      = "8. Streaming, sampling e gramática"
	sglangGroupParalelismoEExecucaoDistribuida  = "9. Paralelismo e execução distribuída"
	sglangGroupMoeEExpertParallelism            = "10. MoE e expert parallelism"
	sglangGroupBackendsDeAtencaoEGemm           = "11. Backends de atenção e GEMM"
	sglangGroupAtencaoEsparsaNsaEDoubleSparsity = "12. Atenção esparsa (NSA e Double Sparsity)"
	sglangGroupMambaSsm                         = "13. Mamba (SSM)"
	sglangGroupLora                             = "14. LoRA"
	sglangGroupSpeculativeDecoding              = "15. Speculative decoding"
	sglangGroupCudaGraphETorchCompile           = "16. CUDA graph e torch.compile"
	sglangGroupComunicacaoEAllReduce            = "17. Comunicação e all-reduce"
	sglangGroupOffloadDePesosEMemorySaver       = "18. Offload de pesos e memory saver"
	sglangGroupMultimodalEEncoder               = "19. Multimodal e encoder"
	sglangGroupApiOpenaiEParsers                = "20. API OpenAI e parsers"
	sglangGroupLoggingMetricasETracing          = "21. Logging, métricas e tracing"
	sglangGroupPdDisaggregation                 = "22. PD disaggregation"
	sglangGroupDebugDeterminismoEDiversos       = "23. Debug, determinismo e diversos"
	sglangGroupServidorDeModelosDeDifusao       = "24. Servidor de modelos de difusão"
)

// CuratedSGLangSchema returns the hand-curated sglang serve schema based on sglang.md.
// The model path flags are intentionally omitted because model-loader handles model selection separately.
func CuratedSGLangSchema() domain.BackendValidationSchema {
	flags := map[string]domain.FlagSpec{}
	add := func(spec domain.FlagSpec) { flags[spec.Long] = spec }
	for _, spec := range []domain.FlagSpec{
		strFlag("host", "", nil, nil, "Endereço do servidor HTTP.", sglangGroupServidorEGeral, false),
		portFlag("port", "", 30000, "Porta do servidor HTTP.", sglangGroupServidorEGeral),
		strFlag("fastapi-root-path", "", nil, nil, "`root_path` do FastAPI atrás de proxy de rota.", sglangGroupServidorEGeral, false),
		boolFlag("grpc-mode", "", nil, false, "Usa servidor gRPC em vez de HTTP.", sglangGroupServidorEGeral),
		strFlag("config", "", nil, nil, "Lê opções de CLI de um arquivo YAML.", sglangGroupServidorEGeral, false),
		boolFlag("skip-server-warmup", "", nil, false, "Pula o warmup do servidor.", sglangGroupServidorEGeral),
		strFlag("warmups", "", nil, nil, "Funções de warmup customizadas (de `warmup.py`).", sglangGroupServidorEGeral, false),
		intFlag("nccl-port", "", nil, nil, "Porta para o setup distribuído NCCL (default aleatória).", sglangGroupServidorEGeral, nil, nil),
		boolFlag("checkpoint-engine-wait-weights-before-ready", "", nil, false, "Espera pesos iniciais antes de servir.", sglangGroupServidorEGeral),
		intFlag("watchdog-timeout", "", nil, nil, "Crash se um forward batch passar do tempo (evita travamento).", sglangGroupServidorEGeral, nil, nil),
		intFlag("soft-watchdog-timeout", "", nil, nil, "Dump de debug se um forward batch passar do tempo (sem crash).", sglangGroupServidorEGeral, nil, nil),
		intFlag("dist-timeout", "", nil, nil, "Timeout do `torch.distributed`.", sglangGroupServidorEGeral, nil, nil),
		strFlag("custom-sigquit-handler", "", nil, nil, "Handler customizado de SIGQUIT (só Engine).", sglangGroupServidorEGeral, false),
		boolFlag("sleep-on-idle", "", nil, false, "Reduz uso de CPU quando ocioso.", sglangGroupServidorEGeral),
		intFlag("base-gpu-id", "", nil, 0, "GPU inicial para alocação.", sglangGroupServidorEGeral, nil, nil),
		intFlag("gpu-id-step", "", nil, 1, "Passo entre IDs de GPU (ex.: `2` usa GPU 0,2,4…).", sglangGroupServidorEGeral, nil, nil),
		strFlag("numa-node", "", nil, nil, "NUMA node de cada subprocesso.", sglangGroupServidorEGeral, false),
		intFlag("scheduler-recv-interval", "", nil, nil, "Intervalo de polling de requisições no scheduler.", sglangGroupServidorEGeral, nil, nil),
		strFlag("tokenizer-path", "", nil, "= model-path", "Caminho do tokenizer.", sglangGroupModeloETokenizer, false),
		enumFlag("tokenizer-mode", "", nil, []string{"auto", "slow"}, "auto", "Modo do tokenizer (`auto` usa fast se disponível).", sglangGroupModeloETokenizer),
		intFlag("tokenizer-worker-num", "", nil, nil, "Workers do tokenizer manager.", sglangGroupModeloETokenizer, nil, nil),
		boolFlag("skip-tokenizer-init", "", nil, false, "Pula init do tokenizer; espera `input_ids`.", sglangGroupModeloETokenizer),
		boolFlag("trust-remote-code", "", nil, false, "Permite código customizado do Hub.", sglangGroupModeloETokenizer),
		intFlag("context-length", "", nil, nil, "Contexto máximo; `None` usa o do `config.json`.", sglangGroupModeloETokenizer, nil, nil),
		boolFlag("is-embedding", "", nil, false, "Usa um CausalLM como modelo de embedding.", sglangGroupModeloETokenizer),
		boolFlag("enable-multimodal", "", nil, false, "Habilita multimodalidade (ver [[#2. Modelo e tokenizer]]).", sglangGroupModeloETokenizer),
		strFlag("revision", "", nil, nil, "Versão específica do modelo no HF.", sglangGroupModeloETokenizer, false),
		enumFlag("model-impl", "", nil, []string{"auto", "sglang", "transformers", "mindspore"}, "auto", "Implementação do modelo.", sglangGroupModeloETokenizer),
		strFlag("served-model-name", "", nil, "= model-path", "Nome retornado por `/v1/models`.", sglangGroupModeloETokenizer, false),
		strFlag("weight-version", "", nil, "default", "Identificador de versão dos pesos (default `default`).", sglangGroupModeloETokenizer, false),
		strFlag("json-model-override-args", "", nil, nil, "Sobrescreve configs do modelo.", sglangGroupModeloETokenizer, false),
		strFlag("model-checksum", "", nil, nil, "Verificação de integridade dos arquivos do modelo.", sglangGroupModeloETokenizer, false),
		enumFlag("load-format", "", nil, []string{"auto", "pt", "safetensors", "npcache", "dummy", "sharded_state", "gguf", "bitsandbytes", "layered", "flash_rl", "remote", "remote_instance", "fastsafetensors", "private"}, "auto", "Formato dos pesos.", sglangGroupCarregamentoDePesos),
		strFlag("model-loader-extra-config", "", nil, nil, "Config extra do loader.", sglangGroupCarregamentoDePesos, false),
		strFlag("download-dir", "", nil, nil, "Diretório de download do HF.", sglangGroupCarregamentoDePesos, false),
		strFlag("custom-weight-loader", "", nil, nil, "Loader customizado de pesos.", sglangGroupCarregamentoDePesos, false),
		boolFlag("weight-loader-disable-mmap", "", nil, false, "Desativa mmap ao carregar safetensors.", sglangGroupCarregamentoDePesos),
		boolFlag("delete-ckpt-after-loading", "", nil, false, "Apaga o checkpoint após carregar.", sglangGroupCarregamentoDePesos),
		strFlag("decrypted-config-file", "", nil, nil, "Arquivo de config descriptografado.", sglangGroupCarregamentoDePesos, false),
		strFlag("decrypted-draft-config-file", "", nil, nil, "Config descriptografado do modelo draft.", sglangGroupCarregamentoDePesos, false),
		strFlag("remote-instance-weight-loader-seed-instance-ip", "", nil, nil, "IP da instância seed (load remoto).", sglangGroupCarregamentoDePesos, false),
		intFlag("remote-instance-weight-loader-seed-instance-service-port", "", nil, nil, "Porta de serviço da seed.", sglangGroupCarregamentoDePesos, nil, nil),
		intFlag("remote-instance-weight-loader-send-weights-group-ports", "", nil, nil, "Portas do grupo de comunicação.", sglangGroupCarregamentoDePesos, nil, nil),
		enumFlag("remote-instance-weight-loader-backend", "", nil, []string{"transfer_engine", "nccl"}, nil, "Backend do load remoto (default `nccl`).", sglangGroupCarregamentoDePesos),
		boolFlag("remote-instance-weight-loader-start-seed-via-transfer-engine", "", nil, false, "Inicia o seed via transfer engine.", sglangGroupCarregamentoDePesos),
		enumFlag("dtype", "", nil, []string{"auto", "half", "float16", "bfloat16", "float", "float32"}, "auto", "Dtype de pesos/ativações.", sglangGroupDtypeEQuantizacao),
		enumFlag("quantization", "", nil, []string{"awq", "fp8", "mxfp8", "gptq", "marlin", "gptq_marlin", "awq_marlin", "bitsandbytes", "gguf", "mxfp4", "compressed-tensors"}, "None", "Método de quantização.", sglangGroupDtypeEQuantizacao),
		strFlag("quantization-param-path", "", nil, nil, "Escalas do KV cache (para KV fp8).", sglangGroupDtypeEQuantizacao, false),
		enumFlag("kv-cache-dtype", "", nil, []string{"auto", "fp8_e5m2", "fp8_e4m3", "bf16", "bfloat16", "fp4_e2m1"}, "auto", "Dtype do KV cache.", sglangGroupDtypeEQuantizacao),
		boolFlag("enable-fp32-lm-head", "", nil, false, "LM head (logits) em FP32.", sglangGroupDtypeEQuantizacao),
		enumFlag("modelopt-quant", "", nil, []string{"fp8", "int4_awq", "w4a8_awq", "nvfp4", "nvfp4_awq"}, nil, "Config de quantização ModelOpt.", sglangGroupDtypeEQuantizacao),
		strFlag("modelopt-checkpoint-restore-path", "", nil, nil, "Restaura checkpoint ModelOpt quantizado.", sglangGroupDtypeEQuantizacao, false),
		strFlag("modelopt-checkpoint-save-path", "", nil, nil, "Salva checkpoint ModelOpt quantizado.", sglangGroupDtypeEQuantizacao, false),
		intFlag("modelopt-export-path", "", nil, nil, "Exporta o modelo quantizado em formato HF.", sglangGroupDtypeEQuantizacao, nil, nil),
		boolFlag("quantize-and-serve", "", nil, false, "Quantiza com ModelOpt e serve direto (dev/proto).", sglangGroupDtypeEQuantizacao),
		strFlag("rl-quant-profile", "", nil, nil, "Profile FlashRL (exigido por `--load-format flash_rl`).", sglangGroupDtypeEQuantizacao, false),
		strFlag("torchao-config", "", nil, nil, "Otimização via torchao (`int8dq`, `int4wo-<g>`, `fp8wo`,…).", sglangGroupDtypeEQuantizacao, false),
		floatFlag("mem-fraction-static", "", nil, nil, "Fração de memória para alocação estática (pesos + pool de KV).", sglangGroupMemoriaEKvCache, nil, nil),
		intFlag("max-running-requests", "", nil, nil, "Máx. de requisições em execução.", sglangGroupMemoriaEKvCache, nil, nil),
		intFlag("max-queued-requests", "", nil, nil, "Máx. de requisições na fila (ignorado em disaggregation).", sglangGroupMemoriaEKvCache, nil, nil),
		intFlag("max-total-tokens", "", nil, nil, "Máx. de tokens no memory pool (geralmente p/ debug).", sglangGroupMemoriaEKvCache, nil, nil),
		intFlag("page-size", "", nil, nil, "Nº de tokens por página.", sglangGroupMemoriaEKvCache, nil, nil),
		intFlag("max-mamba-cache-size", "", nil, nil, "Tamanho máx. do cache Mamba (ver [[#13. Mamba (SSM)]]).", sglangGroupMemoriaEKvCache, nil, nil),
		floatFlag("swa-full-tokens-ratio", "", nil, nil, "Razão de tokens KV de camadas SWA / full.", sglangGroupMemoriaEKvCache, nil, nil),
		boolFlag("disable-hybrid-swa-memory", "", nil, false, "Desliga o pool de memória híbrido para SWA.", sglangGroupMemoriaEKvCache),
		floatFlag("hybrid-kvcache-ratio", "", nil, nil, "Substituído por `--swa-full-tokens-ratio`.", sglangGroupMemoriaEKvCache, nil, nil),
		boolFlag("disable-radix-cache", "", nil, false, "Desliga o RadixAttention (prefix caching).", sglangGroupCacheDePrefixoRadixEHierarquico),
		enumFlag("radix-eviction-policy", "", nil, []string{"lru", "lfu"}, "lru", "Política de evicção do radix tree.", sglangGroupCacheDePrefixoRadixEHierarquico),
		boolFlag("enable-hierarchical-cache", "", nil, false, "Habilita cache hierárquico (HiCache).", sglangGroupCacheDePrefixoRadixEHierarquico),
		floatFlag("hicache-ratio", "", nil, nil, "Tamanho do pool host / device.", sglangGroupCacheDePrefixoRadixEHierarquico, nil, nil),
		floatFlag("hicache-size", "", nil, nil, "Tamanho do pool host em GB (sobrescreve o ratio).", sglangGroupCacheDePrefixoRadixEHierarquico, nil, nil),
		enumFlag("hicache-write-policy", "", nil, []string{"write_back", "write_through", "write_through_selective"}, nil, "Política de escrita do HiCache.", sglangGroupCacheDePrefixoRadixEHierarquico),
		enumFlag("hicache-io-backend", "", nil, []string{"direct", "kernel", "kernel_ascend"}, nil, "Backend de I/O CPU↔GPU.", sglangGroupCacheDePrefixoRadixEHierarquico),
		enumFlag("hicache-mem-layout", "", nil, []string{"layer_first", "page_first"}, nil, "Layout do pool de memória host.", sglangGroupCacheDePrefixoRadixEHierarquico),
		boolFlag("disable-hicache-numa-detect", "", nil, false, "Não fixa o processo ao NUMA mais próximo da GPU.", sglangGroupCacheDePrefixoRadixEHierarquico),
		enumFlag("hicache-storage-backend", "", nil, []string{"file", "mooncake", "hf3fs", "nixl", "aibrix", "dynamic", "eic"}, nil, "Backend de storage do KV hierárquico.", sglangGroupCacheDePrefixoRadixEHierarquico),
		enumFlag("hicache-storage-prefetch-policy", "", nil, []string{"best_effort", "wait_complete", "timeout"}, nil, "Quando parar o prefetch do storage.", sglangGroupCacheDePrefixoRadixEHierarquico),
		strFlag("hicache-storage-backend-extra-config", "", nil, nil, "Config extra do backend de storage.", sglangGroupCacheDePrefixoRadixEHierarquico, false),
		boolFlag("enable-lmcache", "", nil, false, "Usa LMCache como cache hierárquico alternativo.", sglangGroupCacheDePrefixoRadixEHierarquico),
		intFlag("chunked-prefill-size", "", nil, nil, "Tokens por chunk no chunked prefill; `-1` desativa.", sglangGroupPrefillChunkingEScheduler, nil, nil),
		intFlag("prefill-max-requests", "", nil, nil, "Máx. de requisições num batch de prefill.", sglangGroupPrefillChunkingEScheduler, nil, nil),
		boolFlag("enable-dynamic-chunking", "", nil, false, "Ajuste dinâmico do tamanho de chunk (pipeline parallel).", sglangGroupPrefillChunkingEScheduler),
		intFlag("max-prefill-tokens", "", nil, nil, "Máx. de tokens num batch de prefill.", sglangGroupPrefillChunkingEScheduler, nil, nil),
		boolFlag("enable-mixed-chunk", "", nil, false, "Mistura prefill e decode num batch (com chunked prefill).", sglangGroupPrefillChunkingEScheduler),
		boolFlag("disable-chunked-prefix-cache", "", nil, false, "Desliga chunked prefix cache (DeepSeek).", sglangGroupPrefillChunkingEScheduler),
		enumFlag("schedule-policy", "", nil, []string{"lpm", "random", "fcfs", "dfs-weight", "lof", "priority", "routing-key"}, nil, "Política de escalonamento.", sglangGroupPrefillChunkingEScheduler),
		boolFlag("enable-priority-scheduling", "", nil, false, "Habilita escalonamento por prioridade.", sglangGroupPrefillChunkingEScheduler),
		boolFlag("abort-on-priority-when-disabled", "", nil, false, "Aborta requisições com prioridade quando o modo está off.", sglangGroupPrefillChunkingEScheduler),
		boolFlag("schedule-low-priority-values-first", "", nil, false, "Prioridade menor = agendada primeiro.", sglangGroupPrefillChunkingEScheduler),
		floatFlag("priority-scheduling-preemption-threshold", "", nil, nil, "Diferença mínima de prioridade para preempção.", sglangGroupPrefillChunkingEScheduler, nil, nil),
		strFlag("schedule-conservativeness", "", nil, nil, "Quão conservador é o scheduler (maior = mais).", sglangGroupPrefillChunkingEScheduler, false),
		intFlag("num-continuous-decode-steps", "", nil, 1, "Passos de decode contínuos por agendamento (default `1`).", sglangGroupPrefillChunkingEScheduler, nil, nil),
		boolFlag("disable-overlap-schedule", "", nil, false, "Desliga o overlap scheduler (CPU × GPU worker).", sglangGroupPrefillChunkingEScheduler),
		boolFlag("enable-prefill-delayer", "", nil, false, "Atrasa prefill em DP attention para reduzir ociosidade.", sglangGroupPrefillChunkingEScheduler),
		intFlag("prefill-delayer-max-delay-passes", "", nil, nil, "Máx. de forward passes para atrasar prefill.", sglangGroupPrefillChunkingEScheduler, nil, nil),
		strFlag("prefill-delayer-token-usage-low-watermark", "", nil, nil, "Watermark de uso de tokens do delayer.", sglangGroupPrefillChunkingEScheduler, false),
		intFlag("stream-interval", "", nil, nil, "Intervalo/buffer de streaming (em tokens).", sglangGroupStreamingSamplingEGramatica, nil, nil),
		boolFlag("stream-output", "", nil, false, "Saída em segmentos disjuntos.", sglangGroupStreamingSamplingEGramatica),
		intFlag("random-seed", "", nil, nil, "Seed do RNG.", sglangGroupStreamingSamplingEGramatica, nil, nil),
		enumFlag("sampling-defaults", "", nil, []string{"openai", "model"}, "model", "Origem dos defaults de sampling (default `model`).", sglangGroupStreamingSamplingEGramatica),
		strFlag("preferred-sampling-params", "", nil, nil, "Sampling retornado em `/get_model_info`.", sglangGroupStreamingSamplingEGramatica, false),
		enumFlag("grammar-backend", "", nil, []string{"xgrammar", "outlines", "llguidance", "none"}, nil, "Backend de decoding guiado por gramática.", sglangGroupStreamingSamplingEGramatica),
		strFlag("constrained-json-whitespace-pattern", "", nil, nil, "Whitespaces permitidos em JSON constrito (outlines/llguidance).", sglangGroupStreamingSamplingEGramatica, false),
		boolFlag("constrained-json-disable-any-whitespace", "", nil, false, "Representação compacta em JSON constrito (xgrammar/llguidance).", sglangGroupStreamingSamplingEGramatica),
		enumFlag("device", "", nil, []string{"cuda", "xpu", "hpu", "npu", "cpu"}, nil, "Dispositivo (auto-detecção por padrão).", sglangGroupParalelismoEExecucaoDistribuida),
		intFlag("tensor-parallel-size", "", nil, 1, "Tamanho do tensor parallelism.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		intFlag("tp-size", "", nil, 1, "Tensor parallelism (default `1`).", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		intFlag("pipeline-parallel-size", "", nil, 1, "Tamanho do pipeline parallelism.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		intFlag("pp-size", "", nil, 1, "Tamanho do pipeline parallelism.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		intFlag("data-parallel-size", "", nil, 1, "Tamanho do data parallelism.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		intFlag("dp-size", "", nil, 1, "Tamanho do data parallelism.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		intFlag("attention-context-parallel-size", "", nil, 1, "Context parallelism na atenção.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		intFlag("attn-cp-size", "", nil, 1, "Context parallelism na atenção.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		intFlag("moe-data-parallel-size", "", nil, nil, "DP nas camadas MoE.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		intFlag("moe-dp-size", "", nil, nil, "DP nas camadas MoE.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		intFlag("pp-max-micro-batch-size", "", nil, nil, "Máx. micro-batch no pipeline.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		intFlag("pp-async-batch-depth", "", nil, nil, "Profundidade de batch assíncrono do PP.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		enumFlag("load-balance-method", "", nil, []string{"auto", "round_robin", "follow_bootstrap_room", "total_requests", "total_tokens"}, nil, "Estratégia de LB do DP.", sglangGroupParalelismoEExecucaoDistribuida),
		intFlag("dist-init-addr", "", nil, nil, "Endereço de init do backend distribuído.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		intFlag("nccl-init-addr", "", nil, nil, "Endereço de init do backend distribuído.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		intFlag("nnodes", "", nil, 1, "Número de nós.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		intFlag("node-rank", "", nil, 0, "Rank do nó.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		boolFlag("enable-dp-attention", "", nil, false, "DP na atenção + TP no FFN (dp size = tp size).", sglangGroupParalelismoEExecucaoDistribuida),
		boolFlag("enable-dp-lm-head", "", nil, false, "Vocab parallel no grupo TP da atenção (sob DP attention).", sglangGroupParalelismoEExecucaoDistribuida),
		boolFlag("enable-attn-tp-input-scattered", "", nil, false, "Input da atenção espalhado (só TP), reduz carga de qkv latent.", sglangGroupParalelismoEExecucaoDistribuida),
		intFlag("moe-dense-tp-size", "", nil, nil, "TP das camadas MLP densas de MoE.", sglangGroupParalelismoEExecucaoDistribuida, nil, nil),
		intFlag("expert-parallel-size", "", nil, 1, "Tamanho do expert parallelism.", sglangGroupMoeEExpertParallelism, nil, nil),
		intFlag("ep-size", "", nil, 1, "Tamanho do expert parallelism.", sglangGroupMoeEExpertParallelism, nil, nil),
		intFlag("ep", "", nil, 1, "Tamanho do expert parallelism.", sglangGroupMoeEExpertParallelism, nil, nil),
		enumFlag("moe-a2a-backend", "", nil, []string{"none", "deepep", "mooncake", "mori", "ascend_fuseep", "flashinfer"}, "none", "Backend de comunicação A2A do MoE.", sglangGroupMoeEExpertParallelism),
		enumFlag("moe-runner-backend", "", nil, []string{"auto", "deep_gemm", "triton", "triton_kernel", "cutlass"}, "auto", "Backend de cálculo dos experts.", sglangGroupMoeEExpertParallelism),
		enumFlag("flashinfer-mxfp4-moe-precision", "", nil, []string{"default", "bf16"}, nil, "Precisão do MoE mxfp4 do FlashInfer.", sglangGroupMoeEExpertParallelism),
		boolFlag("enable-flashinfer-allreduce-fusion", "", nil, false, "Fusão allreduce + Residual RMSNorm (FlashInfer).", sglangGroupMoeEExpertParallelism),
		enumFlag("deepep-mode", "", nil, []string{"normal", "low_latency", "auto"}, "auto", "Modo do DeepEP MoE (default `auto`).", sglangGroupMoeEExpertParallelism),
		intFlag("ep-num-redundant-experts", "", nil, nil, "Experts redundantes no EP.", sglangGroupMoeEExpertParallelism, nil, nil),
		strFlag("ep-dispatch-algorithm", "", nil, nil, "Algoritmo de escolha de ranks p/ experts redundantes.", sglangGroupMoeEExpertParallelism, false),
		strFlag("init-expert-location", "", nil, nil, "Localização inicial dos experts EP.", sglangGroupMoeEExpertParallelism, false),
		boolFlag("enable-eplb", "", nil, false, "Habilita o algoritmo EPLB (load balancing de experts).", sglangGroupMoeEExpertParallelism),
		strFlag("eplb-algorithm", "", nil, nil, "Algoritmo EPLB.", sglangGroupMoeEExpertParallelism, false),
		intFlag("eplb-rebalance-num-iterations", "", nil, nil, "Iterações para disparar rebalance automático.", sglangGroupMoeEExpertParallelism, nil, nil),
		intFlag("eplb-rebalance-layers-per-chunk", "", nil, nil, "Camadas rebalanceadas por forward pass.", sglangGroupMoeEExpertParallelism, nil, nil),
		floatFlag("eplb-min-rebalancing-utilization-threshold", "", nil, nil, "Utilização mínima da GPU para rebalancear.", sglangGroupMoeEExpertParallelism, nil, nil),
		strFlag("expert-distribution-recorder-mode", "", nil, nil, "Modo do gravador de distribuição de experts.", sglangGroupMoeEExpertParallelism, false),
		intFlag("expert-distribution-recorder-buffer-size", "", nil, nil, "Buffer circular do gravador (`-1` = infinito).", sglangGroupMoeEExpertParallelism, nil, nil),
		boolFlag("enable-expert-distribution-metrics", "", nil, false, "Métricas de balanceamento de experts.", sglangGroupMoeEExpertParallelism),
		strFlag("deepep-config", "", nil, nil, "Config DeepEP afinada para o cluster.", sglangGroupMoeEExpertParallelism, false),
		enumFlag("elastic-ep-backend", "", nil, []string{"none", "mooncake"}, nil, "Backend de comunicação para EP elástico.", sglangGroupMoeEExpertParallelism),
		strFlag("mooncake-ib-device", "", nil, nil, "Dispositivos InfiniBand do Mooncake.", sglangGroupMoeEExpertParallelism, false),
		boolFlag("disable-shared-experts-fusion", "", nil, false, "Desliga fusão de shared experts (DeepSeek v3/r1).", sglangGroupMoeEExpertParallelism),
		enumFlag("attention-backend", "", nil, []string{"triton", "torch_native", "flex_attention", "nsa", "cutlass_mla", "fa3", "fa4", "flashinfer", "flashmla", "trtllm_mla", "trtllm_mha", "dual_chunk_flash_attn", "aiter", "wave", "intel_amx", "ascend", "intel_xpu"}, nil, "Backend de atenção (`fa`, `torch_sdpa`, `sage_attn`, …).", sglangGroupBackendsDeAtencaoEGemm),
		strFlag("prefill-attention-backend", "", nil, "= attention-backend", "Kernels só do prefill (prioridade sobre o geral).", sglangGroupBackendsDeAtencaoEGemm, false),
		strFlag("decode-attention-backend", "", nil, "= attention-backend", "Kernels só do decode (prioridade sobre o geral).", sglangGroupBackendsDeAtencaoEGemm, false),
		enumFlag("sampling-backend", "", nil, []string{"pytorch", "flashinfer", "ascend"}, nil, "Kernels de sampling.", sglangGroupBackendsDeAtencaoEGemm),
		enumFlag("mm-attention-backend", "", nil, []string{"sdpa", "fa3", "fa4", "triton_attn", "ascend_attn", "aiter_attn"}, nil, "Backend de atenção multimodal.", sglangGroupBackendsDeAtencaoEGemm),
		enumFlag("fp8-gemm-backend", "", nil, []string{"auto", "deep_gemm", "flashinfer_trtllm", "flashinfer_deepgemm", "cutlass", "triton", "aiter"}, "auto", "Runner de GEMM FP8 blockwise.", sglangGroupBackendsDeAtencaoEGemm),
		enumFlag("fp4-gemm-backend", "", nil, []string{"auto", "flashinfer_cudnn", "flashinfer_cutlass", "flashinfer_trtllm"}, "flashinfer_cutlass", "Runner de GEMM NVFP4 (default `flashinfer_cutlass`).", sglangGroupBackendsDeAtencaoEGemm),
		boolFlag("disable-flashinfer-autotune", "", nil, false, "Desliga o autotuning do FlashInfer.", sglangGroupBackendsDeAtencaoEGemm),
		boolFlag("flashinfer-mla-disable-ragged", "", nil, false, "Não usa ragged prefill wrapper no FlashInfer MLA.", sglangGroupBackendsDeAtencaoEGemm),
		boolFlag("enable-fused-qk-norm-rope", "", nil, false, "Funde normalização QK + RoPE.", sglangGroupBackendsDeAtencaoEGemm),
		boolFlag("triton-attention-reduce-in-fp32", "", nil, false, "Reduz resultados intermediários da atenção em FP32 (Triton).", sglangGroupBackendsDeAtencaoEGemm),
		intFlag("triton-attention-num-kv-splits", "", nil, 8, "Nº de KV splits no flash decoding Triton (default `8`).", sglangGroupBackendsDeAtencaoEGemm, nil, nil),
		intFlag("triton-attention-split-tile-size", "", nil, nil, "Tamanho do tile de KV split (Triton).", sglangGroupBackendsDeAtencaoEGemm, nil, nil),
		enumFlag("nsa-prefill-backend", "", nil, []string{"flashmla_sparse", "flashmla_kv", "flashmla_auto", "fa3", "tilelang", "aiter", "trtllm"}, nil, "Backend NSA de prefill.", sglangGroupAtencaoEsparsaNsaEDoubleSparsity),
		strFlag("nsa-decode-backend", "", nil, nil, "Backend NSA de decode.", sglangGroupAtencaoEsparsaNsaEDoubleSparsity, false),
		boolFlag("enable-nsa-prefill-context-parallel", "", nil, false, "Context parallel no prefill longo (DeepSeek v3.2).", sglangGroupAtencaoEsparsaNsaEDoubleSparsity),
		enumFlag("nsa-prefill-cp-mode", "", nil, []string{"in-seq-split", "round-robin-split"}, nil, "Modo de split de tokens no prefill NSA.", sglangGroupAtencaoEsparsaNsaEDoubleSparsity),
		boolFlag("enable-double-sparsity", "", nil, false, "Habilita double sparsity attention.", sglangGroupAtencaoEsparsaNsaEDoubleSparsity),
		strFlag("ds-channel-config-path", "", nil, nil, "Config de canais do double sparsity.", sglangGroupAtencaoEsparsaNsaEDoubleSparsity, false),
		intFlag("ds-heavy-channel-num", "", nil, nil, "Nº de \"heavy channels\".", sglangGroupAtencaoEsparsaNsaEDoubleSparsity, nil, nil),
		intFlag("ds-heavy-token-num", "", nil, nil, "Nº de \"heavy tokens\".", sglangGroupAtencaoEsparsaNsaEDoubleSparsity, nil, nil),
		strFlag("ds-heavy-channel-type", "", nil, nil, "Tipo de heavy channel.", sglangGroupAtencaoEsparsaNsaEDoubleSparsity, false),
		floatFlag("ds-sparse-decode-threshold", "", nil, nil, "Comprimento mínimo de decode p/ ativar o kernel esparso.", sglangGroupAtencaoEsparsaNsaEDoubleSparsity, nil, nil),
		strFlag("hierarchical-sparse-attention-extra-config", "", nil, nil, "Config de atenção esparsa hierárquica (ex.: `quest`).", sglangGroupAtencaoEsparsaNsaEDoubleSparsity, false),
		enumFlag("mamba-ssm-dtype", "", nil, []string{"float32", "bfloat16", "float16"}, nil, "Dtype dos estados SSM (default: do config).", sglangGroupMambaSsm),
		floatFlag("mamba-full-memory-ratio", "", nil, nil, "Memória do estado mamba / KV cache full.", sglangGroupMambaSsm, nil, nil),
		enumFlag("mamba-scheduler-strategy", "", nil, []string{"auto", "no_buffer", "extra_buffer"}, nil, "Estratégia do radix cache para Mamba.", sglangGroupMambaSsm),
		intFlag("mamba-track-interval", "", nil, nil, "Intervalo de tracking do estado mamba no decode.", sglangGroupMambaSsm, nil, nil),
		enumFlag("mamba-backend", "", nil, []string{"triton", "flashinfer"}, "triton", "Kernel das operações Mamba SSM (default `triton`).", sglangGroupMambaSsm),
		boolFlag("enable-lora", "", nil, false, "Habilita LoRA (auto-ativado se `--lora-paths` for usado).", sglangGroupLora),
		strFlag("lora-paths", "", nil, nil, "Adapters a carregar (`<PATH>`, `<NOME>=<PATH>` ou JSON).", sglangGroupLora, false),
		intFlag("max-lora-rank", "", nil, nil, "Rank máximo (inferido dos adapters se omitido).", sglangGroupLora, nil, nil),
		strFlag("lora-target-modules", "", nil, nil, "Módulos onde aplicar LoRA.", sglangGroupLora, false),
		intFlag("max-loras-per-batch", "", nil, nil, "Máx. de adapters num batch em execução.", sglangGroupLora, nil, nil),
		intFlag("max-loaded-loras", "", nil, nil, "Máx. de adapters em RAM (≥ `--max-loras-per-batch`).", sglangGroupLora, nil, nil),
		enumFlag("lora-eviction-policy", "", nil, []string{"lru", "fifo"}, "lru", "Política de evicção de LoRA (default `lru`).", sglangGroupLora),
		enumFlag("lora-backend", "", nil, []string{"triton", "csgmv", "ascend", "torch_native"}, nil, "Backend de kernels multi-LoRA.", sglangGroupLora),
		strFlag("max-lora-chunk-size", "", nil, nil, "Chunk máximo do backend `csgmv`.", sglangGroupLora, false),
		boolFlag("enable-lora-overlap-loading", "", nil, false, "Carregamento assíncrono de LoRA (overlap H2D × compute).", sglangGroupLora),
		enumFlag("speculative-algorithm", "", nil, []string{"EAGLE", "EAGLE3", "NEXTN", "STANDALONE", "NGRAM"}, nil, "Algoritmo de speculative decoding.", sglangGroupSpeculativeDecoding),
		strFlag("speculative-draft-model-path", "", nil, nil, "Modelo draft.", sglangGroupSpeculativeDecoding, false),
		strFlag("speculative-draft-model", "", nil, nil, "Modelo draft.", sglangGroupSpeculativeDecoding, false),
		strFlag("speculative-draft-model-revision", "", nil, nil, "Versão do draft.", sglangGroupSpeculativeDecoding, false),
		strFlag("speculative-draft-load-format", "", nil, nil, "Formato dos pesos do draft.", sglangGroupSpeculativeDecoding, false),
		strFlag("speculative-draft-model-quantization", "", nil, nil, "Quantização do draft.", sglangGroupSpeculativeDecoding, false),
		intFlag("speculative-num-steps", "", nil, nil, "Passos amostrados do draft.", sglangGroupSpeculativeDecoding, nil, nil),
		intFlag("speculative-eagle-topk", "", nil, nil, "Tokens amostrados do draft por passo (eagle2).", sglangGroupSpeculativeDecoding, nil, nil),
		intFlag("speculative-num-draft-tokens", "", nil, nil, "Tokens amostrados do draft.", sglangGroupSpeculativeDecoding, nil, nil),
		strFlag("speculative-accept-threshold-single", "", nil, nil, "Limiar de aceitação de um token draft.", sglangGroupSpeculativeDecoding, false),
		strFlag("speculative-accept-threshold-acc", "", nil, nil, "Eleva a prob. de aceitação para `min(1, p/threshold)`.", sglangGroupSpeculativeDecoding, false),
		strFlag("speculative-token-map", "", nil, nil, "Vocab reduzido do draft.", sglangGroupSpeculativeDecoding, false),
		enumFlag("speculative-attention-mode", "", nil, []string{"prefill", "decode"}, "prefill", "Backend de atenção do speculative (default `prefill`).", sglangGroupSpeculativeDecoding),
		strFlag("speculative-draft-attention-backend", "", nil, nil, "Backend de atenção da etapa de draft.", sglangGroupSpeculativeDecoding, false),
		strFlag("speculative-moe-runner-backend", "", nil, nil, "Runner MoE no speculative.", sglangGroupSpeculativeDecoding, false),
		strFlag("speculative-moe-a2a-backend", "", nil, nil, "A2A MoE no speculative.", sglangGroupSpeculativeDecoding, false),
		boolFlag("enable-multi-layer-eagle", "", nil, false, "Eagle de múltiplas camadas.", sglangGroupSpeculativeDecoding),
		enumFlag("speculative-ngram-match-type", "", nil, []string{"BFS", "PROB"}, nil, "Tipo de match da árvore de cache.", sglangGroupSpeculativeDecoding),
		intFlag("speculative-ngram-branch-length", "", nil, nil, "Comprimento de ramo (n-gram).", sglangGroupSpeculativeDecoding, nil, nil),
		intFlag("speculative-ngram-capacity", "", nil, nil, "Capacidade do cache (n-gram).", sglangGroupSpeculativeDecoding, nil, nil),
		boolFlag("disable-cuda-graph", "", nil, false, "Desliga CUDA graph.", sglangGroupCudaGraphETorchCompile),
		boolFlag("disable-cuda-graph-padding", "", nil, false, "Desliga CUDA graph quando há padding.", sglangGroupCudaGraphETorchCompile),
		intFlag("cuda-graph-max-bs", "", nil, nil, "Batch size máximo capturado em CUDA graph.", sglangGroupCudaGraphETorchCompile, nil, nil),
		strFlag("cuda-graph-bs", "", nil, nil, "Lista explícita de batch sizes a capturar.", sglangGroupCudaGraphETorchCompile, false),
		boolFlag("enable-profile-cuda-graph", "", nil, false, "Profiling da captura do CUDA graph.", sglangGroupCudaGraphETorchCompile),
		boolFlag("enable-cudagraph-gc", "", nil, false, "GC durante a captura (default: GC congelado p/ acelerar).", sglangGroupCudaGraphETorchCompile),
		boolFlag("enable-torch-compile", "", nil, false, "torch.compile no DiT (pode causar drift de precisão).", sglangGroupCudaGraphETorchCompile),
		boolFlag("enable-torch-compile-debug-mode", "", nil, false, "Modo debug do torch.compile.", sglangGroupCudaGraphETorchCompile),
		intFlag("torch-compile-max-bs", "", nil, nil, "Batch size máximo com torch.compile.", sglangGroupCudaGraphETorchCompile, nil, nil),
		boolFlag("enable-piecewise-cuda-graph", "", nil, false, "CUDA graph \"piecewise\" (só extend/prefill).", sglangGroupCudaGraphETorchCompile),
		strFlag("piecewise-cuda-graph-tokens", "", nil, nil, "Comprimentos de token p/ captura piecewise.", sglangGroupCudaGraphETorchCompile, false),
		intFlag("piecewise-cuda-graph-max-tokens", "", nil, nil, "Máx. de tokens no piecewise CUDA graph.", sglangGroupCudaGraphETorchCompile, nil, nil),
		enumFlag("piecewise-cuda-graph-compiler", "", nil, []string{"eager", "inductor"}, nil, "Compilador do piecewise CUDA graph.", sglangGroupCudaGraphETorchCompile),
		boolFlag("disable-custom-all-reduce", "", nil, false, "Desliga o all-reduce custom (usa NCCL).", sglangGroupComunicacaoEAllReduce),
		boolFlag("enable-mscclpp", "", nil, false, "Usa mscclpp para mensagens pequenas no all-reduce.", sglangGroupComunicacaoEAllReduce),
		boolFlag("enable-torch-symm-mem", "", nil, false, "Usa torch symm mem no all-reduce (SM90+).", sglangGroupComunicacaoEAllReduce),
		boolFlag("enable-symm-mem", "", nil, false, "NCCL symmetric memory para coletivas rápidas.", sglangGroupComunicacaoEAllReduce),
		boolFlag("enable-nccl-nvls", "", nil, false, "NCCL NVLS para prefills pesados (quando disponível).", sglangGroupComunicacaoEAllReduce),
		boolFlag("enable-p2p-check", "", nil, false, "Checa acesso P2P entre GPUs.", sglangGroupComunicacaoEAllReduce),
		boolFlag("disable-flashinfer-cutlass-moe-fp4-allgather", "", nil, false, "Não quantiza antes do all-gather (flashinfer cutlass MoE).", sglangGroupComunicacaoEAllReduce),
		floatFlag("cpu-offload-gb", "", nil, 0, "RAM reservada para offload de pesos para CPU.", sglangGroupOffloadDePesosEMemorySaver, nil, nil),
		intFlag("offload-group-size", "", nil, nil, "Camadas por grupo no offload.", sglangGroupOffloadDePesosEMemorySaver, nil, nil),
		intFlag("offload-num-in-group", "", nil, nil, "Camadas offloadadas por grupo.", sglangGroupOffloadDePesosEMemorySaver, nil, nil),
		intFlag("offload-prefetch-step", "", nil, nil, "Passos de prefetch no offload.", sglangGroupOffloadDePesosEMemorySaver, nil, nil),
		strFlag("offload-mode", "", nil, nil, "Modo de offload.", sglangGroupOffloadDePesosEMemorySaver, false),
		boolFlag("enable-memory-saver", "", nil, false, "Permite liberar/retomar a ocupação de memória.", sglangGroupOffloadDePesosEMemorySaver),
		boolFlag("enable-weights-cpu-backup", "", nil, false, "Backup dos pesos em RAM (release/resume).", sglangGroupOffloadDePesosEMemorySaver),
		boolFlag("enable-draft-weights-cpu-backup", "", nil, false, "Backup dos pesos do draft em RAM.", sglangGroupOffloadDePesosEMemorySaver),
		strFlag("kt-weight-path", "", nil, nil, "[ktransformers] Pesos de experts quantizados (AMX).", sglangGroupOffloadDePesosEMemorySaver, false),
		strFlag("kt-method", "", nil, nil, "[ktransformers] Formato de quantização para CPU.", sglangGroupOffloadDePesosEMemorySaver, false),
		intFlag("kt-cpuinfer", "", nil, nil, "[ktransformers] Threads de CPUInfer.", sglangGroupOffloadDePesosEMemorySaver, nil, nil),
		intFlag("kt-threadpool-count", "", nil, nil, "[ktransformers] Thread pools (1 por NUMA).", sglangGroupOffloadDePesosEMemorySaver, nil, nil),
		intFlag("kt-num-gpu-experts", "", nil, nil, "[ktransformers] Nº de experts na GPU.", sglangGroupOffloadDePesosEMemorySaver, nil, nil),
		intFlag("kt-max-deferred-experts-per-token", "", nil, nil, "[ktransformers] Experts adiados para CPU por token.", sglangGroupOffloadDePesosEMemorySaver, nil, nil),
		strFlag("limit-mm-data-per-request", "", nil, nil, "Limite de inputs MM por requisição (ex.: `{\"image\":1}`).", sglangGroupMultimodalEEncoder, false),
		intFlag("mm-max-concurrent-calls", "", nil, nil, "Chamadas concorrentes no processamento async de MM.", sglangGroupMultimodalEEncoder, nil, nil),
		intFlag("mm-per-request-timeout", "", nil, nil, "Timeout por requisição multimodal.", sglangGroupMultimodalEEncoder, nil, nil),
		boolFlag("enable-broadcast-mm-inputs-process", "", nil, false, "Broadcast do processo de mm-inputs no scheduler.", sglangGroupMultimodalEEncoder),
		strFlag("mm-process-config", "", nil, nil, "Config de pré-processamento MM (`image`/`video`/`audio`).", sglangGroupMultimodalEEncoder, false),
		boolFlag("mm-enable-dp-encoder", "", nil, false, "DP no encoder MM (dp size = tp size).", sglangGroupMultimodalEEncoder),
		boolFlag("disable-fast-image-processor", "", nil, false, "Usa o image processor base (não o rápido).", sglangGroupMultimodalEEncoder),
		boolFlag("keep-mm-feature-on-device", "", nil, false, "Mantém features MM no device (evita cópia D2H).", sglangGroupMultimodalEEncoder),
		boolFlag("enable-prefix-mm-cache", "", nil, false, "Cache de prefixo multimodal (mm-only).", sglangGroupMultimodalEEncoder),
		boolFlag("encoder-only", "", nil, false, "Sobe um servidor só de encoder (MLLM).", sglangGroupMultimodalEEncoder),
		boolFlag("language-only", "", nil, false, "Carrega só o LM (VLM).", sglangGroupMultimodalEEncoder),
		enumFlag("encoder-transfer-backend", "", nil, []string{"zmq_to_scheduler", "zmq_to_tokenizer", "mooncake"}, nil, "Backend de transferência do encoder.", sglangGroupMultimodalEEncoder),
		strFlag("encoder-urls", "", nil, nil, "URLs de servidores de encoder.", sglangGroupMultimodalEEncoder, false),
		strFlag("api-key", "", nil, nil, "Chave de API do servidor (OpenAI-compatível).", sglangGroupApiOpenaiEParsers, false),
		strFlag("admin-api-key", "", nil, nil, "Chave de endpoints administrativos sensíveis.", sglangGroupApiOpenaiEParsers, false),
		strFlag("chat-template", "", nil, nil, "Template de chat (OpenAI-compatível).", sglangGroupApiOpenaiEParsers, false),
		strFlag("hf-chat-template-name", "", nil, nil, "Qual template nomeado do HF usar (`tool_use`, `rag`,…).", sglangGroupApiOpenaiEParsers, false),
		strFlag("completion-template", "", nil, nil, "Template de completion (code completion).", sglangGroupApiOpenaiEParsers, false),
		strFlag("file-storage-path", "", nil, nil, "Path do file storage do backend.", sglangGroupApiOpenaiEParsers, false),
		boolFlag("enable-cache-report", "", nil, false, "Reporta tokens em cache em `usage.prompt_tokens_details`.", sglangGroupApiOpenaiEParsers),
		enumFlag("reasoning-parser", "", nil, []string{"deepseek-r1", "deepseek-v3", "glm45", "gpt-oss", "kimi", "qwen3"}, nil, "Parser de modelos de raciocínio.", sglangGroupApiOpenaiEParsers),
		enumFlag("tool-call-parser", "", nil, []string{"deepseekv3", "glm", "gpt-oss", "kimi_k2", "llama3", "mistral", "qwen", "hermes"}, nil, "Parser de tool calls.", sglangGroupApiOpenaiEParsers),
		strFlag("tool-server", "", nil, nil, "Servidor(es) de ferramentas.", sglangGroupApiOpenaiEParsers, false),
		strFlag("multi-item-scoring-delimiter", "", nil, nil, "Delimitador para multi-item scoring.", sglangGroupApiOpenaiEParsers, false),
		boolFlag("allow-auto-truncate", "", nil, false, "Trunca automaticamente requisições longas (em vez de erro).", sglangGroupApiOpenaiEParsers),
		boolFlag("enable-custom-logit-processor", "", nil, false, "Permite logit processors customizados (off por segurança).", sglangGroupApiOpenaiEParsers),
		boolFlag("enable-return-hidden-states", "", nil, false, "Retorna hidden states nas respostas.", sglangGroupApiOpenaiEParsers),
		boolFlag("enable-return-routed-experts", "", nil, false, "Retorna experts roteados por camada.", sglangGroupApiOpenaiEParsers),
		strFlag("log-level", "", nil, nil, "Nível de log de todos os loggers.", sglangGroupLoggingMetricasETracing, false),
		strFlag("log-level-http", "", nil, nil, "Nível de log do servidor HTTP (herda `--log-level`).", sglangGroupLoggingMetricasETracing, false),
		boolFlag("log-requests", "", nil, false, "Loga metadados/inputs/outputs das requisições.", sglangGroupLoggingMetricasETracing),
		strFlag("log-requests-level", "", nil, "0", "Verbosidade do log de requisições.", sglangGroupLoggingMetricasETracing, false),
		enumFlag("log-requests-format", "", nil, []string{"text", "json"}, nil, "Formato do log de requisições.", sglangGroupLoggingMetricasETracing),
		strFlag("log-requests-target", "", nil, nil, "Destino(s) do log de requisições.", sglangGroupLoggingMetricasETracing, false),
		strFlag("uvicorn-access-log-exclude-prefixes", "", nil, nil, "Exclui access logs por prefixo de rota (ex.: `/metrics`).", sglangGroupLoggingMetricasETracing, false),
		strFlag("crash-dump-folder", "", nil, nil, "Dump das requisições dos últimos 5 min antes de um crash.", sglangGroupLoggingMetricasETracing, false),
		boolFlag("show-time-cost", "", nil, false, "Mostra custo de tempo de marcas customizadas.", sglangGroupLoggingMetricasETracing),
		boolFlag("enable-metrics", "", nil, false, "Habilita métricas Prometheus.", sglangGroupLoggingMetricasETracing),
		boolFlag("enable-metrics-for-all-schedulers", "", nil, false, "Métricas de todos os ranks TP (não só TP 0).", sglangGroupLoggingMetricasETracing),
		strFlag("tokenizer-metrics-custom-labels-header", "", nil, nil, "Header HTTP de labels custom de métricas do tokenizer.", sglangGroupLoggingMetricasETracing, false),
		strFlag("tokenizer-metrics-allowed-custom-labels", "", nil, nil, "Labels custom permitidos.", sglangGroupLoggingMetricasETracing, false),
		strFlag("extra-metric-labels", "", nil, nil, "Labels custom para métricas.", sglangGroupLoggingMetricasETracing, false),
		strFlag("bucket-time-to-first-token", "", nil, nil, "Buckets de TTFT.", sglangGroupLoggingMetricasETracing, false),
		strFlag("bucket-inter-token-latency", "", nil, nil, "Buckets de inter-token latency.", sglangGroupLoggingMetricasETracing, false),
		strFlag("bucket-e2e-request-latency", "", nil, nil, "Buckets de latência e2e.", sglangGroupLoggingMetricasETracing, false),
		boolFlag("collect-tokens-histogram", "", nil, false, "Histograma de tokens de prompt/geração.", sglangGroupLoggingMetricasETracing),
		strFlag("prompt-tokens-buckets", "", nil, nil, "Buckets (`default`/`tse`/`custom`).", sglangGroupLoggingMetricasETracing, false),
		strFlag("generation-tokens-buckets", "", nil, nil, "Buckets (`default`/`tse`/`custom`).", sglangGroupLoggingMetricasETracing, false),
		intFlag("gc-warning-threshold-secs", "", nil, nil, "Aviso de GC longo (`0` desativa).", sglangGroupLoggingMetricasETracing, nil, nil),
		intFlag("decode-log-interval", "", nil, nil, "Intervalo de log do batch de decode.", sglangGroupLoggingMetricasETracing, nil, nil),
		boolFlag("enable-request-time-stats-logging", "", nil, false, "Stats de tempo por requisição.", sglangGroupLoggingMetricasETracing),
		strFlag("kv-events-config", "", nil, nil, "Publicação de eventos de KV (NVIDIA Dynamo).", sglangGroupLoggingMetricasETracing, false),
		boolFlag("enable-trace", "", nil, false, "Habilita tracing OpenTelemetry.", sglangGroupLoggingMetricasETracing),
		intFlag("otlp-traces-endpoint", "", nil, nil, "Endpoint do coletor OpenTelemetry.", sglangGroupLoggingMetricasETracing, nil, nil),
		boolFlag("export-metrics-to-file", "", nil, false, "Exporta métricas por requisição para arquivo.", sglangGroupLoggingMetricasETracing),
		strFlag("export-metrics-to-file-dir", "", nil, nil, "Diretório dos arquivos de métricas.", sglangGroupLoggingMetricasETracing, false),
		enumFlag("disaggregation-mode", "", nil, []string{"null", "prefill", "decode"}, "null", "Papel do servidor (PD disaggregation).", sglangGroupPdDisaggregation),
		enumFlag("disaggregation-transfer-backend", "", nil, []string{"mooncake", "nixl", "ascend", "fake", "mori"}, "mooncake", "Backend de transferência (default `mooncake`).", sglangGroupPdDisaggregation),
		intFlag("disaggregation-bootstrap-port", "", nil, 8998, "Porta do bootstrap no prefill (default `8998`).", sglangGroupPdDisaggregation, nil, nil),
		intFlag("disaggregation-decode-tp", "", nil, nil, "TP do decode (setado no prefill).", sglangGroupPdDisaggregation, nil, nil),
		intFlag("disaggregation-decode-dp", "", nil, nil, "DP do decode (setado no prefill).", sglangGroupPdDisaggregation, nil, nil),
		intFlag("disaggregation-prefill-pp", "", nil, 1, "PP do prefill (setado no decode; default `1`).", sglangGroupPdDisaggregation, nil, nil),
		strFlag("disaggregation-ib-device", "", nil, nil, "Dispositivos InfiniBand da transferência.", sglangGroupPdDisaggregation, false),
		boolFlag("disaggregation-decode-enable-offload-kvcache", "", nil, false, "Offload async de KV no decode.", sglangGroupPdDisaggregation),
		intFlag("num-reserved-decode-tokens", "", nil, nil, "Tokens de decode com memória reservada por requisição.", sglangGroupPdDisaggregation, nil, nil),
		intFlag("disaggregation-decode-polling-interval", "", nil, nil, "Intervalo de polling no decode server.", sglangGroupPdDisaggregation, nil, nil),
		boolFlag("enable-deterministic-inference", "", nil, false, "Inferência determinística (ops batch-invariant).", sglangGroupDebugDeterminismoEDiversos),
		boolFlag("enable-nan-detection", "", nil, false, "Detecção de NaN (debug).", sglangGroupDebugDeterminismoEDiversos),
		strFlag("debug-tensor-dump-output-folder", "", nil, nil, "Pasta para dump de tensores.", sglangGroupDebugDeterminismoEDiversos, false),
		strFlag("debug-tensor-dump-layers", "", nil, nil, "Camadas a dumpar (todas se omitido).", sglangGroupDebugDeterminismoEDiversos, false),
		strFlag("debug-tensor-dump-input-file", "", nil, nil, "Arquivo de input para dump.", sglangGroupDebugDeterminismoEDiversos, false),
		strFlag("debug-tensor-dump-inject", "", nil, nil, "Injeta saídas como input de cada camada.", sglangGroupDebugDeterminismoEDiversos, false),
		boolFlag("enable-tokenizer-batch-encode", "", nil, false, "Tokenização em batch (não usar com imagens/ids).", sglangGroupDebugDeterminismoEDiversos),
		boolFlag("disable-tokenizer-batch-decode", "", nil, false, "Desliga decode em batch.", sglangGroupDebugDeterminismoEDiversos),
		boolFlag("enable-dynamic-batch-tokenizer", "", nil, false, "Tokenizer dinâmico async (múltiplas reqs concorrentes).", sglangGroupDebugDeterminismoEDiversos),
		intFlag("dynamic-batch-tokenizer-batch-size", "", nil, nil, "Batch máx. do tokenizer dinâmico.", sglangGroupDebugDeterminismoEDiversos, nil, nil),
		intFlag("dynamic-batch-tokenizer-batch-timeout", "", nil, nil, "Timeout de batching da tokenização.", sglangGroupDebugDeterminismoEDiversos, nil, nil),
		boolFlag("disable-outlines-disk-cache", "", nil, false, "Desliga o disk cache do outlines.", sglangGroupDebugDeterminismoEDiversos),
		boolFlag("enable-precise-embedding-interpolation", "", nil, false, "Interpolação de embeddings com corner alignment (mais lento).", sglangGroupDebugDeterminismoEDiversos),
		strFlag("rl-on-policy-target", "", nil, nil, "Sistema de treino a casar para true on-policy.", sglangGroupDebugDeterminismoEDiversos, false),
		boolFlag("enable-pdmux", "", nil, false, "PD-Multiplexing (greenctx stream).", sglangGroupDebugDeterminismoEDiversos),
		strFlag("pdmux-config-path", "", nil, nil, "Config do PD-Multiplexing.", sglangGroupDebugDeterminismoEDiversos, false),
		intFlag("sm-group-num", "", nil, nil, "Nº de grupos de partição de SM.", sglangGroupDebugDeterminismoEDiversos, nil, nil),
		strFlag("dllm-algorithm", "", nil, nil, "Algoritmo de diffusion LLM (ex.: `LowConfidence`).", sglangGroupDebugDeterminismoEDiversos, false),
		strFlag("dllm-algorithm-config", "", nil, nil, "Config do algoritmo dLLM.", sglangGroupDebugDeterminismoEDiversos, false),
		strFlag("forward-hooks", "", nil, nil, "Forward hooks a anexar ao modelo.", sglangGroupDebugDeterminismoEDiversos, false),
		strFlag("vae-path", "", nil, nil, "VAE customizado (ex.: autoencoder destilado).", sglangGroupServidorDeModelosDeDifusao, false),
		enumFlag("backend", "", nil, []string{"auto", "sglang", "diffusers"}, nil, "Backend (auto prefere sglang, cai p/ diffusers).", sglangGroupServidorDeModelosDeDifusao),
		strFlag("attention-backend-config", "", nil, nil, "Config do backend de atenção.", sglangGroupServidorDeModelosDeDifusao, false),
		strFlag("cache-dit-config", "", nil, nil, "Habilita Cache-DiT (backend diffusers).", sglangGroupServidorDeModelosDeDifusao, false),
		intFlag("num-gpus", "", nil, nil, "Nº de GPUs.", sglangGroupServidorDeModelosDeDifusao, nil, nil),
		intFlag("sp-degree", "", nil, nil, "Sequence parallelism (resto das GPUs após TP/DP).", sglangGroupServidorDeModelosDeDifusao, nil, nil),
		intFlag("ulysses-degree", "", nil, nil, "Grau de SP Ulysses / Ring (na atenção).", sglangGroupServidorDeModelosDeDifusao, nil, nil),
		intFlag("ring-degree", "", nil, nil, "Grau de SP Ulysses / Ring (na atenção).", sglangGroupServidorDeModelosDeDifusao, nil, nil),
		boolFlag("enable-cfg-parallel", "", nil, false, "Paralelismo de CFG.", sglangGroupServidorDeModelosDeDifusao),
		intFlag("dp", "", nil, nil, "Data parallelism.", sglangGroupServidorDeModelosDeDifusao, nil, nil),
		intFlag("hsdp-replicate-dim", "", nil, nil, "Dimensões de réplica/shard do HSDP.", sglangGroupServidorDeModelosDeDifusao, nil, nil),
		intFlag("hsdp-shard-dim", "", nil, nil, "Dimensões de réplica/shard do HSDP.", sglangGroupServidorDeModelosDeDifusao, nil, nil),
		strFlag("prompt-file-path", "", nil, nil, "Prompts em batch (um por linha).", sglangGroupServidorDeModelosDeDifusao, false),
		strFlag("mask-strategy-file-path", "", nil, nil, "Estratégia de máscara (STA).", sglangGroupServidorDeModelosDeDifusao, false),
		strFlag("warmup", "", nil, nil, "Warmup do servidor (resoluções, ex.: `256x256`).", sglangGroupServidorDeModelosDeDifusao, false),
		strFlag("warmup-resolutions", "", nil, nil, "Warmup do servidor (resoluções, ex.: `256x256`).", sglangGroupServidorDeModelosDeDifusao, false),
		boolFlag("dit-cpu-offload", "", nil, false, "CPU offload do DiT (se faltar memória com FSDP).", sglangGroupServidorDeModelosDeDifusao),
		boolFlag("dit-layerwise-offload", "", nil, false, "Offload por camada com prefetch async (Wan, MOVA).", sglangGroupServidorDeModelosDeDifusao),
		floatFlag("dit-offload-prefetch-size", "", nil, nil, "Prefetch do offload por camada.", sglangGroupServidorDeModelosDeDifusao, nil, nil),
		boolFlag("use-fsdp-inference", "", nil, false, "FSDP para inferência (sharding dos pesos).", sglangGroupServidorDeModelosDeDifusao),
		boolFlag("text-encoder-cpu-offload", "", nil, false, "CPU offload do text/image encoder / VAE.", sglangGroupServidorDeModelosDeDifusao),
		boolFlag("image-encoder-cpu-offload", "", nil, false, "CPU offload do text/image encoder / VAE.", sglangGroupServidorDeModelosDeDifusao),
		boolFlag("vae-cpu-offload", "", nil, false, "CPU offload do text/image encoder / VAE.", sglangGroupServidorDeModelosDeDifusao),
		boolFlag("pin-cpu-memory", "", nil, false, "Pin memory para CPU offload.", sglangGroupServidorDeModelosDeDifusao),
		boolFlag("disable-autocast", "", nil, false, "Desliga autocast no denoising/VAE.", sglangGroupServidorDeModelosDeDifusao),
		boolFlag("enable-svdquant", "", nil, false, "Nunchaku SVDQuant (estilo W4A4).", sglangGroupServidorDeModelosDeDifusao),
		strFlag("quantized-model-path", "", nil, nil, "Pesos pré-quantizados Nunchaku.", sglangGroupServidorDeModelosDeDifusao, false),
		enumFlag("quantization-precision", "", nil, []string{"int4", "nvfp4"}, nil, "Precisão da quantização.", sglangGroupServidorDeModelosDeDifusao),
		intFlag("quantization-rank", "", nil, nil, "Dimensão low-rank do SVD (ex.: `32`).", sglangGroupServidorDeModelosDeDifusao, nil, nil),
		boolFlag("quantization-act-unsigned", "", nil, false, "Quantização de ativação sem sinal.", sglangGroupServidorDeModelosDeDifusao),
		intFlag("master-port", "", nil, nil, "Portas distribuída / scheduler.", sglangGroupServidorDeModelosDeDifusao, nil, nil),
		intFlag("scheduler-port", "", nil, nil, "Portas distribuída / scheduler.", sglangGroupServidorDeModelosDeDifusao, nil, nil),
		boolFlag("webui", "", nil, false, "Interface web.", sglangGroupServidorDeModelosDeDifusao),
		boolFlag("webui-port", "", nil, false, "Interface web.", sglangGroupServidorDeModelosDeDifusao),
		strFlag("output-path", "", nil, nil, "Diretório de saída (imagens/vídeos).", sglangGroupServidorDeModelosDeDifusao, false),
		strFlag("lora-path", "", nil, nil, "Adapter LoRA (ex.: `0.125` p/ Hyper-SD).", sglangGroupServidorDeModelosDeDifusao, false),
		strFlag("lora-nickname", "", nil, nil, "Adapter LoRA (ex.: `0.125` p/ Hyper-SD).", sglangGroupServidorDeModelosDeDifusao, false),
		strFlag("lora-scale", "", nil, nil, "Adapter LoRA (ex.: `0.125` p/ Hyper-SD).", sglangGroupServidorDeModelosDeDifusao, false),
		strFlag("pipeline-config-path", "", nil, nil, "Config da pipeline.", sglangGroupServidorDeModelosDeDifusao, false),
		strFlag("embedded-cfg-scale", "", nil, nil, "Escala CFG embutida / flow shift.", sglangGroupServidorDeModelosDeDifusao, false),
		strFlag("flow-shift", "", nil, nil, "Escala CFG embutida / flow shift.", sglangGroupServidorDeModelosDeDifusao, false),
		enumFlag("dit-precision", "", nil, []string{"fp32", "fp16", "bf16"}, nil, "Precisão do DiT / VAE / image encoder.", sglangGroupServidorDeModelosDeDifusao),
		enumFlag("vae-precision", "", nil, []string{"fp32", "fp16", "bf16"}, nil, "Precisão do DiT / VAE / image encoder.", sglangGroupServidorDeModelosDeDifusao),
		enumFlag("image-encoder-precision", "", nil, []string{"fp32", "fp16", "bf16"}, nil, "Precisão do DiT / VAE / image encoder.", sglangGroupServidorDeModelosDeDifusao),
		strFlag("text-encoder-precisions", "", nil, nil, "Precisão de cada text encoder.", sglangGroupServidorDeModelosDeDifusao, false),
		boolFlag("vae-tiling", "", nil, false, "Tiling / spatial parallelism do VAE.", sglangGroupServidorDeModelosDeDifusao),
		boolFlag("vae-sp", "", nil, false, "Tiling / spatial parallelism do VAE.", sglangGroupServidorDeModelosDeDifusao),
		strFlag("dmd-denoising-steps", "", nil, nil, "Passos de denoising (ex.: `1000,757,522`).", sglangGroupServidorDeModelosDeDifusao, false),
		strFlag("dit-config.prefix", "", nil, nil, "Prefixo / quantização do DiT.", sglangGroupServidorDeModelosDeDifusao, false),
		strFlag("dit-config.quant-config", "", nil, nil, "Prefixo / quantização do DiT.", sglangGroupServidorDeModelosDeDifusao, false),
		boolFlag("t5-config.parallel-folding", "", nil, false, "Parallel folding do T5.", sglangGroupServidorDeModelosDeDifusao),
		boolFlag("t5-config.parallel-folding-mode", "", nil, false, "Parallel folding do T5.", sglangGroupServidorDeModelosDeDifusao),
	} {
		add(spec)
	}
	return domain.BackendValidationSchema{SchemaVersion: 1, Kind: domain.ValidationSchemaCLIFlagsV1, BackendKind: domain.BackendKindSGLang, BackendID: "sglang-default", Source: domain.SchemaSource{GeneratedFrom: "sglang.md curated reference", SourceVersion: "curated-sglang-serve", Editable: true}, Flags: flags, Presentation: sglangPresentation()}
}

func sglangPresentation() *domain.Presentation {
	return &domain.Presentation{Groups: []domain.PresentationGroup{
		{Name: sglangGroupEssentials, Highlighted: true, Flags: []string{"served-model-name", "host", "port", "api-key", "context-length", "dtype", "quantization", "kv-cache-dtype", "mem-fraction-static", "max-running-requests", "max-total-tokens", "tensor-parallel-size", "tp-size", "pipeline-parallel-size", "data-parallel-size", "device", "enable-multimodal", "chat-template"}},
		{Name: sglangGroupServidorEGeral, Flags: []string{"host", "port", "fastapi-root-path", "grpc-mode", "config", "skip-server-warmup", "warmups", "nccl-port", "checkpoint-engine-wait-weights-before-ready", "watchdog-timeout", "soft-watchdog-timeout", "dist-timeout", "custom-sigquit-handler", "sleep-on-idle", "base-gpu-id", "gpu-id-step", "numa-node", "scheduler-recv-interval"}},
		{Name: sglangGroupModeloETokenizer, Flags: []string{"tokenizer-path", "tokenizer-mode", "tokenizer-worker-num", "skip-tokenizer-init", "trust-remote-code", "context-length", "is-embedding", "enable-multimodal", "revision", "model-impl", "served-model-name", "weight-version", "json-model-override-args", "model-checksum"}},
		{Name: sglangGroupCarregamentoDePesos, Flags: []string{"load-format", "model-loader-extra-config", "download-dir", "custom-weight-loader", "weight-loader-disable-mmap", "delete-ckpt-after-loading", "decrypted-config-file", "decrypted-draft-config-file", "remote-instance-weight-loader-seed-instance-ip", "remote-instance-weight-loader-seed-instance-service-port", "remote-instance-weight-loader-send-weights-group-ports", "remote-instance-weight-loader-backend", "remote-instance-weight-loader-start-seed-via-transfer-engine"}},
		{Name: sglangGroupDtypeEQuantizacao, Flags: []string{"dtype", "quantization", "quantization-param-path", "kv-cache-dtype", "enable-fp32-lm-head", "modelopt-quant", "modelopt-checkpoint-restore-path", "modelopt-checkpoint-save-path", "modelopt-export-path", "quantize-and-serve", "rl-quant-profile", "torchao-config"}},
		{Name: sglangGroupMemoriaEKvCache, Flags: []string{"mem-fraction-static", "max-running-requests", "max-queued-requests", "max-total-tokens", "page-size", "max-mamba-cache-size", "swa-full-tokens-ratio", "disable-hybrid-swa-memory", "hybrid-kvcache-ratio"}},
		{Name: sglangGroupCacheDePrefixoRadixEHierarquico, Flags: []string{"disable-radix-cache", "radix-eviction-policy", "enable-hierarchical-cache", "hicache-ratio", "hicache-size", "hicache-write-policy", "hicache-io-backend", "hicache-mem-layout", "disable-hicache-numa-detect", "hicache-storage-backend", "hicache-storage-prefetch-policy", "hicache-storage-backend-extra-config", "enable-lmcache"}},
		{Name: sglangGroupPrefillChunkingEScheduler, Flags: []string{"chunked-prefill-size", "prefill-max-requests", "enable-dynamic-chunking", "max-prefill-tokens", "enable-mixed-chunk", "disable-chunked-prefix-cache", "schedule-policy", "enable-priority-scheduling", "abort-on-priority-when-disabled", "schedule-low-priority-values-first", "priority-scheduling-preemption-threshold", "schedule-conservativeness", "num-continuous-decode-steps", "disable-overlap-schedule", "enable-prefill-delayer", "prefill-delayer-max-delay-passes", "prefill-delayer-token-usage-low-watermark"}},
		{Name: sglangGroupStreamingSamplingEGramatica, Flags: []string{"stream-interval", "stream-output", "random-seed", "sampling-defaults", "preferred-sampling-params", "grammar-backend", "constrained-json-whitespace-pattern", "constrained-json-disable-any-whitespace"}},
		{Name: sglangGroupParalelismoEExecucaoDistribuida, Flags: []string{"device", "tensor-parallel-size", "tp-size", "pipeline-parallel-size", "pp-size", "data-parallel-size", "dp-size", "attention-context-parallel-size", "attn-cp-size", "moe-data-parallel-size", "moe-dp-size", "pp-max-micro-batch-size", "pp-async-batch-depth", "load-balance-method", "dist-init-addr", "nccl-init-addr", "nnodes", "node-rank", "enable-dp-attention", "enable-dp-lm-head", "enable-attn-tp-input-scattered", "moe-dense-tp-size"}},
		{Name: sglangGroupMoeEExpertParallelism, Flags: []string{"expert-parallel-size", "ep-size", "ep", "moe-a2a-backend", "moe-runner-backend", "flashinfer-mxfp4-moe-precision", "enable-flashinfer-allreduce-fusion", "deepep-mode", "ep-num-redundant-experts", "ep-dispatch-algorithm", "init-expert-location", "enable-eplb", "eplb-algorithm", "eplb-rebalance-num-iterations", "eplb-rebalance-layers-per-chunk", "eplb-min-rebalancing-utilization-threshold", "expert-distribution-recorder-mode", "expert-distribution-recorder-buffer-size", "enable-expert-distribution-metrics", "deepep-config", "elastic-ep-backend", "mooncake-ib-device", "disable-shared-experts-fusion"}},
		{Name: sglangGroupBackendsDeAtencaoEGemm, Flags: []string{"attention-backend", "prefill-attention-backend", "decode-attention-backend", "sampling-backend", "mm-attention-backend", "fp8-gemm-backend", "fp4-gemm-backend", "disable-flashinfer-autotune", "flashinfer-mla-disable-ragged", "enable-fused-qk-norm-rope", "triton-attention-reduce-in-fp32", "triton-attention-num-kv-splits", "triton-attention-split-tile-size"}},
		{Name: sglangGroupAtencaoEsparsaNsaEDoubleSparsity, Flags: []string{"nsa-prefill-backend", "nsa-decode-backend", "enable-nsa-prefill-context-parallel", "nsa-prefill-cp-mode", "enable-double-sparsity", "ds-channel-config-path", "ds-heavy-channel-num", "ds-heavy-token-num", "ds-heavy-channel-type", "ds-sparse-decode-threshold", "hierarchical-sparse-attention-extra-config"}},
		{Name: sglangGroupMambaSsm, Flags: []string{"mamba-ssm-dtype", "mamba-full-memory-ratio", "mamba-scheduler-strategy", "mamba-track-interval", "mamba-backend"}},
		{Name: sglangGroupLora, Flags: []string{"enable-lora", "lora-paths", "max-lora-rank", "lora-target-modules", "max-loras-per-batch", "max-loaded-loras", "lora-eviction-policy", "lora-backend", "max-lora-chunk-size", "enable-lora-overlap-loading"}},
		{Name: sglangGroupSpeculativeDecoding, Flags: []string{"speculative-algorithm", "speculative-draft-model-path", "speculative-draft-model", "speculative-draft-model-revision", "speculative-draft-load-format", "speculative-draft-model-quantization", "speculative-num-steps", "speculative-eagle-topk", "speculative-num-draft-tokens", "speculative-accept-threshold-single", "speculative-accept-threshold-acc", "speculative-token-map", "speculative-attention-mode", "speculative-draft-attention-backend", "speculative-moe-runner-backend", "speculative-moe-a2a-backend", "enable-multi-layer-eagle", "speculative-ngram-match-type", "speculative-ngram-branch-length", "speculative-ngram-capacity"}},
		{Name: sglangGroupCudaGraphETorchCompile, Flags: []string{"disable-cuda-graph", "disable-cuda-graph-padding", "cuda-graph-max-bs", "cuda-graph-bs", "enable-profile-cuda-graph", "enable-cudagraph-gc", "enable-torch-compile", "enable-torch-compile-debug-mode", "torch-compile-max-bs", "enable-piecewise-cuda-graph", "piecewise-cuda-graph-tokens", "piecewise-cuda-graph-max-tokens", "piecewise-cuda-graph-compiler"}},
		{Name: sglangGroupComunicacaoEAllReduce, Flags: []string{"disable-custom-all-reduce", "enable-mscclpp", "enable-torch-symm-mem", "enable-symm-mem", "enable-nccl-nvls", "enable-p2p-check", "disable-flashinfer-cutlass-moe-fp4-allgather"}},
		{Name: sglangGroupOffloadDePesosEMemorySaver, Flags: []string{"cpu-offload-gb", "offload-group-size", "offload-num-in-group", "offload-prefetch-step", "offload-mode", "enable-memory-saver", "enable-weights-cpu-backup", "enable-draft-weights-cpu-backup", "kt-weight-path", "kt-method", "kt-cpuinfer", "kt-threadpool-count", "kt-num-gpu-experts", "kt-max-deferred-experts-per-token"}},
		{Name: sglangGroupMultimodalEEncoder, Flags: []string{"limit-mm-data-per-request", "mm-max-concurrent-calls", "mm-per-request-timeout", "enable-broadcast-mm-inputs-process", "mm-process-config", "mm-enable-dp-encoder", "disable-fast-image-processor", "keep-mm-feature-on-device", "enable-prefix-mm-cache", "encoder-only", "language-only", "encoder-transfer-backend", "encoder-urls"}},
		{Name: sglangGroupApiOpenaiEParsers, Flags: []string{"api-key", "admin-api-key", "chat-template", "hf-chat-template-name", "completion-template", "file-storage-path", "enable-cache-report", "reasoning-parser", "tool-call-parser", "tool-server", "multi-item-scoring-delimiter", "allow-auto-truncate", "enable-custom-logit-processor", "enable-return-hidden-states", "enable-return-routed-experts"}},
		{Name: sglangGroupLoggingMetricasETracing, Flags: []string{"log-level", "log-level-http", "log-requests", "log-requests-level", "log-requests-format", "log-requests-target", "uvicorn-access-log-exclude-prefixes", "crash-dump-folder", "show-time-cost", "enable-metrics", "enable-metrics-for-all-schedulers", "tokenizer-metrics-custom-labels-header", "tokenizer-metrics-allowed-custom-labels", "extra-metric-labels", "bucket-time-to-first-token", "bucket-inter-token-latency", "bucket-e2e-request-latency", "collect-tokens-histogram", "prompt-tokens-buckets", "generation-tokens-buckets", "gc-warning-threshold-secs", "decode-log-interval", "enable-request-time-stats-logging", "kv-events-config", "enable-trace", "otlp-traces-endpoint", "export-metrics-to-file", "export-metrics-to-file-dir"}},
		{Name: sglangGroupPdDisaggregation, Flags: []string{"disaggregation-mode", "disaggregation-transfer-backend", "disaggregation-bootstrap-port", "disaggregation-decode-tp", "disaggregation-decode-dp", "disaggregation-prefill-pp", "disaggregation-ib-device", "disaggregation-decode-enable-offload-kvcache", "num-reserved-decode-tokens", "disaggregation-decode-polling-interval"}},
		{Name: sglangGroupDebugDeterminismoEDiversos, Flags: []string{"enable-deterministic-inference", "enable-nan-detection", "debug-tensor-dump-output-folder", "debug-tensor-dump-layers", "debug-tensor-dump-input-file", "debug-tensor-dump-inject", "enable-tokenizer-batch-encode", "disable-tokenizer-batch-decode", "enable-dynamic-batch-tokenizer", "dynamic-batch-tokenizer-batch-size", "dynamic-batch-tokenizer-batch-timeout", "disable-outlines-disk-cache", "enable-precise-embedding-interpolation", "rl-on-policy-target", "enable-pdmux", "pdmux-config-path", "sm-group-num", "dllm-algorithm", "dllm-algorithm-config", "forward-hooks"}},
		{Name: sglangGroupServidorDeModelosDeDifusao, Flags: []string{"vae-path", "backend", "attention-backend-config", "cache-dit-config", "num-gpus", "sp-degree", "ulysses-degree", "ring-degree", "enable-cfg-parallel", "dp", "hsdp-replicate-dim", "hsdp-shard-dim", "prompt-file-path", "mask-strategy-file-path", "warmup", "warmup-resolutions", "dit-cpu-offload", "dit-layerwise-offload", "dit-offload-prefetch-size", "use-fsdp-inference", "text-encoder-cpu-offload", "image-encoder-cpu-offload", "vae-cpu-offload", "pin-cpu-memory", "disable-autocast", "enable-svdquant", "quantized-model-path", "quantization-precision", "quantization-rank", "quantization-act-unsigned", "master-port", "scheduler-port", "webui", "webui-port", "output-path", "lora-path", "lora-nickname", "lora-scale", "pipeline-config-path", "embedded-cfg-scale", "flow-shift", "dit-precision", "vae-precision", "image-encoder-precision", "text-encoder-precisions", "vae-tiling", "vae-sp", "dmd-denoising-steps", "dit-config.prefix", "dit-config.quant-config", "t5-config.parallel-folding", "t5-config.parallel-folding-mode"}},
	}}
}
