package backendschema

import "github.com/quantmind-br/model-loader/internal/domain"

const (
	vllmGroupEssentials      = "Essenciais"
	vllmGroupServer          = "1. Servidor e geral"
	vllmGroupFrontend        = "2. Frontend (API OpenAI)"
	vllmGroupModel           = "3. Modelo (ModelConfig)"
	vllmGroupLoad            = "4. Carregamento de pesos (LoadConfig)"
	vllmGroupAttention       = "5. Atenção e Mamba"
	vllmGroupStructured      = "6. Saídas estruturadas e reasoning"
	vllmGroupParallel        = "7. Paralelismo e execução distribuída"
	vllmGroupKV              = "8. KV cache"
	vllmGroupWeightOffload   = "9. Offloading de pesos"
	vllmGroupMultimodal      = "10. Multimodal"
	vllmGroupLora            = "11. LoRA"
	vllmGroupObservability   = "12. Observabilidade e métricas"
	vllmGroupScheduler       = "13. Scheduler"
	vllmGroupCompilation     = "14. Compilação e CUDA graphs"
	vllmGroupKernels         = "15. Kernels e MoE"
	vllmGroupAdvancedConfigs = "16. Configs avançadas (VllmConfig)"
)

// CuratedVLLMSchema returns the hand-curated vLLM serve schema based on
// docs/model-loader/vllm.md. The profile model field is handled separately,
// so positional model_tag and --model are intentionally omitted.
func CuratedVLLMSchema() domain.BackendValidationSchema {
	flags := map[string]domain.FlagSpec{}
	add := func(spec domain.FlagSpec) {
		flags[spec.Long] = spec
	}

	for _, spec := range []domain.FlagSpec{
		strFlag("config", "", nil, nil, "Lê opções de CLI a partir de um arquivo YAML.", vllmGroupServer, false),
		intFlag("api-server-count", "asc", nil, nil, "Quantos processos de API server rodar; default acompanha data_parallel_size.", vllmGroupServer, intPtr(1), nil),
		boolFlag("headless", "", nil, false, "Roda sem front-end HTTP em nós secundários de data parallel multi-nó.", vllmGroupServer),
		boolFlag("grpc", "", nil, false, "Sobe servidor gRPC em vez do HTTP OpenAI; requer vllm[grpc].", vllmGroupServer),
		boolFlag("disable-log-stats", "", nil, false, "Desativa o log de estatísticas.", vllmGroupServer),
		boolFlag("enable-log-requests", "", nil, false, "Loga informação das requisições; DEBUG pode incluir prompt.", vllmGroupServer),
		boolFlag("no-enable-log-requests", "", nil, false, "Desativa explicitamente o log de requisições.", vllmGroupServer),
		boolFlag("aggregate-engine-logging", "", nil, false, "Loga estatísticas agregadas em data parallelism.", vllmGroupServer),
		intFlag("shutdown-timeout", "", nil, 0, "Timeout de shutdown em segundos; 0 aborta imediatamente.", vllmGroupServer, intPtr(0), nil),
		enumFlag("gdn-prefill-backend", "", nil, []string{"flashinfer", "triton"}, nil, "Seleciona o backend de prefill do GDN.", vllmGroupServer),
		boolFlag("fail-on-environ-validation", "", nil, false, "Erro fatal se a validação de ambiente falhar.", vllmGroupServer),
		boolFlag("no-fail-on-environ-validation", "", nil, false, "Ignora falhas não fatais da validação de ambiente.", vllmGroupServer),

		strFlag("host", "", nil, nil, "Endereço de escuta; None escuta em todas as interfaces.", vllmGroupFrontend, false),
		portFlag("port", "", 8000, "Porta HTTP do servidor.", vllmGroupFrontend),
		strFlag("uds", "", nil, nil, "Unix domain socket; ignora host/port quando definido.", vllmGroupFrontend, false),
		strFlag("api-key", "", nil, nil, "Exige uma das chaves no header da requisição.", vllmGroupFrontend, false),
		strFlag("root-path", "", nil, nil, "root_path do FastAPI atrás de proxy de rota.", vllmGroupFrontend, false),
		strFlag("allowed-origins", "", nil, "['*']", "Origens permitidas pelo CORS.", vllmGroupFrontend, false),
		strFlag("allowed-methods", "", nil, "['*']", "Métodos permitidos pelo CORS.", vllmGroupFrontend, false),
		strFlag("allowed-headers", "", nil, "['*']", "Headers permitidos pelo CORS.", vllmGroupFrontend, false),
		boolFlag("allow-credentials", "", nil, false, "Permite credenciais no CORS.", vllmGroupFrontend),
		boolFlag("no-allow-credentials", "", nil, false, "Desativa credenciais no CORS.", vllmGroupFrontend),
		strFlag("ssl-certfile", "", nil, nil, "Certificado SSL.", vllmGroupFrontend, false),
		strFlag("ssl-keyfile", "", nil, nil, "Chave SSL.", vllmGroupFrontend, false),
		strFlag("ssl-ca-certs", "", nil, nil, "Arquivo de CA para SSL.", vllmGroupFrontend, false),
		intFlag("ssl-cert-reqs", "", nil, 0, "Exige certificado de cliente segundo stdlib ssl.", vllmGroupFrontend, intPtr(0), nil),
		strFlag("ssl-ciphers", "", nil, nil, "Cifras TLS 1.2 e abaixo.", vllmGroupFrontend, false),
		boolFlag("enable-ssl-refresh", "", nil, false, "Recarrega contexto SSL quando os arquivos mudam.", vllmGroupFrontend),
		boolFlag("no-enable-ssl-refresh", "", nil, false, "Desativa recarga automática do contexto SSL.", vllmGroupFrontend),
		strFlag("chat-template", "", nil, nil, "Template de chat customizado ou arquivo.", vllmGroupFrontend, false),
		enumFlag("chat-template-content-format", "", nil, []string{"auto", "openai", "string"}, "auto", "Formato do conteúdo no template.", vllmGroupFrontend),
		strFlag("default-chat-template-kwargs", "", nil, nil, "Argumentos padrão em JSON para o template.", vllmGroupFrontend, false),
		strFlag("response-role", "", nil, "assistant", "Papel atribuído à resposta.", vllmGroupFrontend, false),
		boolFlag("enable-auto-tool-choice", "", nil, false, "Habilita escolha automática de ferramentas.", vllmGroupFrontend),
		boolFlag("no-enable-auto-tool-choice", "", nil, false, "Desativa escolha automática de ferramentas.", vllmGroupFrontend),
		strFlag("tool-call-parser", "", nil, nil, "Parser de tool calls conforme o modelo.", vllmGroupFrontend, false),
		strFlag("tool-parser-plugin", "", nil, nil, "Plugin de parser de ferramentas.", vllmGroupFrontend, false),
		strFlag("reasoning-parser", "", nil, "", "Parser de conteúdo de raciocínio no formato OpenAI.", vllmGroupFrontend, false),
		strFlag("lora-modules", "", nil, nil, "Define módulos LoRA expostos na API.", vllmGroupFrontend, false),
		intFlag("max-log-len", "", nil, nil, "Trunca o log de prompts e saídas.", vllmGroupFrontend, intPtr(0), nil),
		boolFlag("enable-request-id-headers", "", nil, false, "Adiciona X-Request-Id às respostas.", vllmGroupFrontend),
		boolFlag("no-enable-request-id-headers", "", nil, false, "Desativa X-Request-Id nas respostas.", vllmGroupFrontend),
		boolFlag("disable-fastapi-docs", "", nil, false, "Desliga Swagger, ReDoc e OpenAPI.", vllmGroupFrontend),
		boolFlag("no-disable-fastapi-docs", "", nil, false, "Mantém Swagger, ReDoc e OpenAPI ligados.", vllmGroupFrontend),
		boolFlag("enable-offline-docs", "", nil, false, "Usa docs FastAPI offline com assets embutidos.", vllmGroupFrontend),
		boolFlag("no-enable-offline-docs", "", nil, false, "Desativa docs FastAPI offline.", vllmGroupFrontend),
		boolFlag("disable-uvicorn-access-log", "", nil, false, "Desliga access log do uvicorn.", vllmGroupFrontend),
		boolFlag("no-disable-uvicorn-access-log", "", nil, false, "Mantém access log do uvicorn ligado.", vllmGroupFrontend),
		strFlag("disable-access-log-for-endpoints", "", nil, nil, "Suprime access log de endpoints, separados por vírgula.", vllmGroupFrontend, false),
		enumFlag("uvicorn-log-level", "", nil, []string{"critical", "error", "warning", "info", "debug", "trace"}, "info", "Nível de log do uvicorn.", vllmGroupFrontend),
		strFlag("middleware", "", nil, "[]", "ASGI middleware extra; repetível.", vllmGroupFrontend, false),
		boolFlag("return-tokens-as-token-ids", "", nil, false, "Retorna tokens como token IDs.", vllmGroupFrontend),
		boolFlag("no-return-tokens-as-token-ids", "", nil, false, "Retorna tokens como texto quando possível.", vllmGroupFrontend),
		boolFlag("enable-prompt-tokens-details", "", nil, false, "Detalha tokens de prompt na usage.", vllmGroupFrontend),
		boolFlag("no-enable-prompt-tokens-details", "", nil, false, "Desativa detalhe de tokens de prompt na usage.", vllmGroupFrontend),
		boolFlag("enable-force-include-usage", "", nil, false, "Força inclusão de usage nas respostas.", vllmGroupFrontend),
		boolFlag("no-enable-force-include-usage", "", nil, false, "Não força inclusão de usage nas respostas.", vllmGroupFrontend),
		intFlag("h11-max-header-count", "", nil, 256, "Máximo de headers HTTP.", vllmGroupFrontend, intPtr(1), nil),
		intFlag("h11-max-incomplete-event-size", "", nil, 4194304, "Máximo de evento HTTP incompleto em bytes.", vllmGroupFrontend, intPtr(1), nil),

		strFlag("served-model-name", "", nil, nil, "Nome do modelo na API e nas métricas; default usa o modelo.", vllmGroupModel, false),
		strFlag("tokenizer", "", nil, nil, "Tokenizer alternativo; default usa o modelo.", vllmGroupModel, false),
		enumFlag("tokenizer-mode", "", nil, []string{"auto", "hf", "slow", "mistral"}, "auto", "Modo do tokenizer.", vllmGroupModel),
		strFlag("revision", "", nil, nil, "Branch, tag ou commit do modelo no Hugging Face.", vllmGroupModel, false),
		strFlag("code-revision", "", nil, nil, "Branch, tag ou commit do código remoto.", vllmGroupModel, false),
		strFlag("tokenizer-revision", "", nil, nil, "Branch, tag ou commit do tokenizer.", vllmGroupModel, false),
		enumFlag("dtype", "", nil, []string{"auto", "bfloat16", "float16", "float32", "half", "float"}, "auto", "Tipo de dado de pesos e ativações.", vllmGroupModel),
		strFlag("max-model-len", "", nil, nil, "Comprimento de contexto total; aceita inteiro, 1k, auto ou -1.", vllmGroupModel, false),
		strFlag("quantization", "q", nil, nil, "Método de quantização dos pesos.", vllmGroupModel, false),
		intFlag("seed", "", nil, 0, "Seed global de reprodutibilidade.", vllmGroupModel, nil, nil),
		boolFlag("trust-remote-code", "", nil, false, "Confia em código remoto do Hugging Face.", vllmGroupModel),
		boolFlag("no-trust-remote-code", "", nil, false, "Desativa execução de código remoto do Hugging Face.", vllmGroupModel),
		strFlag("hf-token", "", nil, nil, "Bearer token para arquivos remotos; True usa token local.", vllmGroupModel, false),
		strFlag("hf-overrides", "", nil, "{}", "Sobrescreve a config HF com JSON.", vllmGroupModel, false),
		strFlag("hf-config-path", "", nil, nil, "Caminho de config HF alternativa.", vllmGroupModel, false),
		enumFlag("config-format", "", nil, []string{"auto", "hf", "mistral"}, "auto", "Formato da config do modelo.", vllmGroupModel),
		enumFlag("model-impl", "", nil, []string{"auto", "vllm", "transformers", "terratorch"}, "auto", "Implementação do modelo.", vllmGroupModel),
		enumFlag("runner", "", nil, []string{"auto", "generate", "pooling", "draft"}, "auto", "Tipo de runner do modelo.", vllmGroupModel),
		enumFlag("convert", "", nil, []string{"auto", "classify", "embed", "none"}, "auto", "Adapta o modelo, por exemplo de geração para pooling.", vllmGroupModel),
		boolFlag("enforce-eager", "", nil, false, "Força modo eager, sem CUDA graph.", vllmGroupModel),
		boolFlag("no-enforce-eager", "", nil, false, "Permite CUDA graphs e compilação quando aplicável.", vllmGroupModel),
		boolFlag("enable-sleep-mode", "", nil, false, "Habilita sleep mode da engine em CUDA/HIP.", vllmGroupModel),
		boolFlag("no-enable-sleep-mode", "", nil, false, "Desativa sleep mode da engine.", vllmGroupModel),
		boolFlag("disable-sliding-window", "", nil, false, "Desliga sliding window.", vllmGroupModel),
		boolFlag("no-disable-sliding-window", "", nil, false, "Mantém sliding window habilitado quando suportado.", vllmGroupModel),
		boolFlag("disable-cascade-attn", "", nil, true, "Desliga cascade attention.", vllmGroupModel),
		boolFlag("no-disable-cascade-attn", "", nil, false, "Mantém cascade attention habilitada.", vllmGroupModel),
		intFlag("max-logprobs", "", nil, 20, "Máximo de logprobs retornados; -1 remove limite.", vllmGroupModel, nil, nil),
		enumFlag("logprobs-mode", "", nil, []string{"raw_logprobs", "processed_logprobs", "raw_logits", "processed_logits"}, "raw_logprobs", "Conteúdo de logprobs retornado.", vllmGroupModel),
		strFlag("generation-config", "", nil, "auto", "Origem da generation config: auto, vllm ou caminho.", vllmGroupModel, false),
		strFlag("override-generation-config", "", nil, "{}", "Sobrescreve a generation config com JSON.", vllmGroupModel, false),
		boolFlag("enable-prompt-embeds", "", nil, false, "Aceita prompt_embeds como entrada; use apenas com usuários confiáveis.", vllmGroupModel),
		boolFlag("no-enable-prompt-embeds", "", nil, false, "Desativa entrada via prompt_embeds.", vllmGroupModel),
		boolFlag("skip-tokenizer-init", "", nil, false, "Pula init do tokenizer e espera token IDs.", vllmGroupModel),
		boolFlag("no-skip-tokenizer-init", "", nil, false, "Inicializa o tokenizer normalmente.", vllmGroupModel),
		strFlag("pooler-config", "", nil, nil, "Config de pooling para modelos de embedding.", vllmGroupModel, false),
		strFlag("allowed-local-media-path", "", nil, nil, "Permite ler mídia local; risco de segurança.", vllmGroupModel, false),
		strFlag("allowed-media-domains", "", nil, nil, "Restringe domínios de mídia multimodal.", vllmGroupModel, false),
		intFlag("renderer-num-workers", "", nil, 1, "Threads do pool de renderização.", vllmGroupModel, intPtr(1), nil),
		strFlag("logits-processors", "", nil, nil, "Classes de logits processors customizados.", vllmGroupModel, false),
		strFlag("override-attention-dtype", "", nil, nil, "Sobrescreve dtype da atenção.", vllmGroupModel, false),
		strFlag("io-processor-plugin", "", nil, nil, "Plugin IOProcessor carregado no startup.", vllmGroupModel, false),
		boolFlag("allow-deprecated-quantization", "", nil, false, "Permite quantizações obsoletas.", vllmGroupModel),
		boolFlag("no-allow-deprecated-quantization", "", nil, false, "Bloqueia quantizações obsoletas.", vllmGroupModel),

		enumFlag("load-format", "", nil, []string{"auto", "safetensors", "pt", "dummy", "tensorizer", "runai_streamer", "bitsandbytes", "gguf", "mistral"}, "auto", "Formato dos pesos a carregar.", vllmGroupLoad),
		strFlag("download-dir", "", nil, nil, "Diretório de download/cache dos pesos.", vllmGroupLoad, false),
		strFlag("ignore-patterns", "", nil, "['original/**/*']", "Padrões a ignorar no carregamento dos pesos.", vllmGroupLoad, false),
		strFlag("model-loader-extra-config", "", nil, "{}", "Config extra em JSON passada ao loader.", vllmGroupLoad, false),
		enumFlag("safetensors-load-strategy", "", nil, []string{"None", "lazy", "eager", "prefetch", "torchao"}, nil, "Estratégia de leitura de safetensors.", vllmGroupLoad),
		strFlag("safetensors-prefetch-block-size", "", nil, "16M", "Tamanho de leitura no prefetch.", vllmGroupLoad, false),
		intFlag("safetensors-prefetch-num-threads", "", nil, 8, "Threads de prefetch.", vllmGroupLoad, intPtr(1), nil),
		strFlag("pt-load-map-location", "", nil, "cpu", "map_location do torch.load.", vllmGroupLoad, false),
		boolFlag("use-tqdm-on-load", "", nil, true, "Mostra barra de progresso no load.", vllmGroupLoad),
		boolFlag("no-use-tqdm-on-load", "", nil, false, "Desativa barra de progresso no load.", vllmGroupLoad),

		strFlag("attention-backend", "", nil, nil, "Backend de atenção; auto/None deixa o vLLM decidir.", vllmGroupAttention, false),
		strFlag("mamba-backend", "", nil, "TRITON", "Backend Mamba SSM.", vllmGroupAttention, false),
		boolFlag("enable-mamba-cache-stochastic-rounding", "", nil, false, "Usa arredondamento estocástico no cache SSM fp16.", vllmGroupAttention),
		boolFlag("no-enable-mamba-cache-stochastic-rounding", "", nil, false, "Desativa arredondamento estocástico no cache SSM.", vllmGroupAttention),
		intFlag("mamba-cache-philox-rounds", "", nil, 0, "Rounds do PRNG Philox para rounding estocástico.", vllmGroupAttention, intPtr(0), nil),

		strFlag("reasoning-parser-plugin", "", nil, "", "Plugin de reasoning parser carregado dinamicamente.", vllmGroupStructured, false),
		strFlag("structured-outputs-config", "", nil, nil, "Config completa de saídas estruturadas em JSON.", vllmGroupStructured, false),

		intFlag("tensor-parallel-size", "tp", nil, 1, "Grupos de tensor parallelism.", vllmGroupParallel, intPtr(1), nil),
		intFlag("pipeline-parallel-size", "pp", nil, 1, "Grupos de pipeline parallelism.", vllmGroupParallel, intPtr(1), nil),
		intFlag("data-parallel-size", "dp", nil, 1, "Grupos de data parallelism.", vllmGroupParallel, intPtr(1), nil),
		intFlag("data-parallel-size-local", "dpl", nil, nil, "Réplicas DP locais neste nó.", vllmGroupParallel, intPtr(1), nil),
		intFlag("data-parallel-rank", "dpn", nil, nil, "Rank DP desta instância para LB externo/MoE.", vllmGroupParallel, intPtr(0), nil),
		intFlag("data-parallel-start-rank", "dpr", nil, nil, "Rank DP inicial em nós secundários.", vllmGroupParallel, intPtr(0), nil),
		strFlag("data-parallel-address", "dpa", nil, nil, "Endereço do nó-cabeça do cluster DP.", vllmGroupParallel, false),
		portFlag("data-parallel-rpc-port", "dpp", 0, "Porta RPC do data parallelism.", vllmGroupParallel),
		enumFlag("data-parallel-backend", "dpb", nil, []string{"mp", "ray"}, "mp", "Backend do data parallelism.", vllmGroupParallel),
		boolFlag("data-parallel-external-lb", "dpe", nil, false, "Modo de LB externo one-pod-per-rank para MoE.", vllmGroupParallel),
		boolFlag("data-parallel-hybrid-lb", "dph", nil, false, "Modo de LB híbrido por nó.", vllmGroupParallel),
		intFlag("decode-context-parallel-size", "dcp", nil, 1, "Grupos de decode context parallel.", vllmGroupParallel, intPtr(1), nil),
		intFlag("prefill-context-parallel-size", "pcp", nil, 1, "Grupos de prefill context parallel.", vllmGroupParallel, intPtr(1), nil),
		boolFlag("enable-expert-parallel", "ep", nil, false, "Usa expert parallelism em camadas MoE.", vllmGroupParallel),
		boolFlag("no-enable-expert-parallel", "", nil, false, "Desativa expert parallelism em camadas MoE.", vllmGroupParallel),
		boolFlag("enable-eplb", "", nil, false, "Habilita load balancing de expert parallel.", vllmGroupParallel),
		boolFlag("no-enable-eplb", "", nil, false, "Desativa EPLB.", vllmGroupParallel),
		strFlag("eplb-config", "", nil, nil, "Configuração do EPLB em JSON.", vllmGroupParallel, false),
		enumFlag("expert-placement-strategy", "", nil, []string{"linear", "round_robin"}, "linear", "Posicionamento de experts MoE.", vllmGroupParallel),
		strFlag("all2all-backend", "", nil, "allgather_reducescatter", "Backend de comunicação all2all para MoE.", vllmGroupParallel, false),
		enumFlag("distributed-executor-backend", "", nil, []string{"mp", "ray", "uni", "external_launcher"}, nil, "Backend dos workers distribuídos; None escolhe automaticamente.", vllmGroupParallel),
		boolFlag("disable-custom-all-reduce", "", nil, false, "Desliga all-reduce custom e usa NCCL.", vllmGroupParallel),
		boolFlag("no-disable-custom-all-reduce", "", nil, false, "Permite all-reduce custom.", vllmGroupParallel),
		intFlag("nnodes", "n", nil, 1, "Número de nós para multi-nó com mp.", vllmGroupParallel, intPtr(1), nil),
		intFlag("node-rank", "r", nil, 0, "Rank do nó.", vllmGroupParallel, intPtr(0), nil),
		strFlag("master-addr", "", nil, "127.0.0.1", "Endereço master para multi-nó com mp.", vllmGroupParallel, false),
		portFlag("master-port", "", 29501, "Porta master para multi-nó com mp.", vllmGroupParallel),
		intFlag("max-parallel-loading-workers", "", nil, nil, "Workers paralelos no load para evitar OOM de RAM.", vllmGroupParallel, intPtr(1), nil),
		boolFlag("numa-bind", "", nil, false, "Binding NUMA dos workers de GPU.", vllmGroupParallel),
		boolFlag("no-numa-bind", "", nil, false, "Desativa binding NUMA.", vllmGroupParallel),
		strFlag("numa-bind-nodes", "", nil, nil, "Lista de NUMA nodes por GPU.", vllmGroupParallel, false),
		strFlag("numa-bind-cpus", "", nil, nil, "Lista de CPUs por GPU para binding NUMA.", vllmGroupParallel, false),
		boolFlag("enable-dbo", "", nil, false, "Habilita Dual Batch Overlap.", vllmGroupParallel),
		boolFlag("no-enable-dbo", "", nil, false, "Desativa Dual Batch Overlap.", vllmGroupParallel),
		intFlag("dbo-prefill-token-threshold", "", nil, 512, "Limiar de tokens para microbatching no prefill DBO.", vllmGroupParallel, intPtr(0), nil),
		intFlag("dbo-decode-token-threshold", "", nil, 32, "Limiar de tokens para microbatching no decode DBO.", vllmGroupParallel, intPtr(0), nil),
		strFlag("worker-cls", "", nil, "auto", "Classe do worker.", vllmGroupParallel, false),
		strFlag("worker-extension-cls", "", nil, nil, "Classe de extensão do worker.", vllmGroupParallel, false),
		boolFlag("enable-elastic-ep", "", nil, false, "Habilita expert parallelism elástico com NCCL stateless.", vllmGroupParallel),
		boolFlag("no-enable-elastic-ep", "", nil, false, "Desativa expert parallelism elástico.", vllmGroupParallel),
		boolFlag("enable-ep-weight-filter", "", nil, false, "Cada rank lê só seus pesos de expert.", vllmGroupParallel),
		boolFlag("no-enable-ep-weight-filter", "", nil, false, "Cada rank lê o conjunto normal de pesos de expert.", vllmGroupParallel),
		intFlag("ubatch-size", "", nil, 0, "Tamanho do ubatch.", vllmGroupParallel, intPtr(0), nil),
		intFlag("cp-kv-cache-interleave-size", "", nil, nil, "Interleave do KV em DCP/PCP.", vllmGroupParallel, intPtr(0), nil),
		enumFlag("dcp-comm-backend", "", nil, []string{"ag_rs", "a2a"}, "ag_rs", "Backend de comunicação do DCP.", vllmGroupParallel),
		intFlag("distributed-timeout-seconds", "", nil, nil, "Timeout de operações distribuídas.", vllmGroupParallel, intPtr(1), nil),
		boolFlag("ray-workers-use-nsight", "", nil, false, "Profiling de workers Ray com nsight.", vllmGroupParallel),
		boolFlag("no-ray-workers-use-nsight", "", nil, false, "Desativa nsight nos workers Ray.", vllmGroupParallel),

		floatFlag("gpu-memory-utilization", "", nil, 0.92, "Fração da VRAM usada pela engine.", vllmGroupKV, floatPtr(0), floatPtr(1)),
		strFlag("kv-cache-memory-bytes", "", nil, nil, "Tamanho fixo do KV cache por GPU; ignora a fração.", vllmGroupKV, false),
		enumFlag("kv-cache-dtype", "", nil, []string{"auto", "fp8", "fp8_e4m3", "fp8_e5m2", "bfloat16", "float16"}, "auto", "Tipo de dado do KV cache.", vllmGroupKV),
		strFlag("kv-cache-dtype-skip-layers", "", nil, "[]", "Camadas ou tipos que pulam a quantização do KV.", vllmGroupKV, false),
		intFlag("block-size", "", nil, nil, "Tokens por bloco de cache.", vllmGroupKV, intPtr(1), nil),
		boolFlag("enable-prefix-caching", "", nil, false, "Reusa KV de prefixos já processados.", vllmGroupKV),
		boolFlag("no-enable-prefix-caching", "", nil, false, "Desativa prefix caching.", vllmGroupKV),
		enumFlag("prefix-caching-hash-algo", "", nil, []string{"sha256", "sha256_cbor", "xxhash", "xxhash_cbor"}, "sha256", "Hash usado no prefix caching.", vllmGroupKV),
		intFlag("num-gpu-blocks-override", "", nil, nil, "Sobrescreve número de blocos GPU para testes de preempção.", vllmGroupKV, intPtr(1), nil),
		floatFlag("kv-offloading-size", "", nil, nil, "Buffer de offload do KV para CPU em GiB.", vllmGroupKV, floatPtr(0), nil),
		enumFlag("kv-offloading-backend", "", nil, []string{"native", "lmcache"}, "native", "Backend de offload do KV.", vllmGroupKV),
		intFlag("mamba-block-size", "", nil, nil, "Bloco do cache Mamba; múltiplo de 8.", vllmGroupKV, intPtr(1), nil),
		enumFlag("mamba-cache-dtype", "", nil, []string{"auto", "float16", "float32"}, "auto", "Dtype do cache Mamba.", vllmGroupKV),
		enumFlag("mamba-ssm-cache-dtype", "", nil, []string{"auto", "float16", "float32"}, "auto", "Dtype do estado SSM Mamba.", vllmGroupKV),
		enumFlag("mamba-cache-mode", "", nil, []string{"none", "all", "align"}, "none", "Estratégia de cache das camadas Mamba.", vllmGroupKV),
		boolFlag("calculate-kv-scales", "", nil, false, "Obsoleto: calcula dinamicamente k/v_scale em fp8.", vllmGroupKV),
		boolFlag("no-calculate-kv-scales", "", nil, false, "Desativa cálculo dinâmico de escalas KV fp8.", vllmGroupKV),
		boolFlag("kv-sharing-fast-prefill", "", nil, false, "Otimização WIP de prefill em KV sharing.", vllmGroupKV),
		boolFlag("no-kv-sharing-fast-prefill", "", nil, false, "Desativa fast prefill em KV sharing.", vllmGroupKV),

		floatFlag("cpu-offload-gb", "", nil, float64(0), "Espaço de offload de pesos para CPU por GPU, em GiB.", vllmGroupWeightOffload, floatPtr(0), nil),
		enumFlag("offload-backend", "", nil, []string{"auto", "uva", "prefetch"}, "auto", "Backend de offload de pesos.", vllmGroupWeightOffload),
		strFlag("cpu-offload-params", "", nil, nil, "Segmentos de nome de parâmetro a offloadar via UVA.", vllmGroupWeightOffload, false),
		intFlag("offload-group-size", "", nil, 0, "Agrupa cada N camadas para offload por grupo.", vllmGroupWeightOffload, intPtr(0), nil),
		intFlag("offload-num-in-group", "", nil, 1, "Quantas camadas offloadar por grupo.", vllmGroupWeightOffload, intPtr(0), nil),
		intFlag("offload-prefetch-step", "", nil, 1, "Camadas a prefetch à frente.", vllmGroupWeightOffload, intPtr(0), nil),
		strFlag("offload-params", "", nil, nil, "Segmentos de nome para prefetch offloading.", vllmGroupWeightOffload, false),

		strFlag("limit-mm-per-prompt", "", nil, "{}", "Máximo de itens por modalidade por prompt.", vllmGroupMultimodal, false),
		boolFlag("language-model-only", "", nil, false, "Desliga todas as entradas multimodais.", vllmGroupMultimodal),
		boolFlag("no-language-model-only", "", nil, false, "Permite entradas multimodais.", vllmGroupMultimodal),
		strFlag("mm-processor-kwargs", "", nil, nil, "Args para o processador multimodal do modelo.", vllmGroupMultimodal, false),
		floatFlag("mm-processor-cache-gb", "", nil, float64(4), "Cache do processador multimodal em GiB.", vllmGroupMultimodal, floatPtr(0), nil),
		enumFlag("mm-processor-cache-type", "", nil, []string{"lru", "shm"}, "lru", "Tipo do cache do processador multimodal.", vllmGroupMultimodal),
		intFlag("mm-shm-cache-max-object-size-mb", "", nil, 128, "Limite por objeto no cache shm, em MiB.", vllmGroupMultimodal, intPtr(1), nil),
		strFlag("media-io-kwargs", "", nil, nil, "Args de processamento de mídia, como num_frames.", vllmGroupMultimodal, false),
		boolFlag("interleave-mm-strings", "", nil, false, "Prompts multimodais totalmente intercalados.", vllmGroupMultimodal),
		boolFlag("no-interleave-mm-strings", "", nil, false, "Desativa intercalação completa de strings multimodais.", vllmGroupMultimodal),
		boolFlag("enable-mm-embeds", "", nil, false, "Aceita embeddings multimodais como entrada.", vllmGroupMultimodal),
		boolFlag("no-enable-mm-embeds", "", nil, false, "Desativa embeddings multimodais como entrada.", vllmGroupMultimodal),
		boolFlag("skip-mm-profiling", "", nil, false, "Pula profiling de memória multimodal.", vllmGroupMultimodal),
		boolFlag("no-skip-mm-profiling", "", nil, false, "Executa profiling de memória multimodal.", vllmGroupMultimodal),
		enumFlag("mm-encoder-tp-mode", "", nil, []string{"weights", "data"}, "weights", "Como o encoder multimodal usa tensor parallelism.", vllmGroupMultimodal),
		strFlag("mm-encoder-attn-backend", "", nil, nil, "Backend de atenção do encoder ViT.", vllmGroupMultimodal, false),
		enumFlag("mm-encoder-attn-dtype", "", nil, []string{"fp8", "None"}, nil, "Dtype da atenção do encoder ViT.", vllmGroupMultimodal),
		strFlag("mm-encoder-fp8-scale-path", "", nil, nil, "Caminho das escalas FP8 do encoder.", vllmGroupMultimodal, false),
		strFlag("mm-encoder-fp8-scale-save-path", "", nil, nil, "Caminho para salvar escalas FP8 do encoder.", vllmGroupMultimodal, false),
		floatFlag("mm-encoder-fp8-scale-save-margin", "", nil, 1.5, "Margem das escalas FP8 do encoder.", vllmGroupMultimodal, floatPtr(0), nil),
		boolFlag("mm-encoder-only", "", nil, false, "Executa só o encoder multimodal e pula o LM.", vllmGroupMultimodal),
		boolFlag("no-mm-encoder-only", "", nil, false, "Executa encoder multimodal e LM.", vllmGroupMultimodal),
		enumFlag("mm-tensor-ipc", "", nil, []string{"direct_rpc", "torch_shm"}, "direct_rpc", "IPC de tensores multimodais.", vllmGroupMultimodal),
		floatFlag("video-pruning-rate", "", nil, nil, "Fração de tokens de vídeo podados por EVS.", vllmGroupMultimodal, floatPtr(0), floatPtr(1)),

		boolFlag("enable-lora", "", nil, false, "Habilita adapters LoRA.", vllmGroupLora),
		boolFlag("no-enable-lora", "", nil, false, "Desativa adapters LoRA.", vllmGroupLora),
		intFlag("max-loras", "", nil, 1, "Máximo de LoRAs em um único batch.", vllmGroupLora, intPtr(1), nil),
		intFlag("max-lora-rank", "", nil, 16, "Rank máximo de LoRA.", vllmGroupLora, intPtr(1), intPtr(512)),
		intFlag("max-cpu-loras", "", nil, nil, "Máximo de LoRAs em RAM; deve ser >= max_loras.", vllmGroupLora, intPtr(1), nil),
		enumFlag("lora-dtype", "", nil, []string{"auto", "float16", "bfloat16"}, "auto", "Dtype dos LoRAs.", vllmGroupLora),
		strFlag("lora-target-modules", "", nil, nil, "Restringe LoRA a sufixos de módulo.", vllmGroupLora, false),
		boolFlag("fully-sharded-loras", "", nil, false, "Camadas LoRA totalmente fatiadas por TP.", vllmGroupLora),
		boolFlag("no-fully-sharded-loras", "", nil, false, "Usa LoRA sem fatiamento total por TP.", vllmGroupLora),
		strFlag("default-mm-loras", "", nil, nil, "Mapeia modalidades para caminhos LoRA.", vllmGroupLora, false),
		boolFlag("enable-tower-connector-lora", "", nil, false, "Habilita LoRA no encoder/connector de modelos multimodais.", vllmGroupLora),
		boolFlag("no-enable-tower-connector-lora", "", nil, false, "Desativa LoRA no encoder/connector multimodal.", vllmGroupLora),
		boolFlag("specialize-active-lora", "", nil, false, "CUDA graphs por contagem de LoRAs ativos.", vllmGroupLora),
		boolFlag("no-specialize-active-lora", "", nil, false, "Desativa especialização de CUDA graphs por LoRAs ativos.", vllmGroupLora),

		strFlag("otlp-traces-endpoint", "", nil, nil, "Endpoint OpenTelemetry para traces.", vllmGroupObservability, false),
		enumFlag("collect-detailed-traces", "", nil, []string{"all", "model", "worker", "None"}, nil, "Traces detalhados por módulo.", vllmGroupObservability),
		strFlag("show-hidden-metrics-for-version", "", nil, nil, "Reativa métricas Prometheus depreciadas de uma versão.", vllmGroupObservability, false),
		boolFlag("enable-server-load-tracking", "", nil, false, "Rastreia carga do servidor.", vllmGroupObservability),
		boolFlag("no-enable-server-load-tracking", "", nil, false, "Desativa rastreamento de carga do servidor.", vllmGroupObservability),
		boolFlag("cudagraph-metrics", "", nil, false, "Métricas de CUDA graph.", vllmGroupObservability),
		boolFlag("no-cudagraph-metrics", "", nil, false, "Desativa métricas de CUDA graph.", vllmGroupObservability),
		boolFlag("kv-cache-metrics", "", nil, false, "Métricas de residência do KV cache.", vllmGroupObservability),
		boolFlag("no-kv-cache-metrics", "", nil, false, "Desativa métricas de KV cache.", vllmGroupObservability),
		floatFlag("kv-cache-metrics-sample", "", nil, 0.01, "Taxa de amostragem das métricas de KV cache.", vllmGroupObservability, floatPtr(0), floatPtr(1)),
		boolFlag("enable-mfu-metrics", "", nil, false, "Habilita Model FLOPs Utilization metrics.", vllmGroupObservability),
		boolFlag("no-enable-mfu-metrics", "", nil, false, "Desativa MFU metrics.", vllmGroupObservability),
		boolFlag("enable-layerwise-nvtx-tracing", "", nil, false, "Tracing NVTX por camada.", vllmGroupObservability),
		boolFlag("no-enable-layerwise-nvtx-tracing", "", nil, false, "Desativa tracing NVTX por camada.", vllmGroupObservability),
		boolFlag("enable-logging-iteration-details", "", nil, false, "Loga detalhes por iteração.", vllmGroupObservability),
		boolFlag("no-enable-logging-iteration-details", "", nil, false, "Desativa logs detalhados por iteração.", vllmGroupObservability),

		strFlag("max-num-batched-tokens", "", nil, nil, "Máximo de tokens por iteração; aceita inteiro ou 1k.", vllmGroupScheduler, false),
		intFlag("max-num-seqs", "", nil, nil, "Máximo de sequências por iteração.", vllmGroupScheduler, intPtr(1), nil),
		boolFlag("enable-chunked-prefill", "", nil, false, "Fatia prefills longos.", vllmGroupScheduler),
		boolFlag("no-enable-chunked-prefill", "", nil, false, "Desativa chunked prefill.", vllmGroupScheduler),
		intFlag("long-prefill-token-threshold", "", nil, 0, "A partir de quantos tokens um prompt é considerado longo.", vllmGroupScheduler, intPtr(0), nil),
		intFlag("max-num-partial-prefills", "", nil, 1, "Prefills parciais concorrentes.", vllmGroupScheduler, intPtr(1), nil),
		intFlag("max-long-partial-prefills", "", nil, 1, "Prompts longos prefillados concorrentemente.", vllmGroupScheduler, intPtr(1), nil),
		enumFlag("scheduling-policy", "", nil, []string{"fcfs", "priority"}, "fcfs", "Política de escalonamento.", vllmGroupScheduler),
		boolFlag("async-scheduling", "", nil, false, "Escalonamento assíncrono.", vllmGroupScheduler),
		boolFlag("no-async-scheduling", "", nil, false, "Desativa escalonamento assíncrono.", vllmGroupScheduler),
		boolFlag("scheduler-reserve-full-isl", "", nil, true, "Reserva o ISL completo antes de admitir.", vllmGroupScheduler),
		boolFlag("no-scheduler-reserve-full-isl", "", nil, false, "Não reserva ISL completo antes de admitir.", vllmGroupScheduler),
		boolFlag("disable-chunked-mm-input", "", nil, false, "Não fatia item multimodal no chunked prefill.", vllmGroupScheduler),
		boolFlag("no-disable-chunked-mm-input", "", nil, false, "Permite fatiar item multimodal no chunked prefill.", vllmGroupScheduler),
		strFlag("scheduler-cls", "", nil, "Scheduler", "Classe de scheduler customizada.", vllmGroupScheduler, false),
		intFlag("stream-interval", "", nil, 1, "Intervalo de streaming em tokens.", vllmGroupScheduler, intPtr(1), nil),

		strFlag("compilation-config", "cc", nil, nil, "Config de torch.compile e CUDA graphs em JSON.", vllmGroupCompilation, false),
		intFlag("optimization-level", "O", nil, 2, "Nível de otimização; 0 prioriza startup, 3 desempenho.", vllmGroupCompilation, intPtr(0), intPtr(3)),
		enumFlag("performance-mode", "", nil, []string{"balanced", "interactivity", "throughput"}, "balanced", "Perfil de runtime.", vllmGroupCompilation),
		strFlag("cudagraph-capture-sizes", "", nil, nil, "Tamanhos de batch capturados em CUDA graph.", vllmGroupCompilation, false),
		intFlag("max-cudagraph-capture-size", "", nil, nil, "Maior tamanho de captura de CUDA graph.", vllmGroupCompilation, intPtr(1), nil),

		strFlag("moe-backend", "", nil, "auto", "Backend dos kernels de MoE; auto escolhe pelo modelo/hardware.", vllmGroupKernels, false),
		boolFlag("enable-flashinfer-autotune", "", nil, false, "Autotuning do FlashInfer no warmup.", vllmGroupKernels),
		boolFlag("no-enable-flashinfer-autotune", "", nil, false, "Desativa autotuning do FlashInfer.", vllmGroupKernels),
		strFlag("ir-op-priority", "", nil, nil, "Prioridade de ops da IR do vLLM no forward.", vllmGroupKernels, false),
		strFlag("kernel-config", "", nil, nil, "Config consolidada de kernels em JSON.", vllmGroupKernels, false),

		strFlag("speculative-config", "sc", nil, nil, "Configuração de speculative decoding em JSON.", vllmGroupAdvancedConfigs, false),
		strFlag("kv-transfer-config", "", nil, nil, "Transferência distribuída de KV cache para prefill/decode desagregado.", vllmGroupAdvancedConfigs, false),
		strFlag("kv-events-config", "", nil, nil, "Publicação de eventos de KV cache.", vllmGroupAdvancedConfigs, false),
		strFlag("ec-transfer-config", "", nil, nil, "Transferência distribuída de EC cache.", vllmGroupAdvancedConfigs, false),
		strFlag("weight-transfer-config", "", nil, nil, "Transferência de pesos durante treino RL.", vllmGroupAdvancedConfigs, false),
		strFlag("reasoning-config", "", nil, nil, "Config de modelo de reasoning.", vllmGroupAdvancedConfigs, false),
		strFlag("attention-config", "ac", nil, nil, "Config detalhada de atenção e overrides de backend.", vllmGroupAdvancedConfigs, false),
		strFlag("profiler-config", "", nil, nil, "Config de profiling com torch profiler.", vllmGroupAdvancedConfigs, false),
		strFlag("additional-config", "", nil, "{}", "Config adicional específica de plataforma.", vllmGroupAdvancedConfigs, false),
	} {
		add(spec)
	}

	return domain.BackendValidationSchema{
		SchemaVersion: 1,
		Kind:          domain.ValidationSchemaCLIFlagsV1,
		BackendKind:   domain.BackendKindVLLM,
		BackendID:     "vllm-default",
		Source: domain.SchemaSource{
			GeneratedFrom: "vllm.md curated reference",
			SourceVersion: "curated-vllm",
			Editable:      true,
		},
		Flags:        flags,
		Presentation: vllmPresentation(),
	}
}

func vllmPresentation() *domain.Presentation {
	return &domain.Presentation{Groups: []domain.PresentationGroup{
		{Name: vllmGroupEssentials, Highlighted: true, Flags: []string{"host", "port", "api-key", "served-model-name", "dtype", "max-model-len", "quantization", "tensor-parallel-size", "gpu-memory-utilization", "kv-cache-dtype", "enable-prefix-caching", "max-num-batched-tokens", "max-num-seqs", "enable-chunked-prefill", "uvicorn-log-level"}},
		{Name: vllmGroupServer, Flags: []string{"config", "api-server-count", "headless", "grpc", "disable-log-stats", "enable-log-requests", "no-enable-log-requests", "aggregate-engine-logging", "shutdown-timeout", "gdn-prefill-backend", "fail-on-environ-validation", "no-fail-on-environ-validation"}},
		{Name: vllmGroupFrontend, Flags: []string{"host", "port", "uds", "api-key", "root-path", "allowed-origins", "allowed-methods", "allowed-headers", "allow-credentials", "no-allow-credentials", "ssl-certfile", "ssl-keyfile", "ssl-ca-certs", "ssl-cert-reqs", "ssl-ciphers", "enable-ssl-refresh", "no-enable-ssl-refresh", "chat-template", "chat-template-content-format", "default-chat-template-kwargs", "response-role", "enable-auto-tool-choice", "no-enable-auto-tool-choice", "tool-call-parser", "tool-parser-plugin", "reasoning-parser", "lora-modules", "max-log-len", "enable-request-id-headers", "no-enable-request-id-headers", "disable-fastapi-docs", "no-disable-fastapi-docs", "enable-offline-docs", "no-enable-offline-docs", "disable-uvicorn-access-log", "no-disable-uvicorn-access-log", "disable-access-log-for-endpoints", "uvicorn-log-level", "middleware", "return-tokens-as-token-ids", "no-return-tokens-as-token-ids", "enable-prompt-tokens-details", "no-enable-prompt-tokens-details", "enable-force-include-usage", "no-enable-force-include-usage", "h11-max-header-count", "h11-max-incomplete-event-size"}},
		{Name: vllmGroupModel, Flags: []string{"served-model-name", "tokenizer", "tokenizer-mode", "revision", "code-revision", "tokenizer-revision", "dtype", "max-model-len", "quantization", "seed", "trust-remote-code", "no-trust-remote-code", "hf-token", "hf-overrides", "hf-config-path", "config-format", "model-impl", "runner", "convert", "enforce-eager", "no-enforce-eager", "enable-sleep-mode", "no-enable-sleep-mode", "disable-sliding-window", "no-disable-sliding-window", "disable-cascade-attn", "no-disable-cascade-attn", "max-logprobs", "logprobs-mode", "generation-config", "override-generation-config", "enable-prompt-embeds", "no-enable-prompt-embeds", "skip-tokenizer-init", "no-skip-tokenizer-init", "pooler-config", "allowed-local-media-path", "allowed-media-domains", "renderer-num-workers", "logits-processors", "override-attention-dtype", "io-processor-plugin", "allow-deprecated-quantization", "no-allow-deprecated-quantization"}},
		{Name: vllmGroupLoad, Flags: []string{"load-format", "download-dir", "ignore-patterns", "model-loader-extra-config", "safetensors-load-strategy", "safetensors-prefetch-block-size", "safetensors-prefetch-num-threads", "pt-load-map-location", "use-tqdm-on-load", "no-use-tqdm-on-load"}},
		{Name: vllmGroupAttention, Flags: []string{"attention-backend", "mamba-backend", "enable-mamba-cache-stochastic-rounding", "no-enable-mamba-cache-stochastic-rounding", "mamba-cache-philox-rounds"}},
		{Name: vllmGroupStructured, Flags: []string{"reasoning-parser", "reasoning-parser-plugin", "structured-outputs-config"}},
		{Name: vllmGroupParallel, Flags: []string{"tensor-parallel-size", "pipeline-parallel-size", "data-parallel-size", "data-parallel-size-local", "data-parallel-rank", "data-parallel-start-rank", "data-parallel-address", "data-parallel-rpc-port", "data-parallel-backend", "data-parallel-external-lb", "data-parallel-hybrid-lb", "decode-context-parallel-size", "prefill-context-parallel-size", "enable-expert-parallel", "no-enable-expert-parallel", "enable-eplb", "no-enable-eplb", "eplb-config", "expert-placement-strategy", "all2all-backend", "distributed-executor-backend", "disable-custom-all-reduce", "no-disable-custom-all-reduce", "nnodes", "node-rank", "master-addr", "master-port", "max-parallel-loading-workers", "numa-bind", "no-numa-bind", "numa-bind-nodes", "numa-bind-cpus", "enable-dbo", "no-enable-dbo", "dbo-prefill-token-threshold", "dbo-decode-token-threshold", "worker-cls", "worker-extension-cls", "enable-elastic-ep", "no-enable-elastic-ep", "enable-ep-weight-filter", "no-enable-ep-weight-filter", "ubatch-size", "cp-kv-cache-interleave-size", "dcp-comm-backend", "distributed-timeout-seconds", "ray-workers-use-nsight", "no-ray-workers-use-nsight"}},
		{Name: vllmGroupKV, Flags: []string{"gpu-memory-utilization", "kv-cache-memory-bytes", "kv-cache-dtype", "kv-cache-dtype-skip-layers", "block-size", "enable-prefix-caching", "no-enable-prefix-caching", "prefix-caching-hash-algo", "num-gpu-blocks-override", "kv-offloading-size", "kv-offloading-backend", "mamba-block-size", "mamba-cache-dtype", "mamba-ssm-cache-dtype", "mamba-cache-mode", "calculate-kv-scales", "no-calculate-kv-scales", "kv-sharing-fast-prefill", "no-kv-sharing-fast-prefill"}},
		{Name: vllmGroupWeightOffload, Flags: []string{"cpu-offload-gb", "offload-backend", "cpu-offload-params", "offload-group-size", "offload-num-in-group", "offload-prefetch-step", "offload-params"}},
		{Name: vllmGroupMultimodal, Flags: []string{"limit-mm-per-prompt", "language-model-only", "no-language-model-only", "mm-processor-kwargs", "mm-processor-cache-gb", "mm-processor-cache-type", "mm-shm-cache-max-object-size-mb", "media-io-kwargs", "interleave-mm-strings", "no-interleave-mm-strings", "enable-mm-embeds", "no-enable-mm-embeds", "skip-mm-profiling", "no-skip-mm-profiling", "mm-encoder-tp-mode", "mm-encoder-attn-backend", "mm-encoder-attn-dtype", "mm-encoder-fp8-scale-path", "mm-encoder-fp8-scale-save-path", "mm-encoder-fp8-scale-save-margin", "mm-encoder-only", "no-mm-encoder-only", "mm-tensor-ipc", "video-pruning-rate"}},
		{Name: vllmGroupLora, Flags: []string{"enable-lora", "no-enable-lora", "max-loras", "max-lora-rank", "max-cpu-loras", "lora-dtype", "lora-target-modules", "fully-sharded-loras", "no-fully-sharded-loras", "default-mm-loras", "enable-tower-connector-lora", "no-enable-tower-connector-lora", "specialize-active-lora", "no-specialize-active-lora"}},
		{Name: vllmGroupObservability, Flags: []string{"otlp-traces-endpoint", "collect-detailed-traces", "show-hidden-metrics-for-version", "enable-server-load-tracking", "no-enable-server-load-tracking", "cudagraph-metrics", "no-cudagraph-metrics", "kv-cache-metrics", "no-kv-cache-metrics", "kv-cache-metrics-sample", "enable-mfu-metrics", "no-enable-mfu-metrics", "enable-layerwise-nvtx-tracing", "no-enable-layerwise-nvtx-tracing", "enable-logging-iteration-details", "no-enable-logging-iteration-details"}},
		{Name: vllmGroupScheduler, Flags: []string{"max-num-batched-tokens", "max-num-seqs", "enable-chunked-prefill", "no-enable-chunked-prefill", "long-prefill-token-threshold", "max-num-partial-prefills", "max-long-partial-prefills", "scheduling-policy", "async-scheduling", "no-async-scheduling", "scheduler-reserve-full-isl", "no-scheduler-reserve-full-isl", "disable-chunked-mm-input", "no-disable-chunked-mm-input", "scheduler-cls", "stream-interval"}},
		{Name: vllmGroupCompilation, Flags: []string{"compilation-config", "optimization-level", "performance-mode", "cudagraph-capture-sizes", "max-cudagraph-capture-size"}},
		{Name: vllmGroupKernels, Flags: []string{"moe-backend", "enable-flashinfer-autotune", "no-enable-flashinfer-autotune", "ir-op-priority", "kernel-config"}},
		{Name: vllmGroupAdvancedConfigs, Flags: []string{"speculative-config", "kv-transfer-config", "kv-events-config", "ec-transfer-config", "weight-transfer-config", "reasoning-config", "attention-config", "profiler-config", "additional-config"}},
	}}
}
